### ISSUE TITLE
[Panel] Add `flip` option to pages sections

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#1009]
Currently, the only way to change the order of pages in the pages section is the `sortBy` option. While this is probably enough in most use cases, an option to simply flip the »natural« oder would be helpful. Especially in cases where the collection of pages is relatively large and presorted, I assume reversing the order to be more efficient than to sort the whole collection again.

**Comment by mrflix** [comment]
I just stumbled over this issue because I found out that `flip: true` didn't work in `type: pages` sections as expected from kirby v2. Use case:

I sync my local content with the server via rsync. On some websites there are tons of projects. When a new one gets added it should appear at the front. So it's manually ordered there. Then the sorting of all projects changes increases by one. Example: projects 1....32 turn into 2..33. This makes the sync re-sync all content again although just the folder naming changed. Because of this in v2 I used to flip the pages in the sidebar and in the template so that adding a new project makes it number 33 but it's still at the top.

Or is there a smarter way to handle this?
