### ISSUE TITLE
[cms] Front login form: a wrong password return an exception

### ISSUE THREAD

**Issue by vauvarin** [getkirby/kirby#1027]
I built a login form in a front-end page and test in my controller if the user exist with this code:

``` 
$user = $kirby->user( $email_login );
$check_password = $user->login( $password_login );
```
When for testing, I fill in the password input with a wrong password (longer than 8 characters) I've got an exception:
```
Kirby \ Exception \ InvalidArgumentException (error.user.password.invalid)
Please enter a valid password. Passwords must be at least 8 characters long.
```

**Comment by bastianallgeier** [comment]
Sorry for the delay! What do you expect to happen? Just return false if the password is incorrect?

**Comment by bastianallgeier** [comment]
@vauvarin ping :)

**Comment by lukasbestle** [comment]
I think the current behavior (throw an Exception) makes sense, otherwise there would be no way to know what the error was. If the error message is not needed by the dev, it's always possible to wrap the `login()` call with `try {} catch(Exception $e) {}`

So the only real issue in my opinion is the error message. It doesn't quite fit if the entered password is already longer than 8 chars but just incorrect. I think there should be an error like "The entered password is incorrect." for this case instead (no matter if the entered password is longer than 8 chars or not).

**Comment by rasteiner** [comment]
I've just run into this as well, while using the REST API to login. 
I'd personally prefer the error message to be the same as the one that is thrown when the username is wrong (which is `Invalid email or password`). Otherwise we give (imho) away too much information. 
An attacker could now first guess usernames until he gets one right, and then focus only on the password.

Also, it seems like the response is **not** artificially delayed when only the password is wrong. (At least here a wrong password gets a response after about 400ms, while a wrong username gets a response after about 2 seconds).

**Comment by bastianallgeier** [comment]
✅  I fixed the exception message. I agree with Lukas that throwing the exception is still the best solution and also the solution that's most "comfortable" to handle further error responses in the frontend. 

@rasteiner The sleeping mechanism is in my opinion not the duty of the login method. We implement that in our API authentication and it should probably also be implemented manually when you build a frontend login. We could only provide a helper for that.

**Comment by rasteiner** [comment]
@bastianallgeier I agree. 

What I was trying to say is that the API route doesn't sleep if the user exists, but the password is wrong.

https://github.com/k-next/kirby/blob/fcc2407cd9ac3145488397a7117cc37dd3f2f8ec/config/api/routes/auth.php#L35

Here, if the password is wrong, `login()` doesn't return `false`, but throws an error. 
That error isn't catched. Therefore you exit the function before you reach the `usleep()` call.
