### ISSUE TITLE
ability to demote admin for request

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#1052]
this is a feature request.

We may find ourselves in situations where we want to disable admin rights which we might have been given from a session. 

This is to prevent csrf attacks where a crsf token might not be applicable. 

for example `$kirby->impersonate('anon')` might do the opposite of `$kirby->impersonate('kirby')` and remove all privileges. 

Usecase

```php
function frontendMagicalApi($request) {
  $kirby->impersonate('anon'); //limit damage if something goes wrong

  $kirby->eval($request); //this seems legit!
}
```

**Comment by bnomei** [comment]
since impersonate does not only take the admin kirby user as string but also real user objects my suggestion would be be to create api get/post/put/patch related permission and a simple way do create a user with these permissions on the fly.
having to remember special user names seems a bad choice imho.
making the dev define an real “api-get”-user on-the-fly or via file with these permissions and using that for impersonate seems more clear.

**Comment by rasteiner** [comment]
this issue is about reversing the effects of `$kirby->impersonate('kirby')`. I wouldn't bind this requirement to that other one of securing http endpoints. IMHO that should be done by implementing, for example, a middleware system for the router (but this is off topic). 

I think it's important to have a method (really any method; don't care if it's magic usernames or something else) that allows us to undo  `$kirby->impersonate('kirby')` anywhere we have to work with user content, and that data might come from any source (a file on the server?) in the context of any kind of http request or cli script.

It's only damage control and an attempt at protecting sensible parts of the application from privilege escalation attacks.

**Comment by bastianallgeier** [comment]
You can do the following with the impersonate method: 

```php
// admin 
$kirby->impersonate('kirby');

// any other existing user = rights depend on the role
$kirby->impersonate('my@otheruser.com');

// no user = no rights
$kirby->impersonate();
```
