### ISSUE TITLE
[Panel] Pages section image fails (did not before)

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1179]
**Describe the bug**
pages section image broken in current nightly. was not broken in same setup before.

**To Reproduce**
1. in child create file section for single image called `cover`
2. in child upload an image
3. parent in blueprint list childs and set image to cover
```yml
image: page.images.filterBy('template', 'cover').first
```

**Expected behavior**
show image like it did a few builds agon

**Kirby Version**
current nightly 6221a6b

**Console output**
```
Object { status: "error", exception: "TypeError", message: "Argument 1 passed to Kirby\\Cms\\Page::panelIcon() must be of the type array, string given, called in /Users/XXXX/www/vendor/getkirby/cms/config/sections/pages.php on line 176", file: "vendor/getkirby/cms/src/Cms/Page.php", line: 835, code: 500 }
```

**Desktop (please complete the following information):**
macos mojave, mamppro 4 apache php 7.2, firefox dev 64

**Comment by bastianallgeier** [comment]
✅

**Comment by bnomei** [comment]
@bastianallgeier sorry to bug you (pun intended). since you commits do not name the issue (which you could do writing `#number` in the commit desc real easily) please tell me what was wrong and if using next nighty will just fix it?

**Comment by bastianallgeier** [comment]
You are right, I should mention the issue number in my commits. 

It will be fixed in the next nightly. That's the commit: https://github.com/k-next/kirby/commit/a3500a759640ee9b00135f5d340b55de59977da3

I had refactored the panelIcon method, but didn't think about the single-string option to set the image, which then broke the panelIcon method type check. There are now tests in place for this.
