### ISSUE TITLE
[Panel] JS / CSS of plugins aren't loaded if their mtime is older than the concatenated assets

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1200]
**Describe the bug**
As described on Slack [here](https://getkirby.slack.com/archives/CBN859614/p1542555581707900), the `index.css / index.js` of manually-installed plugins are not loaded if their `mtime` is older than the `mtime` of the concatenated `/media/plugins/index.js` / `/media/plugins/index.css`.

Here's [the culprit line](https://github.com/k-next/kirby/blob/e31bb4d7fa907da832d08dcee80f92a1d0ec6adc/src/Cms/PluginAssets.php#L44).

Prevents copy-pasting plugins from one installation to another, or from a github repo to a newer installation.

Shows this error message as a result:

![48557780-f0cf3180-e8e7-11e8-9726-37c6be5e8a27](https://user-images.githubusercontent.com/14079751/48701652-43159880-ebef-11e8-93b2-0262a5aa2772.png)

**To Reproduce**
1. New starterkit + latest nightly
2. Create a placeholder plugin (making sure `/media/plugins/index.js` / `/media/plugins/index.css` are generated)
3. Copy-paste a plugin with older `mtime` ([kirby-locator](https://github.com/sylvainjule/kirby-locator) for example)
4. Add this blueprint snippet somewhere:
```yaml
mymap:
  label: Location
  type: locator
```
5. Should show "The field type **mymap** does not exist"

**Expected behavior**
Perhaps: Keep a table / identify concatenated plugins in the cache, and concatenate plugins whose `mtime` is older than the cached `/media/plugins/index.{js|css}` **if** they have not been included yet.

**Comment by rasteiner** [comment]
maybe Kirby could compare the size of the bundle with the sum of sizes of the single plugin files.

We should be able to get `mtime` and `size` with a single system call ([`stat()`](http://php.net/manual/en/function.stat.php)). 
Of course it's no guarantee (the copied file could happen to have the same size as the placeholder plugin), but it adds to the heuristic without making the comparison much slower.

We could also hash all plugin mtimes and sizes together and save the hash into the bundle filename. So instead of checking if the bundle is "newer" than the "newest" plugin, it checks if "anything" has changed: it invalidates the cache also if a date has become older. 

PS: all this just to prevent opening all files each time.

**Comment by bastianallgeier** [comment]
✅ I think I fixed it. I have updated the F::modified method to check filemtime and filectime, which is a lot more reliable. To save a second call I used the stat() method as @rasteiner suggested. Seems to work great so far. Please have a look at it after the nightly build and let me know if it works for you too.

**Comment by sylvainjule** [comment]
Seems fixed! Thanks.
