### ISSUE TITLE
Panel: Sometimes very long loading times

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#1340]
**Describe the bug**
When opening a page for the first time after rewriting the cache, we sometimes experience loading times of 2, 3 or more seconds for panel pages with sections (featuring ~100 entries each, 20 shown per pagination page).

**To Reproduce**
Fortunately/unfortunately, when I came across especially long waits this morning and decided to record a screencast showing the phenomenon, it stopped. I did not change anything in my setting, saved entries, emptied the cache, but could not reproduce the slow loading time.

Maybe someone else has more "luck"?

**Kirby Version**
3.0.0-RC-4.1

**Desktop (please complete the following information):**
 - macOS Mojave
 - Firefox 64

**Comment by bastianallgeier** [comment]
I think we should look into this together after the launch. Unfortunately I have no chance to debug this before Tuesday.

**Comment by johannahoerrmann** [comment]
Ok. @nilshoerrmann and I will keep our eyes peeled for when this occurs again.

**Comment by SebastianEberlein** [comment]
I have this issue on a more complex blueprint, too. I haven’t had the time to investigate what causes the issue, though.

But I noticed that it loads slower on my Vagrant machine than our stage server, since Vagrant has less system resources.

Yesterday, I ran an ffmpeg video conversion on my iMac while editing content in the panel. FFmpeg used almost 100% CPU. The frontend on my Vagrant machine still loaded fast, but the complex blueprint loaded very very slow.

When I have time I will test if removing a particular blueprint section improves the loading / rendering time.

Kirby Version: 3.0.0 (official release)

**Comment by bastianallgeier** [comment]
@johannahoerrmann @SebastianEberlein is this still happening with the current version?

**Comment by SebastianEberlein** [comment]
After you fixed the duplicate HTTP calls in 3.0.3, I haven’t noticed any performance issues when the panel loads :)

**Comment by johannahoerrmann** [comment]
Not as far as I can see! The panel is loading MUCH faster now. I'll close this.
