### ISSUE TITLE
Reintroduce 'options: hide' for page blueprints

### ISSUE THREAD

**Issue by SirNovi** [getkirby/kirby#1372]
I assumed the 'read' option was the new 'hide' equivalent but this doesn't seem to be the case, therefore I would really appreciate it if we could get the old 'hide' option back.

**Comment by bastianallgeier** [comment]
options: read should in fact solve this. What's not working for you?

**Comment by SirNovi** [comment]
Hypothetical setup: 

```
sections:
  pages:
    type: pages
    parent: site.find("hiddenpage")
``` 
The bluprint for hiddenpage uses `read: false`

With this setup the "hiddenpage" does not appear in the panel and is indeed hidden. The pages section does still work as it will show all children of "hiddenpage". But adding new pages via this section will throw an error. (The page "hiddenpage" cannot be found)

Now, I must admit that I'm not sure the hide option in v2 actually behaved differently. But I do think that there should be an option that makes pages _only_ hidden for the panel user and not for the panel itself as seems to be the case with the `read` option.

**Comment by medienbaecker** [comment]
@bastianallgeier This is also a deal breaker for a current project of mine. Maybe my use case helps you understand what this issue is about:

Since the builder field still has some issues, you have to use subpages for a "one-pager" setup.
Most of the time you need separate sections (or modules) **and** subpages, though. Therefore the sections should live in a hidden `sections` folder to have separate sorting numbers. Similar to the `_modules` folder with the modules plugin in Kirby 2.

It's not possible to hide the `sections` folder without setting `read` to `false`. But that means I can't add pages to the pages section:

![sections](https://user-images.githubusercontent.com/7975568/53085844-12057680-3504-11e9-96dc-ebbc6785e4ca.gif)

I'd suggest adding a `hide` option that simply hides the page from pages sections and the breadcrumb navigation.

**Comment by medienbaecker** [comment]
@bastianallgeier Is there anything I can do to help you remove the "missing information" label?

**Comment by silllli** [comment]
Also when setting `read` to `false` the page can't be fetched via the API anymore (accessing it with a template still works).

**Comment by distantnative** [comment]
https://kirby.nolt.io/124
