### ISSUE TITLE
`page.update:after` hook seems to work with a cached the collection

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1401]
Probably similar to this old bug: https://github.com/getkirby/kirby/issues/747
**Describe the bug**
When trying to sort the siblings collection by date after updating a date, the new date is not picked up. The page itself does pick up the new date, though.

Here is a short example to illustrate the issue:

```
<?php

Kirby::plugin('texnixe/examplehook', [
    'hooks' => [
	    'page.update:after' => function ($page) {
		$dates = $page->siblings()->listed()->pluck('date');
		
			try {
			$page->parent()->update([
			'date'  => json_encode($page->date()),
			'alldates'    => json_encode($dates)
				
			]);
			} catch(Exception $e) {

			throw new Exception( $e->getMessage());
			
			}
    	}
   	]
]);
```
This will update the parent page with the new date in the `date` field, while the `alldates` field will not store the new date.

See this post in the forum: https://forum.getkirby.com/t/porting-panel-page-update-hook-to-kirby-3-syntax/12431/4

**Comment by afbora** [comment]
I think the reason for this issue being labeled as `difficult: hard` is that the page is being updated in the `ModelWithContent` class instead of `PageActions`.

Why don't we do the functions of the method in the `ModelWithContent` class in `PageActions`?
Do you think this is a wrong implement?

**Here sample implement that fixed issue and working properly:**

### Current

**PageActions**:
https://github.com/getkirby/kirby/blob/develop/src/Cms/PageActions.php#L753-L767

**ModelWithContent**
https://github.com/getkirby/kirby/blob/develop/src/Cms/ModelWithContent.php#L611-L632

### Implement

**Refactored in PageActions**
_Now ignored `ModelWithContent::update()` method_

https://github.com/afbora/kirby/blob/fix/1401-cached-collection-after-page-update/src/Cms/PageActions.php#L753-L791

**Comment by bastianallgeier** [comment]
✅
