### ISSUE TITLE
$languages->map(): Adding additional data not working

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1488]
I would have expected this code to work:

```
$languages = $kirby->languages()->map(function($l) {
  $langOrder = ['fr' => 1, 'de' => 2, 'en' => 3];
  $l->order = $langOrder[$l->code()];
  return $l;
});

foreach($languages as $l) {
  dump($l->order());
}
```
But that doesn't work.

Nor is it possible to add custom properties directly in the language files like this:

```
return [
  'code' => 'en',
  'default' => true,
  'direction' => 'ltr',
  'locale' => 'en_Us',
  'name' => 'English',
  'order' => '1'
];
```

Probably more a feature request than a bug...

**Comment by distantnative** [comment]
I think this really is more an idea/feature request. Do you mind if we move it over to the idea repo for the moment?

**Comment by texnixe** [comment]
The custom property part probably is, but that languages don't work like a normal collection is a bit unexpected, since according to the docs it inherits the methods from the collection object. So I would expect the [`map()` method](https://getkirby.com/docs/reference/objects/languages/map) (and all the others not tested yet) to work.

**Comment by lukasbestle** [comment]
The `map()` method does indeed work, only is there no magic `__call()` method like for other models because the language model so far doesn't support any custom properties.

Which means that the following code works (only change: the value to dump is used without parens):

```php
$languages = $kirby->languages()->map(function($l) {
  $langOrder = ['fr' => 1, 'de' => 2, 'en' => 3];
  $l->order = $langOrder[$l->code()];
  return $l;
});

foreach($languages as $l) {
  dump($l->order);
}
```

I have opened an idea issue at https://github.com/getkirby/ideas/issues/363 about custom language properties.
