### ISSUE TITLE
Sorting problem in panel when more than 1 'pages' section in blueprint

### ISSUE THREAD

**Issue by tickHub** [getkirby/kirby#1502]
When there is more than one section of the type 'pages' in the blueprint, the sorting is wrong as it is setting the position of one of the sections, but re-numbering over all 'pages' sections inside that blueprint.

Example blueprint

    blocks:
      type: pages
      status: all
      image: false
      templates:
        - text
        - visual
        - number
        - quote
        - logos
        - products
        - faq
        - form

    subpages:
      label: Subpages
      type: pages
      status: all
      image: false

      templates:
        - campaign-page

**Comment by medienbaecker** [comment]
The subpages you display in two different `pages` sections are still in one folder — there's no differentiator just because you display different templates separately in the panel.

I guess what you need is at least one container folder, for example for your blocks. That way the sorting will be separate, as the subpages would be direct children and the blocks would be sorted inside `/blocks`.

There's no way to hide these container folders right now, but [the issue](https://github.com/getkirby/kirby/issues/1372) has been added to the 3.1 milestone.
