### ISSUE TITLE
Problem with multiple hooks (bug)

### ISSUE THREAD

**Issue by kgevaert** [getkirby/kirby#1554]
When setting the status of 2 dynamically made pages to listed at the same time, the page.changeStatus:after hook is only triggered once. It's only the hook for the first action that is executed.

```
$newcontact->changeStatus("listed"); // template invite (action 1)
$newinvoice->changeStatus("listed"); // template invoice (action 2)
```

```
'hooks' => [
  'page.changeStatus:after' => function ($newpage,$oldpage) {
      $template=$newpage->intendedTemplate() ;
      if($template == "invite"){
        // do something //this works
      }
      
     if($template == "invoice"){
       // do something // this is not executed
     }
     ....
```

link on the getkirby forum:
https://forum.getkirby.com/t/problem-with-multiple-hooks/13274
@distantnative

**Comment by bastianallgeier** [comment]
✅

**Comment by lukasbestle** [comment]
@distantnative The `serialize()` implementation in #1577 broke (at least) the `route:after` hook as there will be the route action callback somewhere in the `$arguments` and callbacks (closures) can not be serialized. Instead that hook now results in an exception.

If I remember correctly, the whole hook ID thing was only introduced because there could be situations where a hook triggered an action that would again trigger the same hook. So instead of using IDs for this, why not this:

- The `$app->trigger()` method keeps a counter of recursion levels (let's call it `static $recursionLevel`). Each time that method gets called, it adds 1 to the counter.
- It also keeps a list of hook callbacks that have already been called (`static $triggered`). It doesn't need to sort them by any kind of ID.
- Like in the current implementation, it only calls those hook callbacks that haven't yet been called. It adds the called callbacks to `$triggered`.
- After calling all hook callbacks but before returning the result, it decrements the recursion counter `$recursionLevel` again. If the counter is now 0, it knows that we have finished running on the "top-level". It can then throw away the list of hook callbacks in `$triggered`. This means that next time the `$app->trigger()` method is called from an entirely new action, all hooks can now be called again.

Maybe I'm missing something here though. What do you think?

**Comment by lukasbestle** [comment]
@distantnative The `serialize()` implementation in #1577 broke (at least) the `route:after` hook as there will be the route action callback somewhere in the `$arguments` and callbacks (closures) can not be serialized. Instead that hook now results in an exception.

If I remember correctly, the whole hook ID think was only introduced because there could be situations where a hook triggered an action that would again trigger the same hook. So instead of using IDs for this, why not this:

- The `$app->trigger()` method keeps a counter of recursion levels (let's call it `static $recursionLevel`). Each time it gets called, it adds 1 to the counter.
- It also keeps a list of hook callbacks that have already been called (`static . It doesn't need to sort them by any kind of ID.
- Each time the `$app->trigger()` method is called,
- After calling all hook callbacks but before returning the result, it decrements the recursion counter again. If the counter is now 0, it knows that we have finished running on the "top-level". It can then throw away the list of hook callbacks

Maybe I'm missing something here though. What do you think?

**Comment by distantnative** [comment]
@lukasbestle that could solve the previous `triggered` checks in a different way, but I don't think it fixes the issue we tried to fix with `serialise()`:
Keeping track of the hook name and which callback functions have been triggered fixes issues of endless loops, however it also stops the same hook from being called with different arguments consecutively (e.g. a different page object when trying to change status first of page A then page B).

**Comment by distantnative** [comment]
Then again, all current tests (including tests for endless hooks and different parameters) pass after trying to implement what you described (please have a look if I didn't misunderstand anything):

```php
    public function trigger(string $name, ...$arguments)
    {
        if ($functions = $this->extension('hooks', $name)) {
            static $level = 0;
            static $triggered = [];
            $level++;

            foreach ($functions as $index => $function) {
                if (in_array($function, $triggered[$name] ?? []) === true) {
                    continue;
                }

                // mark the hook as triggered, to avoid endless loops
                $triggered[$name][] = $function;

                // bind the App object to the hook
                $function->call($this, ...$arguments);
            }

            $level--;

            if ($level === 0) {
                $triggered = [];
            }
        }
    }
```

**Comment by distantnative** [comment]
Also all object-specific tests (e.g. pages) still pass.

**Comment by lukasbestle** [comment]
> Keeping track of the hook name and which callback functions have been triggered fixes issues of endless loops, however it also stops the same hook from being called with different arguments consecutively (e.g. a different page object when trying to change status first of page A then page B).

Only if the second call happens "inside" the first call. Because `$triggered` is cleared in the end, it will work with consecutive calls that are based on different actions.

I'm not 100 % sure about the implications though. There may well be use-cases that relied on triggering a different action on a different object inside the hook (e.g. if a page gets deleted, also delete another page). Those won't work. But I think it's really hard to handle those correctly.

One way could be to pass the ID manually from the piece of code that triggered the hook. Then we won't have to dynamically generate IDs from the arguments (which will always break in some cases as with `serialize()` and also won't have good performance).
But the question is if we can find suitable ID sources for all hook types.

Difficult...

> please have a look if I didn't misunderstand anything

Your implementation is exactly what I meant. LGTM! :)
(If we decide to do it like this in the end...)

**Comment by distantnative** [comment]
> I'm not 100 % sure about the implications though. There may well be use-cases that relied on triggering a different action on a different object inside the hook (e.g. if a page gets deleted, also delete another page). Those won't work. But I think it's really hard to handle those correctly.

You think they won't work at all in this implementation or it just would not work to prevent loops?

**Comment by lukasbestle** [comment]
The hook would not get triggered for the second action at all because the array has not yet been cleared.

The question is if there are really use-cases that rely on hooks being triggered multiple times. If there aren't, this would reduce complexity by a fair amount (as the solution proposed above would work). My feeling is that most use-cases should be possible with this implementation, but I'm not 100 % sure.

**Comment by bastianallgeier** [comment]
I'd suggest to go with @distantnative's and your approach and then see what will happen.

**Comment by bastianallgeier** [comment]
I added @distantnative's last version for the rc.
