### ISSUE TITLE
Add audio support to kirbytext

### ISSUE THREAD

**Issue by bennyschudel** [getkirby/kirby#157]
I've wrote a plugin but to me this should be in the kirbytext core like the images & files.

**Comment by bastianallgeier** [comment]
The bug is fixed in the meanwhile. Sorry that it took so long. 

@fanningert your plugin looks awesome!! Did you consider to submit it here: http://getkirby-plugins.com 

I think most people would want to work on the HTML for this, so something like Thomas' plugin is probably a better fit than to add it to the core.

**Comment by fanningert** [comment]
@bastianallgeier Thanks. Yes I submited all my plugins to the webpage for many weeks. But I don't see it on the page.

**Comment by JonasDoebertin** [comment]
Hi @fanningert,

somehow you submission didn't make it through. Did you use the linked form? Anyhow, I'll add it later today.

Would you mind pointing me to the another plugins you'd like to have added?

**Comment by fanningert** [comment]
@JonasDoebertin yes I am used the online form.
Here are my other plugins.
https://github.com/fanningert/kirbycms-extension-image
https://github.com/fanningert/kirbycms-extension-video
https://github.com/fanningert/kirbycms-extension-code
https://github.com/fanningert/kirbycms-extension-audio

**Comment by JonasDoebertin** [comment]
@fanningert Thanks for letting me know. I'll add them to the site within the next days!
