### ISSUE TITLE
Displayed user role does not update after change in users view

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/kirby#1595]
**Describe the bug**
When changing a user’s role from the users view in the panel, the list of all users only updates after reloading the view, when a role is changed.

**To Reproduce**
1. Go to `yoursite.test/panel/users`
2. Click on  the `…` symbol of a user and change his*her role and save.
3. The role is not updated in the list.

**Expected behavior**
The list should update

**Kirby Version**
3.1.0-rc.1

**Console output**
none

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser: Firefox 65.0.1

**Comment by distantnative** [comment]
I cannot reproduce it. Changes for me in the list right away after submitting the dialog. Including `:)` notification. Does this issue still persist with 3.1 (non-RC)? 

Or any special plugins, role blueprints?

**Comment by conallor** [comment]
I can confirm this bug. I had it with the starter kit with 3.0 and when I dropped 3.1 in. And it's still there now that I've got the develop branch up and running on my local.

I'm new to Kirby3 and never used Vue, so I'll see if I can narrow down where the problem is. Always a good way to learn!

**Comment by distantnative** [comment]
Just to be sure I understand it correctly:
This happens to you in the users view, so the table-style overview of all users, when changing the role via the dialog popup from the contextual dropdown menu?

**Comment by conallor** [comment]
Yes, actually the bug occurs when changing any of the users information from the drop down, except for delete. The stale data persists even if you refresh immediately a few times.  I've logged the incoming reads at the lowest level I could find for the site/accounts/-user-hash-/index.php in question:

https://gist.github.com/conallor/77579478e5ac1eac9c53ac8198567c8e

As you can see the delay is about 3s on my machine. Having looked into why, I've found that the bug is probably limited to those who have OPcache installed and enabled on their system (like me). The issue here is that the user info is not fetched from disk using [file_get_contents](https://github.com/getkirby/kirby/blob/74b593ff86f9a220343d08e3c631b128d09e76d6/src/Toolkit/F.php#L498) but directly interpreted using [require](https://github.com/getkirby/kirby/blob/74b593ff86f9a220343d08e3c631b128d09e76d6/src/Cms/UserActions.php#L243). Behind the scenes, this is stored in memory even across reloads meaning we have stale data until the cache is invalidated.

To fix this you can simply check to see if opcache is installed and force the invalidation of the cache for a specific file: http://php.net/manual/en/function.opcache-invalidate.php

You could do this before reading the file in UserActions->readCredentials(), but it probably makes more sense to do so directly after writing to the file UserActions->writeCredentials() as you would avoid redundant calls.

If you like I can make a pull request, though I'm not sure if this logic should go directly inline on UserActions->writeCredentials() or if its better to be extracted to somewhere like F::invalidateOpcache($file). What do you think?

**Comment by distantnative** [comment]
This might be a much bigger issue with opcache than just with user files. So extracted would be good.

I’d give it a neutral name though, not only related to opcache so it could extended potentially.

**Comment by conallor** [comment]
Yes, you're right. As far as I know OPcache is the only one available for php 7 at the moment, but of course this could change. invalidateCache is too generic as could refer to cache at any level, so I would probably go with F::invalidateOpcodeCache($file).

**Comment by bastianallgeier** [comment]
✅
