### ISSUE TITLE
Significant slowdown from 3.0 to 3.1 when sorting pages by URL in multilang site

### ISSUE THREAD

**Issue by omz13** [getkirby/kirby#1642]
As raised in omz13/kirby3-xmlsitemap#27, there has been a significant slow-down in the time taken for my plugin to generate a sitemap. A quick regression test seems to point to something changing between 3.0.3 and 3.1.

kirby 3.0.3 time = 211 👍
kirby 3.1.0 time = 1800 👎

The main loop of my plugin essentially iterates across the collection, and recurses into any children. Pseudo-code is

```
addPagesToSitemap( Pages $pages, string &$r, ?string $langcode = null )
{
   $sortedpages = $pages->sortBy( 'url', 'asc' );
   foreach ( $sortedpages as $p ) {
     // do something with $p
      if ( $p->children() !== null ) {
         addPagesToSitemap( $p->children(), $r, $langcode );
      }
   }
}
```

**Comment by lukasbestle** [comment]
Hm, I cannot reproduce this. I also [couldn't spot a change in the codebase from 3.0.3 to 3.1.0](https://github.com/getkirby/kirby/compare/3.0.3...3.1.0) that could explain it.

I created a test directory with 100 pages with 100 children each like so:

```bash
mkdir test
cd test
touch test.txt

for i in {1..100}; do
  mkdir $i
  touch $i/test.txt
  
  for j in {1..100};  do
    mkdir $i/$j
    touch $i/$j/test.txt
  done
done
```

Then I've run the following code inside the Kirby `home.php` template:

```php
function recursiveIterate(Kirby\Cms\Pages $pages) {
  $pages = $pages->sortBy('url', 'asc');

  foreach ($pages as $p) {
    if ($p->children() !== null) {
      recursiveIterate($p->children());
    }
  }
}

$start = microtime(true);
recursiveIterate(page('test')->children());
echo microtime(true) - $start;
```

The result is a rather consistent time of 2.6 to 2.8 seconds both with 3.0.3 and the latest version of the `develop` branch (which currently equals 3.1.2). Do you still get the issue with 3.1.2?

**Comment by lukasbestle** [comment]
PS: I have also tested 3.1.0 now for comparison. The result is basically the same (around 2.7 seconds +- 0.1 seconds).

I think the question is: Could this behavior come from something else entirely and not just from getting the page objects? Your plugins does quite a lot of stuff, so it's hard to track it down to a specific line. Could you maybe [profile your plugin](https://xdebug.org/docs/profiler) to find out which part is the cause? That would help a lot with further debugging.

**Comment by omz13** [comment]
I did a quick test last week, and, yes, its probably not the iterating across the objects that's the problem, but more likely accessing their data (template, date, etc). Unfortunately I am suffering with very bad conjunctivitis in both eyes, so until my eyesight is back to normal I am unable to do any debugging 😭 (I managed to get as far as getting xdebug installed and was about to work on the profiler when my eyes went south)

**Comment by lukasbestle** [comment]
Sorry to hear that, get well soon. :)

**Comment by omz13** [comment]
Thanks to eyedrops, I managed to do a bit of screen time today. I think I found the problem::

```
    $sortedpages = $pages->sortBy( 'url', 'asc' );
```

Kirby 3.0.3 time = 1.77 ms
Kirby 3.1.2 time = 39.5 ms.

So, its `sortBy` that has become exponentially slower between the branches.

**Comment by lukasbestle** [comment]
@omz13 has sent me Xdebug profile files which I was now able to analyze and compare. This was a great help, thanks for that! <3

I tracked it down to [this change](https://github.com/getkirby/kirby/commit/0b4b2c3a7347875e27857473879aca5eb17f9a3a) in Kirby 3.1.0. It was an improvement to the URL handling in multilang so that URLs are now by default returned in the current language. So the reason for this bug was a feature.

Because that feature introduced more logic and internal checks, a lot more stuff gets called internally. And because sorting by URL calls the `$app->url()` method a lot, that can really add up.

So to wrap up, the performance issue occurred exactly in the following situation:

- Sorting pages
- by URL
- in a multilang site
- in Kirby 3.1.0+.

Based on the excellent profile logs you sent me, I was able to determine that content files in multilang sites were read over and over and not cached in memory. This was by far the biggest bottleneck. I have fixed this in #1676. My testing setup with 100x100 pages took 42 seconds to sort before the change and now takes 11 seconds, which is even faster than with 3.0.3 (15 seconds). :tada:

@omz13 Maybe it makes sense to get rid of the sorting in your plugin, which with 3.1.0 uses around 60 % of the whole sitemap generation time alone (before the bug and probably now after the fix still around 30 %). If you really need sorting, you could sort the sitemap in the end instead of sorting the pages that will land in the sitemap. This will increase performance by quite a bit.

**Comment by omz13** [comment]
@lukasbestle Thanks for finding the root cause 🎉 ; glad the Xdebug profile files helped.

Yes, for the xmlsitemap plugin I can remove the sorting because it is not really necessary; I originally had this so the entries would be explicitly sorted to make debugging a bit easier.

**Comment by bastianallgeier** [comment]
✅

**Comment by bastianallgeier** [comment]
Great work guys!

**Comment by joernroeder** [comment]
thanks to all for looking into this!
