### ISSUE TITLE
Wrong date gets stored when in a different time zone

### ISSUE THREAD

**Issue by dgsiegel** [getkirby/kirby#1813]
**Describe the bug**
I have a date field without time set up in a blueprint. When I input a date, it correctly gets stored in both the panel as well as in the txt file. However when my client (based in the UK) enters a date, the day after gets stored in the txt file and therefore in the panel as well. If we change his browser/system timezone to Europe/Berlin, this issue disappears.

**To Reproduce**
1. Add a date field to a content type
2. Change your system/browser timezone to UK or USA
3. Enter a date
4. Find that the date was changed to the day after

**Expected behavior**
The correct date should be visible.

**Kirby Version**
3.1.4

**Desktop (please complete the following information):**
Happens on different browsers, systems and even mobile devices, if they are set to a different time zone.

**Additional context**
Seems to be a similar issue: https://forum.getkirby.com/t/date-field-shows-wrong-date-for-some-users/14167/11

**Comment by distantnative** [comment]
Tried to reproduce using https://chrome.google.com/webstore/detail/change-timezone-time-shif/nbofeaabhknfdcpoddmfckpokmncimpj

But it works properly for me. Tried saving at date with time set to 23:00 as well as to 01:00 using `America/Los_Angeles` as time gone. Works properly in my tests.

**Comment by dgsiegel** [comment]
Would you mind switching your system time to a different time zone? I couldn't reproduce it with an extension either. Might also be related with my client being located in the UK (UTC+0).

**Comment by dgsiegel** [comment]
See also: https://forum.getkirby.com/t/panel-kirby-adds-one-day-to-the-selected-date/15552

**Comment by afbora** [comment]
@distantnative I can reproduce this issue with that extension.

![timezon](https://user-images.githubusercontent.com/3393422/66259318-40487580-e7b8-11e9-8cef-2b403c6aa1ef.gif)

**Timezone**: America/Los_Angeles

**Current Date**: 2019-10-05 21:00 (txt file)
**Appear Date**: 2019-10-04 00:00 (panel)
**Selected Date**: 2019-10-10 00 (change)
**After Select Date**: 2019-10-07 13:00 (after change)
**Saved Date**: 2019-10-09 10:00 (txt file)

That's really weird 😩

**Comment by distantnative** [comment]
@afbora I can produce it as well but couldn't track down the bug completely.

**Comment by afbora** [comment]
@distantnative As much as I've seen in my tests, this is a issue with `dayjs` plugin. 

The solution that comes to mind is to create a new `timezone` option like `locale`. 
If developers wish to use the panel in different time zones, the `timezone` option is set when loading the application as follows.

````php
return [
    'debug' => true,
    'timezone' => 'America/New_York',
];
````


````php
public function setTimezone($timezone = null): void
{
    if ($timezone === true) {
        $timezone = ini_get('date.timezone');
    }
    
    if (empty($timezone) === false) {
        date_default_timezone_set($timezone);
    }
}
````

**Comment by distantnative** [comment]
@afbora i don’t think this will work as different Panel user alight be in different time zones.

**Comment by afbora** [comment]
@distantnative `date_default_timezone_set` in config, works for me.
Timezone option for saving always stable dates.
The date will be displayed according to its own time zone, but will be saved according to the setting defined when registering timezone option.

**Comment by alancwoo** [comment]
Also having this problem unfortunately, in Firefox, on Japan timezone. The content saves as UTC on the server then jumps to display a different time after save.

**Comment by distantnative** [comment]
@afbora From my tests, the problem is happening with the days library. So we should try to fix this and not offer an option on the PHP side. I still have hope...

**Comment by distantnative** [comment]
I think we are running into a small timezone issue with dayjs (actual difference in hours) that then gets multiplied cause we call days a number of times.

I set up a little demo:
https://codepen.io/distantnative/pen/PoovYBP

When I alter my timezone (with https://chrome.google.com/webstore/detail/change-timezone-time-shif/nbofeaabhknfdcpoddmfckpokmncimpj), I can clearly see the issue:
<img width="640" alt="Screen Shot 2019-11-23 at 22 01 00" src="https://user-images.githubusercontent.com/3788865/69485222-c12d0080-0e3c-11ea-9c22-983838ac2b04.png">

**Comment by afbora** [comment]
@distantnative Did you find a solution?

**Comment by distantnative** [comment]
No, so far not.

**Comment by distantnative** [comment]
I feel like it really should be solvable with https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#utc but I haven't figured it out so far.

**Comment by bastianallgeier** [comment]
Looks like we need to move it to the next milestone :/

**Comment by pedroborges** [comment]
This issue has been very annoying for quite some time. I'm working on an event calendar plugin and it will be almost impossible for it to work correctly without fixing this issue.

The cause for this bug is: let's say a date field in the content file contains `2019-12-09 10:00`. PHP assumes that the server timezone is UTC and sends `2019-12-09T10:00:00+00:00` to the browser. Because dayjs receives the date including a timezone, it tries to be smart by offsetting the date with my system's timezone. Because I'm in Brazil (GMT-03:00) I see time as 07:00 in the date field. In some cases, you even see a different day. If I set the time to 15:00, It is saved correctly. When I refresh the page it shows 12:00 because dayjs offsets the date once again.

If I set the server timezone to be the same as in my system, it works fine. The problem would be solved if panel users were always in the same timezone. But we can do better and not try to guess panel users' timezone.

The solution: send dates without timezone to the browser in the [`/config/fields/date.php`](https://github.com/getkirby/kirby/blob/21ebebda6bdde9aee62140f81f658f0852ea4e60/config/fields/date.php#L70) file:

```diff
- return date(DATE_W3C, $timestamp);
+ return date('Y-m-d H:i:s', $timestamp);
```

This changes makes the browser displays the exact same datetime as in the content file.

No change is required in the front-end because the date I see when hitting "save" is being stored correctly to the content file.

**Comment by pedroborges** [comment]
You can also test the browser side by manually removing the timezone from `date` in the `KDateField` component with Vue Dev Tools.

 With timezone:

<img width="1280" alt="with-timezone" src="https://user-images.githubusercontent.com/688309/70480090-9938d080-1abd-11ea-8c1d-5e21c98cdb4d.png">

Without timezone:

<img width="1280" alt="without-timezone" src="https://user-images.githubusercontent.com/688309/70480110-9fc74800-1abd-11ea-9c85-d3e1543caa85.png">

**Comment by nilshoerrmann** [comment]
We‘ve had this issue in another CMS and removing timezones from all dates (= considering all input and output UTC) also solved the issue reliably.

**Comment by distantnative** [comment]
@pedroborges Awesome input! I was tring so hard to fix it on the dayjs side, that I overlooked trying to pass a different date format from the backend.

**Comment by distantnative** [comment]
@pedroborges Actually, your suggestion doesn't solve the problem for me 😞

1. Change to ` return date('Y-m-d H:i:s', $timestamp);` in https://github.com/getkirby/kirby/blob/21ebebda6bdde9aee62140f81f658f0852ea4e60/config/fields/date.php#L70

2. Change timezone to e.g. Vancouver (via https://mybrowseraddon.com/change-timezone.html)
3. Still false result:
![Screen Recording 2019-12-10 at 18 57 02](https://user-images.githubusercontent.com/3788865/70555269-06606a80-1b7f-11ea-89c8-c4bda03ebb96.gif)

**Comment by nilshoerrmann** [comment]
I don‘t know dayjs well, but have you made sure that the JavaScript interprets all dates as UTC?

**Comment by distantnative** [comment]
@nilshoerrmann That's exactly the problem where I am biting on stone so far with dayjs

**Comment by pedroborges** [comment]
I think the problem is that you are changing the timezone with the window opened. This isn't normal behavior. I guess dayjs is assuming some timezone when creating date instances, but not offsetting them because the date no longer contains a timezone. The moment you change your browser timezone without refreshing the window, offsetting kicks in.

Try the following without this extension:

1. Keep the change to `return date('Y-m-d H:i:s', $timestamp);`
1. Open a page with a date. Ensure you see the same date and time.
1. Change page date/time and save. Ensure it saves what you see to file.

It works even after I change my system timezone and refresh the page.

See: https://jumpshare.com/v/Mkl1Wrf3b5fw4b04MX4j

**Comment by nilshoerrmann** [comment]
@distantnative: Doesn't this work: 
https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#utc

1. Get the date from the API without timezone.
2. Set the date using `dayjs.utc('2019-12-10 20:10:05', 'YYYY-MM-DD HH:mm:ss')`.
3. Get the date using `dayjs.utc().format('YYYY-MM-DD HH:mm:ss')`.

**Comment by emmitc90** [comment]
Hey All.... 

Had the same issue of dates saving properly then displaying in the panel and on frontend of site 1 day ahead..

@pedroborges  suggested I try to change line 70 of the kirby/config/fields/date.php file to: 
return date('Y-m-d H:i:s', $timestamp);

The above fixed my problem and all dates are displaying properly.

-emmit

**Comment by distantnative** [comment]
@nilshoerrmann nope, didn’t work in my tests

**Comment by nilshoerrmann** [comment]
@distantnative, okay, that is strange. Which part is failing? Setting or getting?

**Comment by nilshoerrmann** [comment]
Maybe, if all else fails, you can manually correct the date passed to the API by using the user's timezone offset, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset.

**Comment by distantnative** [comment]
Seems to be a problem with the Dayjs etc plugin – I'm checking with the developer whether its a bug or I am using it wrong.

**Comment by distantnative** [comment]
Turns out @pedroborges's fix is all that is needed. Everything else I struggled with is a bug introduced by the plugin @afbora and I used to test different timezones. If we alter the OS timezone actually, it works fine with Pedro's fix added. So much wasted time because of a stupid plugin :(

**Comment by distantnative** [comment]
✅
