### ISSUE TITLE
Sorting collections of pages by date

### ISSUE THREAD

**Issue by saschabregenhorn** [getkirby/kirby#1825]
Very uncommon case, but when you sort a collection of pages by date, but the pages have no date field, you get this sorting: 10, 11, 12, 1, 2, 3 …

You can of course work around that, but maybe this issue has an effect in other scenarios as well.

**Comment by distantnative** [comment]
What would you expect to happen if you sort the pages by the date field, but they do not have a date field?

**Comment by saschabregenhorn** [comment]
I would expect the sort by date to be ignored and get the sorting of the pages in the Panel (1, 2, 3 ... 10, 11, 12 ...).

**Comment by distantnative** [comment]
Just trying to explore what would work best here: Shouldn't there be rather an error message pointing out that you are trying to sort by something that doesn't exist instead of silently changing the behavior?

**Comment by saschabregenhorn** [comment]
Good question. I'd say in most cases, when you are trying to work with something that doesn't exist,  an error message would be the right behavior.

But in the case of sorting I'd say the (described) fallback would be preferable, since you still have results but „only“ displayed in a wrong way.

**Comment by lukasbestle** [comment]
@afbora and I have refactored the `$collection->sortBy()` method for Kirby 3.2.5 and it has shown once more that the PHP `array_multisort()` function (which handles all the sorting in the end) is quite stubborn – its behavior can't easily be changed without breaking other edge-cases.

From my experience it's always best to define the fields to sort by as explicitly as possible, otherwise there will be always be ambiguities and the sorting result will be unpredictable.

You can already sort by multiple fields by passing more fields to the `sortBy()` functions. The additional fields will be used as a fallback when the first field is identical (or does not exist like in your example, which for PHP just means "identically empty").

I'm therefore closing this as this is not something we can really solve in the core. Feel free to reopen if you disagree.
