### ISSUE TITLE
Add a way to register an installation without using the panel 

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#1831]
There's no way so far to register a Kirby installation without using the panel. This is not very helpful for users, who don't use the panel at all and even switch it off. We need a way to handle this either in licenses.getkirby.com or in the source code somewhere.

**Comment by lukasbestle** [comment]
Leaving an idea here:

licenses.getkirby.com could have a field for the domain name that would then trigger a download of the respective license file.

We already have methods in the core to manually register, but it‘s quite an effort to build a script that calls them manually. We won‘t be able to make that much simpler.

So better to integrate this into our license server so that it can also be used for internal sites on servers without internet access at the same time.

**Comment by bastianallgeier** [comment]
@lukasbestle that's a great idea and definitely much easier to solve!

**Comment by nilshoerrmann** [comment]
I know that some users don't like their install to "phone home". Kirby never does this expect for the registration process in the panel. It would be nice – presuming the described download feature on licenses.getkirby.com already existed – if the panel offered a "drop your license here" area to circumvent the direct communication with the license server during registration. This would really fit [Kirby's privacy manifesto](https://getkirby.com/docs/guide/kirby-and-privacy).

So the users would be able to opt-out of automatic registration and opt-in to private manual registration.

**Comment by lukasbestle** [comment]
That‘s the idea. The downloaded license file would already be ready for use, so no further communication with the license server is required.

**Comment by bastianallgeier** [comment]
You can now download licenses files directly from the license area. 

![ezgif-4-3fe283fff4f2](https://user-images.githubusercontent.com/24532/66836208-3ca7b200-ef61-11e9-8f52-682a88634457.gif)

Direct upload in the panel has to wait a bit more, but it's pretty easy to add it to the config folder already.
