### ISSUE TITLE
Throw exception for multiple default languages

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1849]
since i copy and pasted a language definition file and forgot to unset the default value i had two default languages in the language settings page. maybe did not cause any problems, but i was wondering what other parts of the kirby core or panel might do if there are two default languages. will it break? will only one be used? which one?

kirby 3.1.4

**Comment by distantnative** [comment]
As you described how it happened, it's hard to prevent. I can't say from the top of my head which language would be treated as default in this case.

In my opinion, we should have a check for that in the core (multiple defaults) and throw a fatal error, so that developers/users are aware of the situation and can change it manually.

**Comment by bastianallgeier** [comment]
✅
