### ISSUE TITLE
[Panel] Using num:  date in blueprint results in error if date format is set to strftime

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1882]
**Describe the bug**
If you set

```
num: date
```

for page sorting with the date handler set to strtime in the `config.php` file, the Panel throws an error:

> Return value of Kirby\Cms\Page::createNum() must be of the type int, string returned

This does only happen with the short form, when using the query language with the correct date format for `strftime`, all is well.

**To Reproduce**
1. Set date handler to `strfttime`
2. Go to a note page in the Starterkit 

**Expected behavior**
Don't know if this is a bug. Maybe the short form could also respect the date format. If not, we have to add a note in the docs.

**Kirby Version**
3.2

**Comment by lukaskleinschmidt** [comment]
I just ran into this issue. I tracked it down to this [commit](https://github.com/getkirby/kirby/commit/5c612853f00249723fffd38bd7e30b9bddb330d8#diff-f394d91de05f65144be42abf6dde3b03). Because the `toDate` method is unaware of the used date handler the method can not format the date correctly and will just return the anticipated format (e.g. `Ymd` or `YmdHi`).

For anyone in need of a quick fix you can add following plugin. It's not ideal but at least you can get it working again this way.
```php
<?php

// plugins/datefix/index.php

Kirby::plugin('datefix/datefix', [
    'fieldMethods' => [
        'toDate' => function ($field, string $format = null, string $fallback = null) {
            if (empty($field->value) === true && $fallback === null) {
                return null;
            }

            $time = empty($field->value) === true ? strtotime($fallback) : $field->toTimestamp();

            if ($format === null) {
                return $time;
            }

            if (option('date.handler') === 'strftime') {
                switch ($format) {
                    case 'Ymd':
                        $format = '%Y%m%d';
                        break;

                    case 'YmdHi':
                        $format = '%Y%m%d%H%M';
                        break;
                }
            }

            return option('date.handler', 'date')($format, $time);
        },
    ]
]);
```

**Comment by bastianallgeier** [comment]
✅
