### ISSUE TITLE
[Panel] Users Field Should Save Persistent ID, Not Email Address

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1885]
**Describe the bug**
We just ran into an unexpected issue today, if you change the email address of a user, pages that had a Users field are no longer linked to the affected user.

I genuinely thought the Users field would save a list of persistent User IDs (i.e. the folder name that contains an individual user's files). If it had done this, renaming an email address wouldn't break existing pages (it breaks now because `$field->toUsers()` finds no matching email address.

**What's Actually Saved in a Content File**
```yaml
Authors: 

- foo@example.com
```

**What I Would Expect to be Saved**
```yaml
Authors: 

- By4XbnMB
```

**To Reproduce**
1. Have a user with an email `foo@example.com` ("Example User")
2. Go to a page with a Users field, select "Example User"
3. Change the email address for "Example User" to `bar@example.com`
4. Attempt to do `$field->toUsers()` on the original page

**Expected behavior**
The user should still be accessible.

**Kirby Version**
`3.1.x` and `3.2.0`

**Comment by texnixe** [comment]
It might make sense to make what is stored optional, like in a select field

```
query:
  fetch: kirby.users.filterBy("role", "editor")
  text: '{{kirby.user.email}}'
  value: '{{kirby.user.id}}'
```

Not really a bug, more a feature request.

**Comment by GiantCrocodile** [comment]
I'm surprised that this really happens 😮. This is very far away from expected behavior and can be a real mess for productive sites. I think this should be changed very soon, as @neildaniels suggests.

**Comment by texnixe** [comment]
>  This is very far away from expected behavior 

The same happens if you delete a user and do not take care of removing the reference or outputting something else instead. The same happens for page or file references as well if you remove a page or if you rename a page slug (unless you use  a manual or automatically generated permanent reference, for example using the AutoID plugin by @bnomei).

The main point here is the missing feature to store anything else but the email.

As long as this feature doesn't exist, you can use a hook that takes care of updating all references to a user email with the new one.

**Comment by bastianallgeier** [comment]
We always try to keep the result in text files as human readable as possible in the first place. Kirby's file system should ideally stay editable without the panel. That's the reason why emails are stored instead of the ID. I agree that we need the additional feature to change that behaviour though.

**Comment by bnomei** [comment]
@texnixe the autoid plugin [does not support generating values at the user content file](https://github.com/bnomei/kirby3-autoid/issues/23) yet. but if anyone has more sparetime than me right now and does a PR with a solution i would welcome this feature.

**Comment by texnixe** [comment]
@bnomei Yes, I know, I just wanted to point it out as an example. However, we need the option to store values other than the email in the users field first before we can actually make use of an extended AutoId plugin. But after what @bastianallgeier wrote above I'm pretty confident we'll get this feature soon.

**Comment by afbora** [comment]
Can we also add this feature (Array Query Options) for `pages` and `files` field? 

Forum discussion: https://forum.getkirby.com/t/invalid-value-for-query-on-fetching-pages-field/14925

**Comment by bastianallgeier** [comment]
I considered this some more and while the options are still a good idea, we should think about ways to avoid future issues in the first place. 

When we keep storing the email address as default, the issue persists. I really changed my mind on this entire issue. The panel should help avoid such problems as good as it can. While you can still keep on adding email addresses manually in text files, the panel shouldn't be doing this. I created a PR which will now store the ID as default. 3.3.0 is a good point to introduce this and it‘s luckily 100% backward compatible.

**Comment by afbora** [comment]
✅
