### ISSUE TITLE
Show error message in tooltip on invalid login

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#1906]
When you try to log in with an existing user and an invalid password, an proper exception is thrown in the console but there is no error message shown beside an animation of the login box.

```
code: 400
details: Array []
exception: "Kirby\\Exception\\InvalidArgumentException"
file: ""
key: "error.user.password.notSame"
line: 876
message: "Die Passwörter stimmen nicht überein"
route: "auth/login"
status: "error"
```

The user should be notified properly on the frontend.

**Comment by GiantCrocodile** [comment]
Same with invalid username on log in: no error shown on frontend.

**Comment by lukasbestle** [comment]
The detailed error message is only passed to the browser if the `debug` mode is active. So it's not a feature that is available by default and that we could use in the UI (because generally the `debug` mode should be disabled anyway). The reason why we don't have the detailed error message by default is to prevent information leakage that could be used by attackers.

Regarding a general error message: I think the animation is pretty clear. Do you have an idea what such an additional error message could look like?

**Comment by GiantCrocodile** [comment]
> Regarding a general error message: I think the animation is pretty clear. Do you have an idea what such an additional error message could look like?

We have to provide any kind of information (user or password wrong) for usability to visually impaired people or their softwares.

**Comment by texnixe** [comment]
I agree there should be some message, like "The combination of username and password is not correct" or something along those lines without giving away what exactly is not ok. Or like in Kirby 2 "Invalid username or password"

**Comment by lukasbestle** [comment]
What we could probably do is to show a red tooltip above the login fields with the error message. It could be the one that actually gets passed from the backend (i.e. a detailed one if debug mode is enabled).

**Comment by GiantCrocodile** [comment]
Is the missing discussion label still valid up2date here?

**Comment by bastianallgeier** [comment]
✅
