### ISSUE TITLE
[Panel] A non-admin user cannot change the role of another user of the same or different role

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1919]
**Describe the bug**
If I create for example an Editor user (with no permission settings set or with explicit settings to allow changing roles), I get an error message when trying to change the role of another user of the same or a different (non-admin) role. But the option is nevertheless available via the context menu.

> You are not allowed to change the role for the user "test@user.com"
```
title: Editor

options:
  changeRole:
    editor: true
    manager: true
permissions:
  users:
    changeRole: true
```

**To Reproduce**
1. Create an Editor blueprint like the above or empty
2. Create other users with the same or a different non-admin role
3. Try to change the role of these users via the context menu or in the user view. The change role dialog pops up (even with the option to change to the admin role which should not be the case, but that is another issue).
4. See error message

**Expected behavior**
A non-admin user role should still be able to change other users roles (apart from creating admins) if it is allowed via the role blueprint (assuming if there are no settings that everything is allowed).

**Screenshots**

**Kirby Version**
3.2.2

**Additional context**
I think the user permissions are a bit messed up in general atm.

https://github.com/getkirby/kirby/issues/1917

**Comment by bastianallgeier** [comment]
✅

**Comment by PaulRaschke** [comment]
I have a project running on Kirby 3.4.4 and I'm still facing this issue.
The bug seems to emerge from [`UserPermissions->canChangeRole()`](https://github.com/getkirby/kirby/blob/6112f1cb8ebf9c36e8a9f97ae08acc910ddbc792/src/Cms/UserPermissions.php#L37), where the number of available user roles is checked with [`User->roles()`](https://github.com/getkirby/kirby/blob/6112f1cb8ebf9c36e8a9f97ae08acc910ddbc792/src/Cms/User.php#L685), which always returns only the role of the specified user, unless the logged in user is an admin.
