### ISSUE TITLE
Language detection only works if default language has language code in URL

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1924]
**Describe the bug**
When setting `'languages.detect' => true` in the config, the user is only redirected to the detected browser language if the `url` parameter in the default language's config file is set to the default `null` (or language code) setting, not if the setting is `'url' => '/'`

**To Reproduce**
1. Define two languages (via the Panel or manually), set `'url' => '/'` for the default language
2. Set `'languages.detect' => true` in the config
3. Set your preferred browser language to the non-default language
4. See how you are **not** redirected to the detected language

**Expected behavior**
In an ideal world, redirection to the detected language would also work if the default language omits the language code.

**Screenshots**

**Kirby Version**
3.2.2 (and most probably older versions as well)

**Comment by bnomei** [comment]
all my websites omit the lang code for default. glad you found that bug @texnixe.

**Comment by afbora** [comment]
I don't think that's exactly a bug. I think that's how it works. 
Because if the default language in `/` address, the default language home page can never be displayed for users who detected language.

For example:

    example.com (Default as English with `/`)
    example.com/tr (Turkish language with `/tr` or `null`)

I entered the website `example.com` and redirected to `/tr` homepage, because of my browser language is `TR`. So far, no problem.

What if I want to see the English homepage (so default language of the website)? This will be impossible.

To fix this, we need to use session or cookies. Do you think this is necessary?

**Comment by lukasbestle** [comment]
If I remember correctly, we used a query param for this in v2. The param would get appended to the URL of the default language's homepage when printed for links etc. If the homepage was visited with the query param set, Kirby would set a cookie to manually switch the language.

I agree with @afbora though that this is all a bit overkill and too complex (it really was complex and caused a lot of other bugs). Maybe we should indeed close this as "won't fix".

**Comment by moritzebeling** [comment]
The language must only be detected (and the visitor redirected) when there was no prior selection by the visitor or the incoming URL he/she followed.
During on-site-surfing in all non-default languages, the choice is remembered with the language code included in all internal links.
The problem is: how do you know, that a visitor actually wants to stay in the default language?
- Also the default language could additionally have the lang code within the URL, indicating that a user has actively opted for the default language.
- There could be a query param, but that is not really beautiful and easily can get lost
- There could be a cookie remembering the language a visitor actively chose last. May be the cookie lifetime could be set in the config.

A cookie-solution would also mean, that all Kirby devs and users would have to know and inform their visitors in order to be GDPR compliant.

**Comment by lukasbestle** [comment]
As I wrote [above](https://github.com/getkirby/kirby/issues/1924#issuecomment-527593416), that's exactly how the solution in v2 worked. :)

**Comment by afbora** [comment]
I think we can mark this issue as `wontfix` and close 🤔

**Comment by lukasbestle** [comment]
I agree. What do you think @bastianallgeier?

**Comment by judbd** [comment]
It seems that's my problem described here a long time ago : https://forum.getkirby.com/t/language-detect-doesnt-work/14127/3
 How can I work around this? I have to set /fr on the default language? and a 301 redirect from  `/fr/*` to `/*` ?

**Comment by afbora** [comment]
@judbd Yes, default language url should be not `/` as root to work with `languageDetect` feature. You can set `null` or `/fr` for default language. If you currently use with `/` and want to redirect old links to news for SEO/Google Indexes, yes you need to redirect from `/*` to `/fr/*` with 301.

**Comment by judbd** [comment]
Thank you, but if language detect don't work with `/` so what's the point to autodetect? And will the `/` root will work if I have set `/fr` for the default language? This feature is not very clear.

**Comment by afbora** [comment]
@judbd Language detection works only for users who access the site's home directory as `/`.

**For ex:**

FR url option is `/fr` as default lang
example.com/fr

DE url option is `/de`
example.com/de

If a user whose browser language is `DE`, enters  `/` the home directory of the site as  `example.com`, will redirected to the address `/de` as `example.com/de`.

**Comment by judbd** [comment]
But NOT if the default language URL is set to `/` (aka `/fr` doesn't exists) right?
If I change my default language URL to `/fr`, does the website will be accessible with `/`?

**Comment by afbora** [comment]
If you set the default language's url setting to `/fr` and users enter `/` address, Kirby will do following two behaviors:

1. If the user's language is available in Kirby, they are directed to that language. (de> example.com/de)
2. If the user's language is not available in Kirby, they are redirected to the default language (example.com/fr)

So the address `/` is used only as a router to the relevant language.

**Comment by lukasbestle** [comment]
We have discussed this in the team again and come to the conclusion that this can't be properly fixed without making the implementation unreliable like the one in Kirby 2.

**Comment by christophlocher** [comment]
Please consider adding a note about this known limitation to the Kirby docs section about [Language-specific URLs](https://getkirby.com/docs/guide/languages/introduction#language-specific-urls). It says “If you want to keep the root URL for the default language, you can set the URL manually using the url option”. – I’d say the fact that this will disable Automatic language detection is quite a big caveat.

Thanks!

**Comment by lukasbestle** [comment]
@ChristophLabacher Thanks for pointing that out, I have added a note to the docs.
