### ISSUE TITLE
Files Section "Replace" Menu Item Broken in Safari

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1951]
**Describe the bug**
Within a Files section, if you use the context menu on a file, you cannot replace a file in Safari. Works fine in Chrome. You click it and nothing happens.

**Screenshots**
![2019-07-26 at 3 33 PM](https://user-images.githubusercontent.com/417182/61984941-9086a880-afbb-11e9-836e-557f6f4e41fc.jpeg)

**Kirby Version**
`3.2.2`

**Console output**
None

**Desktop (please complete the following information):**
 - OS: macOS 10.15 Beta (19A512f)
 - Browser: Safari 13.0 (15608.1.34.1.1)

**Additional context**

**Comment by luxlogica** [comment]
Does not seem to work in Firefox, either.

**Comment by bastianallgeier** [comment]
Ughhhh. This is the kind of bug that takes much more time than expected :( Firefox and Safari block the input from being clicked here and I don't really understand why. It works as expected in all other places.

**Comment by neildaniels** [comment]
I did some testing on prior versions. This functionality worked fine (at least in Safari) in `3.0.0`, `3.1.0`, and `3.1.4`.

`3.2.0` was the first version where this regression occurred, so the breaking change is probably in one of those commits.

**Comment by neildaniels** [comment]
Also seems like the "Open" menu item is broken.

**Comment by bastianallgeier** [comment]
@neildaniels I finally found the reason for this. We had an additional API call since 3.2.0, which was called before each action was executed. Safari and Firefox have built-in security features for opening windows and file inputs and they get blocked when there are too many nested JS functions involved to execute the event. 

My PR is still in the review process, but we will definitely have the fix in 3.3.0

**Comment by bastianallgeier** [comment]
✅
