### ISSUE TITLE
[Cms] Custom page models do not work if languages are enabled

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/kirby#1972]
**Describe the bug**
If languages are enabled, custom page models do not take effect.

**To Reproduce**

1. Start with a clean copy of the `plainkit` at 3.2.2
2. Create a custom page model `site/models/home.php`.
3. Add a new language in `site/languages/en.php`.
4. Create a new template for the home page in `site/templates/home.php` with the following contents:
   ```php
   <?php echo get_class(page()) ?>
   ```
5. Open the homepage in your browser
6. The name of the default page class is displayed on the homepage: `Kirby\Cms\Page`.

I’ve created a [repository to reproduce the bug](https://github.com/tillprochaska/plainkit/tree/custom-page-models-multilang/site).

**Expected behavior**
The name of the custom page model should be displayed: `HomePage`.

**Kirby Version**
3.2.2

**Additional context**
It seems this bug has been reported and fixed before during beta (#949).

**Comment by afbora** [comment]
I checked your repository and tested in my side.
This is because your [homepage content file](https://github.com/tillprochaska/plainkit/blob/custom-page-models-multilang/content/home/home.txt) is not setup properly.

If languages are enabled, your `home.txt` file should be named as `home.en.txt`
You will see properly works when you rename the home content file with language code.

**Comment by tillprochaska** [comment]
Thanks @afbora, renaming the content files solved the problem, thanks!
