### ISSUE TITLE
Strange regex in Url::isAbsolute

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#2002]
https://twitter.com/mthie/status/1161223681877643265

**Comment by bastianallgeier** [comment]
@lukasbestle could you have another look at this? I just checked our regex and it actually does what it is supposed to do. One could argue that a url might still be relative, if it has a relative path later. I.e. https://something.com/a/b/../c but I wonder if we should check for that? You could also argue that the check for scheme-less URLs is a bit unsafe. There could be `//super/nice/awesome` which wouldn't be a correct absolute URL. This is something we might really need to check. What do you think?

**Comment by lukasbestle** [comment]
To be honest I don't get what the originally reported issue was. I don't see any problem with the RegEx. The method checks if the passed URL is protocol-absolute. And since `mailto:` and `tel:` are URL protocols as well, that's exactly what it should check. The same for the URLs with relative paths inside them – if they have a protocol and hostname, they are absolutely defined.

The only thing that could indeed be an issue is the check for scheme-less URLs. They are not 100 % absolute, but it depends on the use-case whether this is an issue or not.

> You could also argue that the check for scheme-less URLs is a bit unsafe.

What do you mean with "unsafe"? The URL `//super/nice/awesome` is actually valid if there is a hostname called `super` in the local network. :)

**Comment by bastianallgeier** [comment]
Yes, I agree. After checking it again, I really don't understand the problem. I just wanted to make sure I'm not just clueless :)

With "unsafe" I mean that it could be just a typo in the path with two slashes and it could be misinterpreted as a schema-less protocol. But I'm not sure if we should even worry about this edge-case.

**Comment by lukasbestle** [comment]
No, I think we shouldn't. There are use-cases where schema-less URLs are intended, so I think we should support them here.

**Comment by bastianallgeier** [comment]
Perfect!
