### ISSUE TITLE
Json::encode escapes unicode entities

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2111]
**To Reproduce**
1. Put this in a template:
```php
echo \Kirby\Data\Json::encode('здравей');
```
2. Echoed string is:
```
\u0437\u0434\u0440\u0430\u0432\u0435\u0439
```

**Expected behavior**
The encoded string should be `здравей`

**Kirby Version**
3.2.3

**Additional context**
This can be fixed by simply adding [a flag](https://www.php.net/manual/en/json.constants.php) in `Json::encode()` (tested):
```php
json_encode($data, JSON_UNESCAPED_UNICODE);
```

**Comment by afbora** [comment]
Instead of direct usage, we can enchance `encode()` method passing optional `options` param.

````php
public static function encode($data, int $options = 0): string
{
    return json_encode($data, $options);
}
````

**Usage**:

````php
echo \Kirby\Data\Json::encode('здравей', JSON_UNESCAPED_UNICODE);
````

**Comment by bastianallgeier** [comment]
I prefer @afbora's way. As I understand it, the version with encoded unicode characters is more stable. That's why it's the PHP default.

**Comment by bastianallgeier** [comment]
✅

**Comment by lukasbestle** [comment]
@bastianallgeier We can't really do it that way as that changes the method signature compared to the other `Data` handler classes. I see three problems with it:

- It could be confusing because you would expect that all handlers work the same way (which they currently do).
- We won't be able to add params to the other handlers that aren't compatible with this new `$options` param, otherwise the different handlers won't be compatible anymore (which they should be as the whole `Data` package should be a transparent translation layer between memory data and serialization forms).
- You can't pass the `$options` param when calling `Data::write($myFile . '.json', $data)` directly, so it's of limited use.

I haven't found any background information on the PHP JSON option constants, but I'd imagine they are there for backwards-compatibility. Some ancient parsers don't play well with Unicode and also with slashes, which is why the `JSON_UNESCAPED_SLASHES` and `JSON_UNESCAPED_UNICODE` constants are probably not enabled by default. But I can't imagine that there are actually still parsers out there that can't handle those chars. So we should actually be pretty safe to always use those two options. Or have you found any more specific information @bastianallgeier?

**Comment by bastianallgeier** [comment]
@lukasbestle you are right. I added the two options as default. I agree that they should be fine as general defaults. By removing the param again, the code is also a bit simpler, which is good.
