### ISSUE TITLE
Default page model?

### ISSUE THREAD

**Issue by fvsch** [getkirby/kirby#212]
As a follow-up to #143, is it possible to define a page model that applies to all pages, whatever the template used?

If I want to make a utility method available on all pages, can I do that with a model or should I stick with a plugin that exposes some functions?

For instance I have a function that returns the page's main content as HTML, looking for a `text` field first (and converting it from Markdown to HTML), or for a `html` field next (as-is). I don't want to duplicate that logic in each template *or* in each model, so right now it's in a plugin. Would you say a plugin is the recommended way?

**Comment by lukasbestle** [comment]
Implementing automatic inheriting over multiple "layers" is not possible in PHP because of the way inheriting works (you would still have to change the `extends` attribute in the class definition).

You can create your "base class" with the shared methods, put it in a plugin and then let your specific models extend that class instead of the default `Page` class.

**Comment by distantnative** [comment]
Custom page methods have been added to the develop branch and will be included in the next release. They would allow you to create custom methods for all $page objects - so kind of a default page model:

```php
page::$methods['linktag'] = function($page) {
  return '<a href="' . $page->url() . '">' . $page->title()->html() . '</a>';
};
```

I think, this addition together with @lukasbestle's suggestion should be sufficient to solve your issue.

**Comment by fvsch** [comment]
Oooh that's great.
