### ISSUE TITLE
Structure field with translate false and existing content

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2163]
**Describe the bug**  
Setting a structure field to `translate: false` doesn't have an effect if the translation already contains content for that field.

**To Reproduce**  
1. Set up a structure field and add content for all languages.
2. Set the field to `translate: false` _afterwards_.
3. Visit the frontend.

**Expected behavior**  
Existing translated content should be ignored.

**Kirby Version**  
3.2.5

**Additional context**  
This might be be controversy because there _actually is content_ in the translated files. But I'd argue that this content is breaking the rules. I've added a new item to a structure field and couldn't figure out why my English translation didn't update while the blueprint correctly stated the field was untranslatable.

**Comment by moritzebeling** [comment]
As far as I remember, this accounts to all field types: when you first enter a value and later set that field as untranslatable, the value is still stored in the content file. I don’t know how this can be solved in an elegant none-confusing way... But right now, it leads to the **situation, where a field has an undesired value but cannot be edited by any panel user**, since it’s untranslatable.

So what would be the desired procedure after setting a field as untranslatable, that may be filled already in some places? There is no such moment, where Kirby realises, that a blueprint has changed. So **maybe it should be solved at the moment, a page/file is next being updated?**
Each time you update a page, Kirby would have to **revalidate if the content matches the blueprint rules.** I would think, that this is a not too bad solution and maybe a good practice anyway.
But: it can lead to data loss simply by changing the blueprint (intended in our case, but can be accidentally and have dramatic consequences).
You would also have to update every page in the panel in order to clean up.

In the meantime you could clean up programmatically by looping through all your content like this recipe suggests: https://getkirby.com/docs/cookbook/extensions/content-file-cleanup.

**Comment by distantnative** [comment]
What @moritzebeling said. Just adding that it would be a huge performance issue to check the blueprint all the time when loading the content values (e.g. when loading frontend). So as @moritzebeling said, we could only do that when updating values again.

**Comment by moritzebeling** [comment]
Seems like this issue is a more specific case of #1859. Once that is solved, this one is too, I guess.

**Comment by nilshoerrmann** [comment]
I agree that this will be solved by #1859.
