### ISSUE TITLE
[Panel] New Icons

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2209]
https://getkirby.com/docs/reference/panel/icons

We can use emoji but it's a good idea to add some icons that are used very often.

- home [🏠]
- folder [📁]

You can add new icons under this issue/idea.

**Comment by bastianallgeier** [comment]
The following icons will land in 3.3.0

- bell
- book
- bookmark
- box
- bug
- car
- cart
- chart
- chat
- credit-card
- folder
- heart
- home
- layers
- linkedin
- map
- question
- star
- strikethrough
- underline
- vimeo
- whatsapp
- wheelchair
- youtube

![Screenshot 2019-10-15 at 09 56 19](https://user-images.githubusercontent.com/24532/66811991-5251b300-ef32-11e9-8b76-9defa6d2031e.png)

If you need more you can use the new icon plugin feature since 3.2.5
