### ISSUE TITLE
Setting asset `urls` in index.php doesn't have any effect on asset links

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2229]
**Describe the bug**  
In a multisite setup as described in this [recipe](https://getkirby.com/docs/cookbook/setup/multisite), setting the assets urls only affects @auto CSS links, not standard links, resulting in these two different URLs patterns:

```
<link href="http://my-site.test/assets/css/index.css" rel="stylesheet">
<link href="http://my-site.test/my-site.test/assets/css/templates/home.css" rel="stylesheet">
```

**To Reproduce**  
Setup a multi-site

**Expected behavior**  
The URLs generated with the CSS helper should be generated correctly for both standard and @auto asset links.

**Kirby Version**  
3.2.5

**Console output**  
404 not found for the first link

**Desktop (please complete the following information):**  
 - OS: Mac OS
 - Browser: Firefox/Safari

**Comment by afbora** [comment]
In fact, the problem here is that the behavior of the `css()` and `js()` methods is different. 
When using `@auto`, it looks at the `/assets` folder, otherwise it looks at the base directory. 
I think the `css()` and `js()` methods should always respond according to the `assets` or `base` setting of `urls`.

I did a few tests and I think we can solve it by writing a new method like `toAsset()` to use in `css()` and `js()` methods 🤔 

https://github.com/getkirby/kirby/blob/develop/src/Cms/Url.php#L43-L52

````php
public static function toAsset(string $path): string
{
    $kirby = App::instance();
    $url   = $kirby->url('assets') . '/' . $path;

    return $url;
}

public static function toTemplateAsset(string $assetPath, string $extension)
{
    $kirby = App::instance();
    $page  = $kirby->site()->page();
    $path  = $assetPath . '/' . $page->template() . '.' . $extension;
    $file  = $kirby->root('assets') . '/' . $path;
    $url   = static::toAsset($path);

    return file_exists($file) === true ? $url : null;
}

````

https://github.com/getkirby/kirby/blob/develop/src/Cms/Url.php#L43-L52
````php
if ($url === '@auto') {
    if (!$url = Url::toTemplateAsset('css/templates', 'css')) {
        return null;
    }
} else {
    $url  = Url::toAsset($url);
}
````

Likewise, the `js()` method should be modified.

**Comment by distantnative** [comment]
I think `toAsset` needs to test if the file exists as `toTemplateAsset` does.

**Comment by lukasbestle** [comment]
The only place we currently use the `assets` root in is the `toTemplateAsset()` method. That one of course needs it, otherwise the automatic asset URLs won't work as it wouldn't be possible to configure the URLs and roots for those.

I'm not sure if the `css()` and `js()` methods should use the `assets` root though. As Kirby traditionally doesn't care where the dev stores which assets, it should still be possible to access assets outside of the main `assets` directory. But then we'd need another param to the `css()` and `js()` helpers (and potentially others) that would override the "automatic" behavior.

Also this behavior would break backwards-compatibility as all calls to `css()` and `js()` currently include the `assets/` prefix already. That one would get added to the final URL, so the name of the `assets` dir would be included twice like `/assets/assets/css/index.css`.

To be honest, I feel like this is a "won't fix". In such custom setups, the asset URL should rather be manually included with `css($kirby->urls()->assets() . '/css/index.css')`.

The only thing we could do is to add a new config option that would then auto-prefix all asset URLS with the `assets` URL. As I explained above, this option couldn't be enabled by default though. So I feel like this is too complex to be in the core.

**Comment by yandodov** [comment]
@lukasbestle I think that what I proposed in #496 might be a good solution?

1. Rename the `Asset` class to `Resource`
1. Rename the `asset()` helper to `resource()`
1. Leave `asset()` as an alias for `resource()` and mark it as deprecated

That clears out the confusion I talked about in #496.

Some time later, you could bring back `asset()` and make it work the same way as `resource()` but relative to the `assets` root. That way, you could do:

```
css(asset('style.css'))
```

I think that would make the `asset` root more useful as well.

**Comment by lukasbestle** [comment]
@hdodov There's no need to duplicate your idea in the separate issue and here. Linking between the issues with a simple "Also see #..." is enough. :)

I like your idea. It doesn't solve this particular issue, but is definitely related and useful.

**Comment by distantnative** [comment]
I agree with @lukasbestle - I don't think there is a good way to change this without breaking many setups. And the easiest way to not break setups is the manual way. I don't think another config option makes sense. So rather a topic to address beyond Kirby 3.

@hdodov if you are still keen on renaming the class and helper, please open an idea suggestion over at feedback.getkirby.com
