### ISSUE TITLE
[Panel] Scheduled pages

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#224]
I think it would be a nice core feature to be able to set a page publish scheduled date/time.

Not all pages will need this feature. Therefor I think it would be perfect as a field, an extended datetime field that looks like a datetime field, but will also only show the page on the site (and in page collections) if the datetime is prior to the datetime set in the field.

Maybe for 3.5 or so?

**Comment by distantnative** [comment]
Somehow the idea for it as a feature doesn’t sit right with me. I totally get the use, but I’m thinking if we can’t accomplish it otherwise: have a `scheduled` field, sort pages by that field and then have a hook/site controller or so which checks if a page has a scheduled field in the past and publishes the page then. I think even performance wise this shouldn’t be too bad, since it only has to run through unpublished pages which in this scenario are most likely to be a minority.

**Comment by wottpal** [comment]
Sounds super useful to me but not like a core feature more like a plugin.

**Comment by jenstornell** [comment]
If it's that very simple and not at all hackish as a plugin, I could accept that as well.

**I may have changed my mind. A plugin may not help much, because of below...**
 \\/

**Comment by jenstornell** [comment]
@distantnative By the way, a hook would not work very well. Then a user action is needed after the scheduled page. Maybe the user is on vacation.

**I have done this plugin before:**
https://github.com/jenstornell/kirby-scheduled-pages

**The problem with it is the very hackish solution required:**
https://github.com/jenstornell/kirby-scheduled-pages/blob/master/docs/CONTROLLER.md

What could solve this is the idea issue of a site controller. Else we need the code in every controller that uses scheduled pages.

We would also need to be aware of scheduled pages in the new collection feature to prevent page listings to show the page on the site.

I'm not sure we can automate this with a plugin in a good way. The user would probably still need to add things to his/her site controller as well as collection in order for it to work.

It's not just a "set it and forget it" thing.

**Comment by distantnative** [comment]
To be fair, I think you really should be aware of what you are doing with such a functionality and where. And not try to forget it.

But when I talked about hooks, I was thinking of additional ones e.g. `page.load:before`.

I don’t like this as a fixed feature because there could be a lot of other conditions to automatically publish a page than just a datetime, e.g. an external API result. Or maybe you rather want to republish at a certain date. That is why I’m looking for more general way to approach this.

Such a page hook could work.

**Comment by jenstornell** [comment]
@distantnative. Yes, a `page.load:before` would be much more clear than a controller, I think. Then the controllers can be used on what they do best, send values to the template and snippets.

Then we would have a hook that is not bound to the panel, which is a step I like. Then `page.load:before` would be loaded no matter if the panel exists or not?

Maybe add a separate issue about that hook. It would be very useful. It would then be a bit similar to https://github.com/jenstornell/kirby-starthook#example-2 (example 2)

**Comment by jenstornell** [comment]
>I don’t like this as a fixed feature because there could be a lot of other conditions to automatically publish a page than just a datetime, e.g. an external API result. Or maybe you rather want to republish at a certain date. That is why I’m looking for more general way to approach this.

I agree now with @distantnative that this field can be very complex in the end.

I took the most simple approach to just schedule the page until a specific date/time, with a bit of help from @wottpal.

https://github.com/jenstornell/kirby-scheduled-pages/tree/kirby-3

![schedule-icons2](https://user-images.githubusercontent.com/927011/44083871-71635078-9fb5-11e8-8ad0-4f173990ea8b.gif)

**So, a plugin it will be. I'm closing it, reopen if it make sense.**
