### ISSUE TITLE
[3.3.0-rc.4][Panel] Pending Changes Dropdown Does Not Appear When Clicked

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2263]
**Describe the bug**  
When clicking on the "pending changes" pencil in the toolbar, nothing happens. My Safari console shows some errors when clicking on it.

I suspect part of the problem is my Local Storage has knowledge about a page that was actually deleted on the server. It should just skip over deleted pages.

**To Reproduce**  
1. Click on the "pending changes" button in the toolbar

**Screenshots**  
<img width="1289" alt="Screen Shot 2019-10-30 at 4 32 21 PM" src="https://user-images.githubusercontent.com/417182/67906842-212cd180-fb33-11e9-933d-d4d4c00cc1c9.png">

**Kirby Version**  
`3.3.0-rc.4`

**Console output**  
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (change-template-test, line 0)
[Error] Object

code: 404

details: [] (0)

exception: "Kirby\\Exception\\NotFoundException"

file: "Api.php"

key: "error.page.notFound"

line: 199

message: "The page \"change-template-test\" cannot be found"

route: "pages/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)"

status: "error"

Object Prototype

	(anonymous function) (app.js:1:260980)
	(anonymous function) (app.js:1:256684)
	promiseReactionJob
```

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari
 - Version: 13.0.3

**Additional context**  
Example content in my Local Storage:

| Key | Value |
| --- | --- |
| `kirby$content$pages/change-template-test` | `{"api":"/pages/change-template-test","originals":{"testfield1":[],"testfield2":""},"changes":{"testfield1":"","testfield2":""}}` |

**Comment by afbora** [comment]
The source of this issue is the pages with unsaved contents cannot be found and i can reproduce on RC-4 with following more specific steps:

**To Reproduce:**
1. Go to panel
2. Edit any page without save
3. Delete the page manually (from content folder)
4. Try to click top bar pencil icon
5. See nothing on panel and check out console output

**Expected behavior**
If the page is not found in unsaved changes, it should be deleted from localstorage and the user should be able to continue operations.

**Comment by bastianallgeier** [comment]
✅ Ok, I fixed it.
