### ISSUE TITLE
[Cms + Panel] `readonly` attribute not working

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#234]
Did the `readonly` attribute in blueprints has changed from v2? If I add `readonly: true` to any field it doesn't change anything visually and I can still edit and submit changes.

Also: I've noticed a lot of the blueprints in the current alpha look like in the screenshot below (but not all). Not sure why and what happens.

![bildschirmfoto 2018-03-12 um 17 21 15](https://user-images.githubusercontent.com/3930150/37296053-1965d73e-261a-11e8-904b-12251ff272fa.png)

**Comment by distantnative** [comment]
Related: https://github.com/k-next/starterkit/issues/219

The field Vue components for sure need to be fixed here. Can you actually save the edited values, so that they end up in the content file?

**Comment by wottpal** [comment]
Yes, the changes are saved to the content file.

**Comment by distantnative** [comment]
Ok, so the issue then applies to the representation in the panel as well as the backend/CMS/API.

**Comment by distantnative** [comment]
@bastianallgeier I can only find a `disabled` property on Field in the backend. You intend to use that instead of readonly? Or is readonly just missing yet?

**Comment by bastianallgeier** [comment]
When I checked the HTML specs for fields readonly and disabled are wildly mixed. I only went for disabled as a general switch and would create an alias for readonly. Each field should then react on the disabled state in whatever way is more compliant.

**Comment by bastianallgeier** [comment]
@wottpal what are you using to validate the yaml like that?

**Comment by jenstornell** [comment]
There seems to be many alias around here and there. I think they can be good, but in the docs I hope it will be clear what value is the "real" and what is the alias.

**What I don't want to see, because of confusion**

```text
Use "disabled" or "readonly".
```

The above kind of require the developer to pick one. Don't make me think.

**What I want to see**

```text
Use "disabled".
```

...or...

```text
Use "disabled" (alias "readonly")
```

Maybe you are already aware of this, but I think it's important. Else we could end up having a mix of `disabled` and `readonly` values in our blueprints, because we could not make up our minds.

**Comment by bastianallgeier** [comment]
Most definitely aware of this! That's why I decided to go for just disabled as the switch in the first place. K3 is all about removing those ambiguous settings. I don't even know if we mention the alias at all. The only reason why there are going to be aliases is a smoother transition from v2 to v3. I would actually prefer to just cut them all off, but then it could get very painful to upgrade.

**Comment by wottpal** [comment]
> @wottpal what are you using to validate the yaml like that?

@bastianallgeier I'm not really sure if this has something to do with my editor/linter/whatever because I can see these red characters on github as well: https://github.com/k-next/starterkit/blob/master/site/blueprints/pages/product.yml. You too?

**Comment by distantnative** [comment]
Could it be a simple tabs vs. spaces?

**Comment by bastianallgeier** [comment]
The readonly alias is now working and all fields should be reacting to disabled states. 

I still have to check what the blueprint issue might be.

**Comment by nilshoerrmann** [comment]
The `readonly` setting in blueprints doesn't work on URL fields. `disabled` works as advertised but in difference to `readonly` fields it doesn't allow the user to select and copy the field content. Also, clicking the icon to the right won't open the given link.
