### ISSUE TITLE
$kirby->language() breaks with url set for secondary language

### ISSUE THREAD

**Issue by kosmar** [getkirby/kirby#2345]
**Describe the bug**  

_default lang is de, secondary is en_

the failing code is literally just:
`<?php $language = $kirby->language(); ?>`
in 3.2.3 it gives `de` or `en` depending on path being `/` or `/en` as set up and expected.

3.3.1 gives `de` in all cases and pages below `/en` are delivered as german error page

site works well when url for secondary language is unset - (but i do want a specific path or subdomain)

**To Reproduce**  
1. Go to /site/languages
2. set in secondary language:
`'url' => '/foo',`

**Kirby Version**  
3.3.1 plainkit

**Additional context**  
https://forum.getkirby.com/t/kirby-language-does-not-output-the-current-language/12860/13

**Comment by afbora** [comment]
I can reproduce too and working on 3.2.5.

**Comment by afbora** [comment]
I tracked down the issue. If `url` property is not null, `$language->pattern()` returns full path instead of relative path.

**For example:**

When `url` is null, pattern() returns: `en/(:all?)`

When `url` is custom as `foo`, pattern() returns: `test/kirby/2345/foo/(:all?)`

Should be like that `foo/(:all?)`, tested and working.

https://github.com/getkirby/kirby/blob/master/src/Cms/LanguageRoutes.php#L33

**Comment by afbora** [comment]
@kosmar I have fixed the issue, could you test the PR please? #2411

**Comment by bastianallgeier** [comment]
✅
