### ISSUE TITLE
Changing page slug in a page.create:after hook redirects to old slug

### ISSUE THREAD

**Issue by Flobin** [getkirby/kirby#2377]
When you have a hook, for instance `page.create:after` where you change the slug of a page, after creation of the page, it will try to redirect to the old slug, which doesn't exist anymore.

**Example**  

    <?php

    return [
        'hooks' => [
            'page.create:after' => function ($page) {
                if ($page->template() == 'entry') {
                    $newSlug = 'anything';
                    $page->changeSlug(str::slug($newSlug));
                }
            }
        ]
    ];

**Kirby Version**  
I experience this issue in Kirby 3.3.2 with PHP 7.4.

This doesn’t seem like a huge issue, but I thought it would be good to share.

**Comment by distantnative** [comment]
How about changing it in the `before` hook?
There is no communication between the PHP backend and the Panel from the `after` hook, so the Panel cannot be aware that you just moved the page somewhere else.

**Comment by afbora** [comment]
@distantnative We can't change the any object in `before` hook, because of before hook works like void as one-sided operation. 

But if the `before hook` returns a value, it would be great to forward it to the `after hook` 👍 

https://github.com/getkirby/kirby/blob/master/src/Cms/PageActions.php#L312-L322

**Comment by distantnative** [comment]
You don't get the object, but you could already modify the data that's passed to create the object (so alter the slug value even before the page was created):

https://getkirby.com/docs/reference/plugins/hooks/page-create-before

**Comment by afbora** [comment]
I haven't seen any reference to the `$input` value anywhere. I tested it, it didn't work.

````php
return [
    'hooks' => [
        'page.create:before' => function ($page, $input) {
            $input['slug'] = 'anything';
        }
    ]
];
````

**Comment by distantnative** [comment]
And manipulating it on $page?

**Comment by afbora** [comment]
With `$page->update()` method? Not possible: https://github.com/getkirby/getkirby.com/commit/0589ceb9d4a17f257d806e441c009769b4471caf

````
return [
    'hooks' => [
        'page.create:before' => function ($page, $input) {
            $page = $page->update([
                'slug' => 'anything'
            ]);
        }
    ]
];
````

You know that `$page->update()` method is not update the original object. I guess we need reference to the arguments or something like that? @lukasbestle Any idea about that?

**Comment by lukasbestle** [comment]
PHP arrays are not passed by reference by default, so as @afbora wrote, the user would need to manually request a reference for the `$input` variable with `&$input`. But that wouldn't work as the reference isn't passed all the way through the call chain.

What we could do is switch from `$app->trigger()` to `$app->apply()`. The `$input` array could then be modified by the hook and returned back. However the params to the different hooks are not consistent enough for that (only the last hook param is the one that is modified by `$app->apply()`).

**Comment by afbora** [comment]
Similar issue:

https://forum.getkirby.com/t/display-of-a-new-title-after-a-change-by-page-update-after-without-reload/17016

**Comment by distantnative** [comment]
We have to admit that this isn't solvable through the current setup.

I create a more abstract idea issue about triggering Panel actions/events from inside PHP hooks.

**Comment by danburzo** [comment]
I’m also toying with deriving the title and slug from other content fields, based on @lukaskleinschmidt’s [solution here](https://forum.getkirby.com/t/hook-page-create-before-how-to-edit-user-input/12656/27):

```php
class EventPage extends Page {

    public static function create(array $props): static {
        $start_date = $props['content']['start_date'];
        $props['slug'] = $start_date;
        $props['content']['title'] = $start_date;
        return parent::create($props);
    }

    public function update(
        array|null $input = null, 
        string|null $languageCode = null, 
        bool $validate = false
    ): static {
        $start_date = $input['start_date'];
        $input['title'] = $start_date;
        $page = parent::update($input, $languageCode, $validate);
        return $page->changeSlug($start_date, $languageCode);
    }
}
```

This seems to work well so far, except for the fact that upon saving the page from the Panel, it tries to redirect to the old slug. @distantnative closed this issue as impossible to fix in 2020, but I was wondering if anything changed in the meantime that would allow for this last piece in the puzzle: performing a redirect to the updated slug.

**Comment by distantnative** [comment]
@danburzo No, so far still not in the books to trigger a redirect from a hook.

**Comment by distantnative** [comment]
@danburzo any reason why you could not use https://getkirby.com/docs/reference/panel/blueprints/page#page-creation-dialog__automatic-title-and-slug ? At least for the creation, of course will not work to keep the field and slug in sync on updates.

**Comment by danburzo** [comment]
Yes, that was the path I started on, but using the stable identifier `{{page.uuid.id}}` for both `title` and `slug`, so that I don’t need to update them when content fields change. This, however, does not look great inside various parts of the Panel (in a Pages section, in the page editing UI, in the resulting URL), so I experimented with a computed title/slug based on the relevant fields.

When basing the `title` and `slug` off editable content fields, I feel it’s important to keep them in sync, and handling this in the page model’s `create()` and `update()` methods is _almost_ there.

Looking through the forums it seems there’s a common denominator for people looking for a solution to this: you have pages, like the list of showings for a film, that don’t have an identity of their own, other than the fields inside (the date-time and the venue), so it would be useful if the title/slug could be abstracted away for editors.

(There’s also another missing piece where _Duplicate page_, since it doesn’t abide by the `create` options in the blueprint, surfaces this computed title/slug in the duplication dialog.)
