### ISSUE TITLE
[Cms] Implement email sending

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#245]
We should discuss the email library that @distantnative already built. I'm a bit undecided if we should really go for PHPMailer or rather use Switfmail or Nette Mail instead. Nette Mail seems to be the most modern one, but relies on 7.1. Swiftmail is used by Symfony and Laravel, which seems like a very solid foundation. 

In the end I'd like to bind email sending to the App via `$kirby->email()`. 

At a later point it would be cool to provide email templates with shortnames like this: 

```
$kirby->email('welcome')->to('example@example.com');
```

The email templates would be stored in site/emails.

**Comment by distantnative** [comment]
Honestly, by now I’d rather throw everything away I did with PHPMailer and start over.

7.1 is tricky. 7.0 is not officially supported anymore, but how widespread available is 7.1?

**Comment by bastianallgeier** [comment]
Ok, this sucks! I evaluated three libraries: 

1. swiftmailer
2. nette mail 
3. php mailer

Swiftmailer is probably the most advanced one, but comes with a 1.6 MB package. That's huge for just sending emails and I somehow don't want to bind that many dependencies into the core of Kirby. 

Nette Mail is tiny with just around 200kb and looks rather modern. But the 7.1 minimum requirement could definitely be a problem. 

PHPMailer isn't big with around 300kb, so it might be the best compromise between the two.

**Comment by jenstornell** [comment]
Does it have to be this complicated? Why not just use http://php.net/manual/en/function.mail.php? Or do you want to do something advanced with it?

**Comment by bastianallgeier** [comment]
PHP mail() has many flaws and is often not very reliable or not even usable. We need at least SMTP support. We also had Amazon SES, Mailgun and Postmark drivers in v2. If we want to be on the same level with features, we need to reimplement them.

**Comment by jenstornell** [comment]
https://github.com/PHPMailer/PHPMailer
https://github.com/nette/mail

PHPMailer has 10000 stars on Github and Nette has below 200. The safer bet would probably be PHPMailer.

## About additional services

As for the additional services. I understand why you added them in the first place, they are common, or requested, or simple to implement. My personal opinion about it would be to cut Kirby out from external services and then reintroduce those bridges as plugins instead. 

Services come and go as well as change. It also requires maintenance to keep them updated when APIs change etc. The thing is, you don't control these services and that's why I think they should be away from the Kirby core.

If using this principle, the Youtube tag would be ditched as well (https://getkirby.com/docs/cheatsheet/kirbytags/youtube) and replaced with a plugin. The same with Vimeo, Twitter and Gist tags (or group some of them to an embed plugin).

You will probably not agree here, but I just wanted to plant a seed in your mind. 😄

**Comment by bastianallgeier** [comment]
Huge ✅
