### ISSUE TITLE
Rethinking current behavior of validators regarding required validator

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#2456]
Situation:
Right now, validators [only trigger if you have input given](https://forum.getkirby.com/t/does-an-email-validator-need-a-required-validator/17116). Let's say you have a `required` and an `email` validator, the email validator won't trigger if you remove the `required` validator due to the fact that no input means nothing has to be validated. I think this decision should be rethought for three reasons:

Issues I see with this:
1. I think this behavior is quite unexpected because if you say that this field should be validated as a valid email address, no input is not a valid email. I'm not aware of many softwares where no input means it can pass the validation of a field.
2. This will cause issues if you have a regular expression which defines the minimum and maximum length of a string: Even if the regular expression states that your input has to be >= 3 chars, it won't trigger without a `required` validator. Thus those regular expressions scenarios are just partly supported.
3. In most cases you have a different use case than `required`: You want to have some field to be optional by design/on purpose. On the other hand, most of the time your fields are anyway required to have a proper data quality given and to find out if the data you will import is indeed fine and doesn't miss some values without you knowing about it (e. g. if you get data from a customer and import it => you want to make sure it doesn't break current expected validation although the customer could have bad data in it).

My suggestion:
- Make fields always `required` if they have validators given.
- Introduce an `optional` validator to explicitly state that this field can have no or invalid data.
- Provide a boolean flag in the config to switch between new/old behavior to not break old projects.

**Comment by texnixe** [comment]
I don't agree with this suggestion. The implementation is completely in line with HTML form field validation. There is no such thing as `optional` in HTML, but only required or not required. If you don't require a field, input is optional and consequently can only be validated if there is data.  It doesn't make sense to enforce the required attribute because you add another validator.

Optional is the default if you don't add the required attribute. I don't really understand why you don't add the required attribute if that's the behavior you want?

https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation

**Comment by GiantCrocodile** [comment]
I think HTML form validation is just an usability thing and shouldn't be taken in account as a reference if we do backend-related development: The front-end validation can be easily bypassed and still can't do much harm (let's just ignore XSS for a moment). On the other hand we have the back-end which processes the data, pass it on to third party APIs, sends out emails with input, alters data, etc. I see a way bigger risk in that part so we should be more explicit and enforce stronger rules than on the front-end where we just talk about usability but not about security risks.

Even more, I think that it's not possible to enforce `required` in the front-end as a browser developer or HTML specification guru: He/She can't take his/her crystal ball and magically find out what data you need or if it's important. That's different with the back-end: No third-party has to care about your back-end nor do you need to send empty field input from the front-end: If the field is empty by design, hide it from the front-end and don't send it. It's obvious to the back-end that this form field is not filled in then. Beside that, it's easier to forget a required than to forget an `optional` validator (which imposes security risks and bad data quality while forgetting an optional wouldn't be that bad).

Maybe we should hear some other opinions on this 🙂.

**Comment by texnixe** [comment]
How would you then validate an optional field? If I allow the user to either provide data or not, I would still want my backend to validate the data, so that if I get data, I don't want rubbish.

> Maybe we should hear some other opinions on this 🙂.

Sure, I was just giving my 2ct and didn't close this (but I still wouldn't want to see this behavior).

But since this is not a bug, I'd rather see this in the ideas repo.

**Comment by GiantCrocodile** [comment]
I think that should be the case when you use `optional` validator + some other validator like `email`: Either you provide nothing or if you do provide something, it must be a valid email. If you just use `optional` you can put in anything or nothing (same with no validator).

I think what you prefer depends on what you dealt with in the past: If you are new to Kirby, it can be confusing; if you are used to it, it's annoying to have it changed. Thus I would suggest a config option with a boolean flag to change this, depending on what you prefer. I just created this issue because it took me some time, rose questions with specific regular expression and it's nothing I was used from other softwares.

Do we loose anything positive if we would change the behavior? Right now, I don't see a disadvantage but only the mentioned advantages. I even tried to think about a case where you have zero validation but can't find one: You are either limited by the browser, the HTTP protocol, the backend's programming language, file type specification, etc. Zero validation should be very very rare.

**Comment by lukasbestle** [comment]
I agree with @texnixe: Our validators are inspired by HTML validators. Those are already established in the web dev community and therefore rather easy to wrap the head around. It's *not* about whether the validation happens in the frontend or backend, but just about the semantics we are using for the validation behavior. Both ways (explicit `required` vs. `optional`) are valid and will lead to the same result, but the implementation needs to decide which approach to follow.

Besides being inconsistent with the way many people are used to from HTML, I see multiple other issues with your suggestion:

- `optional` is not a validator. It's a non-validator. This doesn't fit semantically and is therefore quite confusing and also complex to implement.
- It would be a huge breaking-change as a lot of users rely on the fact that fields are by default optional if not specified otherwise. There are many use-cases for optional fields, e.g. if you have a profile page of an employee that can have an optional direct email address or phone number, but if those are not given, the contact details should not be displayed at all. So the fields in this example should validate against the respective data type, but only if the content is provided.
- Adding a config option for the validation behavior won't work as it will make everything even more complex, harder to debug and harder to wrap the head around. We believe that consistent behavior is worth much more than configurability.

So while I understand that the "correct" way of doing this depends on personal preference and prior experience with other tools and software, I'm afraid that this is not something that can get added to Kirby. I'm therefore closing this issue.
