### ISSUE TITLE
Site setting of one language, are copied in another language fields

### ISSUE THREAD

**Issue by drapisarda** [getkirby/kirby#2473]
**Describe the bug**  
It happened twice in a day that the content of one language, have been copied on the fields of another language

**To Reproduce**  
Steps to reproduce the behaviour:
1. Open site settings
2. Switch language to a not-default one 
3. Do changes on a particular field
4. Save
5. Data from other fields on the site settings are copied from the default language to the current and saved with the proper changes

**Expected behaviour**  
Just the wanted settings are changed

**Kirby Version**  
3.2.2

**Desktop (please complete the following information):**  
 - OS: MacOS 10.13.6
 - Browser: gChrome
 - Version: 80.0.3987.116

**Comment by afbora** [comment]
I didn't fully understand the issue.
I think there is a missing of steps. 
There is no language switch button on the `site settings` page 🤔 

If you mean the site dashboard;
It only pulls the default language data when the first language data of a page is entered. It does not repeat after the language file has been created.

If you don't want it to be translated, you need to use `translate: false`.
https://getkirby.com/docs/guide/languages/translating-content#preventing-translations-of-individual-fields

**Comment by drapisarda** [comment]
For language switch, I mean the button with a world icon right under the title of the site/page dashboard.

**Comment by afbora** [comment]
@drapisarda if the non-default language doesn't have a content file (for example secondary language as TR: **/content/site.tr.txt**), this is expected behavior. This behavior doesn't repeat after the content file of the non-default language has been created.

**Comment by texnixe** [comment]
As long as you don't save the suggested content, it will not end up in the translation. If you don't want to translate the content at all, you can set the fields to `translate: false` as suggested by @afbora. If you want to translate the fields, you have to either enter your translation or remove the suggested content. The whole purpose of showing the content of the default language is to make it easier to translate content (so that you know what content you have to translate).

**Comment by neildaniels** [comment]
When I started using the panel for a multi-language site, I actually found this Panel behavior kind of confusing.

I totally get _why_ the existing content is shown there. But I think it makes it really difficult at a glance to tell whether that content is "shadow content" or actually part of that language file.

I'd be inclined to say that this default language's shadow content should initially appear as placeholder text. But that has two issues:
1. A field could already define a placeholder value and I'm not sure which one is "more important" to show.
2. It'd be annoying to translate paragraphs worth of content if everything disappears the moment you type a character (and cause the placeholder text to disappear).

Regardless, I do wish there was a way to keep secondary language content files filled with content that has _actually_ been translated, not automatically copied.

**Comment by texnixe** [comment]
In Kirby 2 we had a [`translate: optional` field property.](https://k2.getkirby.com/docs/panel/blueprints/form-fields#translating-form-fields) With this option set...

> The Panel won't pre-fill the field with the value from the default language in this case.

I think if we re-introduce that, everyone can be happy (because I think the current behavior is actually useful if you manually translate content, but I can see why it might be confusing).

**Comment by afbora** [comment]
@texnixe I used it likely in K2. Vote for `translate: optional` 👍 
What do you think? @lukasbestle @distantnative

**Comment by nilshoerrmann** [comment]
Would it be possible to let Kirby match field values between the default language and the translation on save so that it only stores content for fields that deviate and thus have been translated?

The problem with the current implementation is that when you start translating a page, all translatable field content is copied even if I only edited one field. Now, when the default language is edited again this is not reflected in the translation which will still feature the old untranslated content.

**Comment by neildaniels** [comment]
I genuinely like that idea, but I think it would have to be paired with some kind of manual indication that a field has been translated/approved.

Sometimes there are cases where a translation is "coincidentally" the same as the original language.

This is a contrived example, but lets say I started with an English text field "Film" (as in movie). A French translation would just be "Film". But if I changed the English field to "Book", it would need to be translated to "Livre" for French.

**Comment by nilshoerrmann** [comment]
Thinking out loud, what about this:

If a user creates a new translation, all translatable fields do feature the content of the source language. The content is dimmed* though, like it is for placeholders, just that it's real content that does not vanish when you focus the field. As soon as the user edits content in a field, the content is darkened to full contrast and the save bar pops up. If the user hits save, only the edited content will be saved to the content file: visually this equals all full contrast fields as the dimmed ones are still just virtual representations of the source content. If the user changes the source content, these changes will be reflected by these virtual representations on the translation view. So this is one way to mark content as translated: editing.

Thinking of your example with identical words across languages, there are two options I see in this concept:

1. Sticking to editing: if the English text is "film", the French translation will only display a virtual representation which is visually recognizable as such (it's dimmed). So the user can either just leave it as is, knowing that it might change if the source language is changed. Or the user can actively override it the the same word "film" which marks it as edited and thus saveable to the translation's content file.

2. There could be a shortcut to mark a virtual representation of the source language as accepted translation by double-clicking the field which would also bring the field to full contrast visually and would also pop up the save bar.

In general, this would require an additional property on all fields marking them as accepted translations or – vice versa – as virtual representations.

---

\* dimmed doesn't have to equal grey, it just has to be visually clear that this is "ghost content". It can be another color, there could also be a special icon visible to help people with low vision.

**Comment by drapisarda** [comment]
Personally, my issue is not on fields, but on pages themselves. I would expect some pages simply return a 404 if not explicitly translated by the content editor on the dashboard. The possibility of having some content for a not-explicitly translated page is nice but could be not required and so become harmful. 

The `translate: false` property is nice, but how nice is to have to apply it field by field?

**Comment by nilshoerrmann** [comment]
@drapisarda, so we are dealing with two issues: 

1. A config option to disable implicit translations where no content file in the specific language exists.
2. An improved translation process.

**Comment by drapisarda** [comment]
@nilshoerrmann  I do agree. In point 2, would be a great thing to have a dashboard feature to kill a whole translation, maybe preventing this for the "default" language.

**Comment by texnixe** [comment]
No matter whatever we eventually come up with, there is no way around a manual review process with a field that marks a translation as ready to be published. If I remember correctly, we definitely will not have a separate draft/published status for translations in Kirby 3, so you can only ever publish a complete page with all its translations,  and an additional field for the translation process is required. On the frontend, you can then filter your pages by this field, which will then also solve the problem that Kirby falls back to the default language if no translation/an unfinished translation is present.

Since this additional process is needed anyway, it probably doesn't do much harm if default language content accidentally gets stored in the non-default pages? That is not to say that better translation support is desirable, it definitely is!

**Comment by drapisarda** [comment]
It may harm your SEO due to duplicated content.

**Comment by texnixe** [comment]
You will not have duplicate content [if you filter your pages by a translated state](https://getkirby.com/docs/cookbook/i18n/filter-by-language). The recipe I link to only checks if a translation file is present, which is only a first step. This could be replace with a check for an actual field.

Also, with correct canonical URL settings you shouldn't run into SEO issues?

Again, I'm totally not against any improvements, just suggesting solutions for as long as we have to live with what we have and make the most of it.

**Comment by drapisarda** [comment]
New data for the bug. 
I had a user who changed a field for a component. Then she changed also a lot of data on other component forms without realising it. The wrong data were old data that we used to edited months before the bug.
So feels like this is not related to the i18n, but to the form management per se.

**Comment by dinko** [comment]
Not sure whether this is resolved. I ran into the same problems @drapisarda described initially.

1. Set up a textarea field in site blueprint.
2. Saved the field in the default language (de, in my case)
3. Switched to a different language (en, in my case)
4. Made edits to the field and saved.
5. Check on live page, edited content still appears in default language.
6. Reload of backend page » edits are gone and replaced by content of field in default language.

**Comment by distantnative** [comment]
I have created a few idea tickets from the suggestions in this thread:
- https://kirby.nolt.io/317
- https://kirby.nolt.io/318
- https://kirby.nolt.io/319
- https://kirby.nolt.io/320

Please upvote and add your further comments there, so we can structure the discussion towards the different aspects.
