### ISSUE TITLE
Start Session only on demand

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#249]

**Comment by jbeyerstedt** [comment]
This would be really nice, especially because of this EU cookie law. Or does this not affect php session cookies?

**Comment by Zegnat** [comment]
Disclaimer: I am not a lawyer, and all that.

---

> Or does _[EU cookie law]_ not affect php session cookies?

This is an unanswerable question because there is no one “EU cookie law”. Every country implements their own variant of the EU directive. What I can say is that, by [the Dutch implementation (NL)](http://www.rijksoverheid.nl/onderwerpen/internet/bescherming-privacy-op-internet/cookiewet-regels-en-richtlijnen) of the EU directive, so called functional cookies that enable websites to work (their example is an online store’s shopping cart) do **not** require explicit permission from the visitor. This would apply to PHP session cookies as well.

---

The term cookie is flawed, as the wording in several of the national implementations and of [the EU directive](http://eur-lex.europa.eu/legal-content/EN/TXT/?uri=URISERV:l24120) it self could refer to `localStorage` and other methods of storing information:

> before information is stored on their computers or devices or before access to that information is obtained

**Comment by jbeyerstedt** [comment]
You are right, but this whole thing is kind of confusing and many websites are displaying some annoying banners. I´m just trying to get into it. But this should not be the main point.

It´s not very bad, that the session is opened and a session cookie is transmitted, even if it is not used, but it would meet my perception of software and web aesthetics if there is no (somewhat personalized) data transmitted, which is not needed. If there is no need for a session, my browser should not transmit some data, which tells everybody, that I´m still the same.
This is not a big problem, but it would be quite nice, if this is "fixed". But this is just my quite idealistic opinion.

**Comment by bastianallgeier** [comment]
I totally agree with this idea and therefor just added it to the develop branch :)
