### ISSUE TITLE
Korean full locale doesn't seem to work

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2542]
**Describe the bug**  
When setting the locale for Korean to `ko_KR.utf-8`, the locale setting is ignored, while setting it to only `ko` works.

For more information, check out this forum thread: https://forum.getkirby.com/t/korean-sortby-issue/17676/19

**Kirby Version**  
3.3.5

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Firefox

Tested with Mamp and Valet and different PHP versions. It seems, the result is different on different machines, though.

**Comment by afbora** [comment]
As far as I know, this is expected behavior for [setlocale()](https://www.php.net/manual/en/function.setlocale.php) function:

> If locale is an array or followed by additional parameters then each array element or parameter is tried to be set as new locale until success. This is useful if a locale is known under different names on different systems or for providing a fallback for a possibly not available locale.

I couldn't test it (because it works all kinds of me) but I think we can check and set the available languages with a use like this:

````php
return [
    'locale' => [
        LC_ALL => ['ko_KR.utf-8', 'ko_KR', 'ko', 'korean'],
    ]
];
````

**Comment by texnixe** [comment]
But if the locale `ko_KR.UTF-8` is installed on my system (I verified with `locale -a`), then I would expect this to work?

**Comment by afbora** [comment]
I'm not quite sure, but yes it has to be.
`ko, ko_KP, ko_KR`is available locales for me on windows locale, but even if I change places, `ko` always returns. What about you?

````php
echo setlocale(LC_ALL, 'ko_KR.utf-8', 'ko_KR', 'ko', 'korean'); // return always ko for me
````

**Comment by texnixe** [comment]
It depends on what I put first, some of these don't return anything on my system when used alone.

```php
echo setlocale(LC_ALL, 'korean', 'ko', 'ko_KR', 'ko_KR.utf-8'); // ko_KR

echo setlocale(LC_ALL, 'korean', 'ko', 'ko_KR.utf-8', 'ko_KR'); // ko_KR.utf-8

echo setlocale(LC_ALL, 'korean', 'ko',); // ko_KR.utf-8; // nothing
```

**Comment by afbora** [comment]
@lukasbestle Do you have an idea about this is bug or expected behavior?

**Comment by lukasbestle** [comment]
My Mac (Catalina 10.15.4) has the following Korean locales (from `locale -a`):

- `ko_KR`: Sorts `3 1 2 4` (*not* working)
- `ko_KR.eucKR`: Sorts `1 2 3 4` (working)
- `ko_KR.UTF-8`: Sorts `3 1 2 4` (*not* working)
- `ko_KR.CP949`: Sorts `1 2 3 4` (working)

Just `ko` (not listed in `locale -a`) works as well.

So this issue seems to be about the encodings that are used. I have now tried saving all content files with `EUC-KR` (Korean encoding). This will break the Panel as the Panel only supports UTF-8 content files. But you can still access the pages from templates, so I did the `->sortBy('title', 'asc', SORT_LOCALE_STRING)` there and got the following results:

- `ko`: Sorts `1 2 3 4` (working)
- `ko_KR`: Sorts `1 2 3 4` (working)
- `ko_KR.eucKR`: Sorts `3 1 2 4` (*not* working)
- `ko_KR.UTF-8`: Sorts `1 2 3 4` (working)
- `ko_KR.CP949`: Sorts `3 1 2 4` (*not* working)

So now suddenly the locale with `UTF-8` encoding works even though I have switched to `EUC-KR` encoding. And once I save the files with `UTF-8` again, the results switch back. 🤯

Of course this is no solution (as I wrote the Panel won't work), but it tells us that this issue is even weirder than we thought. I'm pretty sure this is a PHP issue as the underlying sorting function is from PHP's core. We cannot do anything about this unfortunately.

So the best way would be to use the `ko` locale as that seems to work consistently no matter what the encoding is.
