### ISSUE TITLE
SQlite ROWID is not accepted as valid field in where clauses

### ISSUE THREAD

**Issue by andreasotto** [getkirby/kirby#2576]
`Db::update` and `Db::delete` using sqlite's `ROWID` fails.

example:
```
			$bool = Db::delete('books', [
				'ROWID' => $data['id']
			]);
```

result: `Invalid column ROWID`

**Comment by lukasbestle** [comment]
I have now verified why this happens: To detect the existing columns of a table, we run a [`PRAGMA table_info(:table)` query](https://www.sqlite.org/pragma.html#pragma_table_info) against the DB. This query returns the list of all columns of the table, but the result does not include `ROWID`, not even if there is no named ID column in the given table. The reason for this is that `ROWID` is not a real column, but just a virtual pointer to the internal row ID.

The only way we could fix this is adding a special case just for SQLite that `ROWID`, `OID` and `_ROWID_` are always valid columns (maybe with an additional check if the given table is a [ROWID table](https://www.sqlite.org/rowidtable.html), but that check is not necessary for security, so we could get away without it).

Adding this special case would be a hack, which would make the implementation more complex than necessary. To be honest, I think that this hack is not worth it for the slim use-case where the `ROWID` column actually needs to be used in queries: Tables with ROWID that don't also have a named `INTEGER PRIMARY KEY` column (which will [alias the `ROWID` automatically](https://www.sqlite.org/rowidtable.html)).

And given that the SQLite docs explicitly advise against using tables without named `INTEGER PRIMARY KEY` columns [because the IDs are then not persistent and may change](https://www.sqlite.org/rowidtable.html), the use-case becomes even slimmer.

I am therefore closing this issue. Please let me know if you disagree.
