### ISSUE TITLE
excerpt() not working on Asian languages

### ISSUE THREAD

**Issue by mpaeslack** [getkirby/kirby#259]
In my testing I came across the following

the excerpt() helper works well on English, German, etc. but does not do anything on Chinese and Japanese text.

**Comment by cilice** [comment]
Could you please create a file called info.php at the root of kirby with
```php
<?php phpinfo();
```
Then open it in the browser and look if "mbstring" occurs there somewhere? It's a sign your PHP version lacks support for multibite utf8 strings, like asian languages are.

**Comment by mpaeslack** [comment]
Thanks for the hint, phpinfo() has a whole section about mbstring and shows it as enabled. 
So I assume this is not the problem. 
![screen shot 2015-06-26 at 09 53 25](https://cloud.githubusercontent.com/assets/3752727/8369245/40e7b9aa-1be9-11e5-8a83-c2015316764e.png)

**Comment by bastianallgeier** [comment]
Could you provide some sample text that I can test with?

**Comment by bastianallgeier** [comment]
Without any sample text, I'm afraid I can't really test it. I'm closing this for now until it might come up again.

**Comment by tillprochaska** [comment]
While in most western languages, words are separated by a space, in Chinese and Japanese, characters and words are actually the same concept, i. e. a single character represents a word. (If I’m not mistaken, in Japanese, words might as well be composed of two characters. However, as this is difficult to determine this programmatically, it’s still common to simply count characters in order to know how many words are in a text.)

Kirby’s `excerpt(…)` function is implemented using PHP’s `str_word_count(…)`. `str_word_count(…)` uses the C function `isalpha(…)` in order to determine wether a character is an alphabetic character, i. e. to determine wether a character is part of a word. `isalpha(…)` (and thus `str_word_count(…)`) aren’t save to use with non-ASCII characters (at least on some operating system/platforms…).

Examples:

```php
setlocale(LC_ALL, 'de_DE');
echo str_word_count('äöü äöü', 0); // => 6
echo str_word_count('Bäume', 0); // => 2

setlocale(LC_ALL, 'ja_JP');
echo str_word_count('家', 0); // => 0
```

As a consequence, `excerpt('家家家', 2, 'words')` returns the original string instead of `家家`.
