### ISSUE TITLE
[Panel] StructureField – Keyboard shortcuts

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#261]
It would be great to have a way to close&save a structure-field item. Maybe by pressing Esc/Enter when any field of the structure-item is in focus. Or simply collapse all structure-field items after saving via `CMD+S`.

**Comment by bastianallgeier** [comment]
✅

**Comment by REHvision** [comment]
@bastianallgeier unfortunately this is not completely solved yet.

`Esc` and `Cmd + S` work nicely to close/leave an opened structure item :wink:
`Enter` doesn't do anything on most fields (which is okay and maybe no issue since it could also lead to unwanted changes and `Cmd + S` is more explicit).

**But actually the toggle field reacts to `Enter`** which is quite problematic in this scenario (as I also wrote in [my too quickly solved issue](https://github.com/k-next/kirby/issues/536#issuecomment-403795096)) :fearful: 

Besides from that, **when tabbing through fields and over collapsed structure fields**, the delete button of each item gets highlighted but the field itself not (so you don't know where the "cursor" is in this case).
Only if you hover the structure field with the mouse you see that the sort handle is highlighted. But the sort handle doesn't allow for keyboard navigation and there is no way to open/enter the structure item itself.
