### ISSUE TITLE
[Panel] Use Gravatar for Default User Profile Pictures

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#262]

**Comment by jenstornell** [comment]
**I will vote against this one because of what I said here:**

https://github.com/k-next/starterkit/issues/245#issuecomment-374248951

>As for the additional services. I understand why you added them in the first place, they are common, or requested, or simple to implement. My personal opinion about it would be to cut Kirby out from external services and then reintroduce those bridges as plugins instead.

>Services come and go as well as change. It also requires maintenance to keep them updated when APIs change etc. The thing is, you don't control these services and that's why I think they should be away from the Kirby core.

>If using this principle, the Youtube tag would be ditched as well (https://getkirby.com/docs/cheatsheet/kirbytags/youtube) and replaced with a plugin. The same with Vimeo, Twitter and Gist tags (or group some of them to an embed plugin).

What I DO think could be very useful is to be able to hook on whatever service you want, in various places in the panel (by plugins). This could be one of those places. Then Kirby would stay independent from external stuff.

In this case these could be helpful:

https://sv.gravatar.com/site/implement/images/
https://sv.gravatar.com/site/implement/hash/

**Comment by distantnative** [comment]
I honestly am not a fan of Gravatar as well… both as an external additional service, but also I think it doesn't fit to Kirby. My personal opinion.

**Comment by distantnative** [comment]
GDPR has shown that it is great to have Kirby as disconnected from anything else, making no calls somewhere else. So that developers can rely on that when building sites. In that view, I would say we do not implement something that would cause the panel making calls to a third-party service like Gravatar.

@bastianallgeier correct me, if I am jumping ahead here.
