### ISSUE TITLE
[Panel] Add auto-save not only on blur, but every X seconds

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#268]

**Comment by jenstornell** [comment]
Is the time counter reset on blur save? I hope so. There is no need to re-save on time directly after it has just been saved by the blur.

If you are going to reply, what is the time seconds set to? 30 seconds?

**Comment by distantnative** [comment]
There is no time interval at all. You will hear more about it later in the live stream, but in Alpha 6 on every input the values are saved to localStorage and then with the hit of a button (or Cmd+S) send to the API. So we do not need any auto-save on blur or after X seconds anymore at the moment.

**Comment by jenstornell** [comment]
Ahh, I see. I hope it's very clear in the panel when the page is saved and when it's not (when it's in localstorage).

Else we may forget to save the localstorage data to file. The next day we for some reason need to clear the cache, change browser or use the phone instead to continue to work. Then all the work will be lost, (not there) because it's bound to the computer and browser where we started the page.

I see a big risk, so I hope you get this right.

A really visible notice that the page is not saved is probably the best/only way. Maybe you have already solved it this way?

**Comment by distantnative** [comment]
I'd suggest you check out the stream in less than four hours.

**Comment by jenstornell** [comment]
Alright, I'll hold my breath until then... Sorry for about the nag. 😸
