### ISSUE TITLE
kirby()->language() always returns the default language in ready callback option

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2703]
**Describe the bug**  
I want to set an option based on the current language. Since I can't use the `$kirby` object directly in `config.php`, I use the `ready` callback option. However, `kirby()->language()` always returns the default language. In templates, it returns the correct one.

**To Reproduce**  
1. Create a multi-language setup
2. `var_dump(kirby()->language())` in `ready` callback
3. Navigate to a translated page
4. See the default language locale

**Expected behavior**  
Should return the current language, determined by the URL.

**Kirby Version**  
3.4.0

**Comment by afbora** [comment]
I think because the route runs after the ready option 🤔 
 `kirby()->router()->route()` returns null in ready option.

````php
'ready' => function() {
    var_dump(kirby()->router()->route()); // returns NULL
    var_dump(kirby()->language());
}

**Comment by bastianallgeier** [comment]
The problem with this is the definition of "ready". In our current implementation the ready callback is called when the App is fully setup. But it's called before any routing happens, so Kirby does not know yet, which language should be used. I think this is the correct way to handle it because we wanted to provide that callback to be able to overwrite certain options from the config depending on the App setup. This could include routes. 

In such a scenario we would need another callback directly after the router is being called and then offer a way to still overwrite options. I'm not entirely sure though if this could have weird side effects. This is all super tricky. We've messed around with similar ideas and problems for ages. You basically end up in an everlasting race between setting and getting options at the right time in the lifecycle of the app.

**Comment by bastianallgeier** [comment]
I removed the bug label. It's really not a bug per se. It's more like a conceptual problem depending on the lifecycle of the app.

**Comment by yandodov** [comment]
Maybe there's a way to partially setup the router before running the `ready` callback? I mean, the current language isn't determined by the config, but by the visited URL, which is constant.

**Comment by bastianallgeier** [comment]
I think in this case it would be better if you use the request object to inspect the path yourself and find the language code accordingly tbh. Running the router twice just to be able to detect the correct language at such an early stage seems like a pretty big overhead. Especially if new routes could be added within the ready callback and everything changes afterwards anyway.

**Comment by distantnative** [comment]
Would it help if we just offer another hook after language detection is done?
Given, depending on what the option is used for, at that point setting the option might be too late again.

**Comment by lukasbestle** [comment]
I haven't tested it, but I think using the `route:before` hook could work. The only issue is that it doesn't seem to be possible to set options dynamically after they have been "baked" by the `App` class (which is a reliability feature to prevent that plugins can easily overwrite options).

**Comment by distantnative** [comment]
That's why I asked whether we need another (new) hook/callback like `ready` after detecting language where setting options is supported (as with `ready`) :)

**Comment by lukasbestle** [comment]
The more hooks we have, the more difficult it becomes to keep the overview which one does what...

**Comment by dustsucker** [comment]
The Problem seems to still exist in Kirby 4 in 2024. We had Problems with the $page->title() function like in #2611
And found this bug in the code. Setting $this->content = null in the Page content() function seems to fix it, but forces a reload as Content is created every time the function is called.
