### ISSUE TITLE
DB Pagination Bug

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#2738]
**Describe the bug**  
I just ran into an issue where I'm able to paginate DB queries but not able to access the proper pagination object from the returned collection.

**To Reproduce**  
1. Create a DB query and use `$query->page(…)` to paginate
2. Try to fetch the pagination object from the returned collection
3. The pagination object differs from the one created in the `page` method

I think the problem is right about [here](https://github.com/getkirby/kirby/blob/master/src/Database/Query.php#L789). Not sure if this was possible at some point or not. But as far as I can tell it is not possible to set the pagination object with the `$collection->paginate()` right now.

**Expected behavior**  
I should be able to get the proper pagination object from the collection.

**Kirby Version**  
3.3.5

**Comment by afbora** [comment]
I think, we're using `Collection` (`Kirby\Cms\Collection`) instead `Kirby\Toolkit\Collection` iterator. I'm trying to understand the code comment and implementation why we used that. After all both iterator attach the pagination object, right?

https://github.com/getkirby/kirby/blob/6b20fa11843f57cd9a1e611bc9e8e8a91b855156/src/Database/Query.php#L776-L780

I'm not sure if DB will be refactored in 3.7, but if the solution is simple, we can fix it and get it out of the way.

**Comment by bastianallgeier** [comment]
I think we should provide a quick fix and not wait for some refactoring. We plan to do that for way too long already.

**Comment by afbora** [comment]
If we remove `->iterator('Collection')` set, seems will be solved but I'm not sure about that. Need @lukasbestle thoughts.

**Comment by lukasbestle** [comment]
I agree it might be because of `Cms\Collection`. It has its own special pagination handling that the `Database` classes don't expect/can't deal with.

The reason that we [explicitly set `->iterator('Collection')`](https://github.com/getkirby/kirby/blob/6b20fa11843f57cd9a1e611bc9e8e8a91b855156/src/Database/Query.php#L776-L780) is that the user could have also set `array` beforehand. But with the `array` iterator the pagination is entirely impossible. I believe that's what the code comment is trying to say.

I believe the solution should be to use the fully qualified class name as `->iterator('Kirby\Toolkit\Collection')`.

**Comment by afbora** [comment]
Why we set iterator again? Default iterator is already `Kirby\Toolkit\Collection`.

https://github.com/getkirby/kirby/blob/6b20fa11843f57cd9a1e611bc9e8e8a91b855156/src/Database/Query.php#L44

**Comment by distantnative** [comment]
@afbora in case the user set it to array (which then would crash with pagination, so we force it to be collection no matter if/what the user set)

**Comment by bastianallgeier** [comment]
✅
