### ISSUE TITLE
Srcset support for `(image: ...)`

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#2741]

**Comment by ipenburg** [comment]
Who's problem are we trying to solve here? It's not like it's currently impossible or even hard to create a responsive website with Kirby. Based on a visual design you can choose if you need to implement only some automatic resolution switching or need to also bother editors with solving art direction problems. If it's not clear what built-in srcset support is supposed to solve we probably just end up with an opinionated default that ticks some responsive checkbox without much additional value over a less complex solution.

So, maybe it makes sense to formulate this feature as a User Story: As a < type of user >, I want < some goal > so that < some reason >?

**Comment by distantnative** [comment]
Since this doesn't seem as clear cut and with our ambition to reduce issues in this repo to mainly bug reports, I have created a Idea on Nolt referencing this great discussion: https://kirby.nolt.io/112
