### ISSUE TITLE
Unexpected behavior creating textarea with Html::tag 

### ISSUE THREAD

**Issue by LeBenLeBen** [getkirby/kirby#2743]
**Describe the bug**  

Since version 3.4, when you create a `textarea` element with the Html::tag method like this:

```php
Html::tag('textarea', null);
```

The output is:

```html
<textarea>
```

and therefor not valid HTML. Everything following this tag ends as the textarea content.

**Expected behavior**  

A textarea without content should generate a closing tag as well:

```html
<textarea></textarea>
```

**Kirby Version**  
3.4.0

**Workaround**

Pass an empty string as the second argument of the `Html::tag` method.

**Comment by lukasbestle** [comment]
The previous behavior of the `Html` class was pretty inconsistent and buggy, so we have refactored it in 3.4.0.

If you set the second argument to `null`, you will [now get a self-closing element](https://getkirby.com/docs/reference/tools/html/tag). If you want an empty `<textarea>`, use an empty string like so:

```php
Html::tag('textarea', '');
```

**Comment by bastianallgeier** [comment]
@lukasbestle sorry to intervene here, but I missed this change to be honest. Why would passing null create a self-closing element? There's a fixed list of self-closing HTML elements that we can use to do this automatically.

**Comment by LeBenLeBen** [comment]
I agree with @bastianallgeier, I didn't find a way to create just a closing element, so I don't think creating an "invalid" opening-only element should be allowed.

**Comment by lukasbestle** [comment]
Sorry for closing this so early. I should have explained in more detail why this is the case, which I now want to catch up on:

The `Html::tag()` method has been documented to return a self-closing tag for `$content === null` [since Kirby 3.0.0](https://github.com/getkirby/kirby/blob/3.0.0/src/Toolkit/Html.php#L348) (possibly even earlier). Unfortunately the method didn't actually do what the documentation said. Instead it just used the fixed list of void tags (`Html::isVoid()`) to determine whether to use a self-closing tag or not.

The refactored implementation in 3.4.0 now does what the documentation has said from the beginning. To be honest, I just didn't expect while refactoring that people explicitly used `null` as the second argument before Kirby 3.4.0 as the documentation said to use an empty string for an empty non-self-closing tag. Also, `null` was the default value anyway before Kirby 3.4.0, which made me believe even more that explicitly setting `null` is pretty unlikely. The new default value is an empty string, which matches the documentation and prevents a breaking-change both for those who left out the second argument in this case and for those who have used an empty string all along.

But of course it *is* a breaking-change for those who passed `null` explicitly, which as I said was not a possibility I imagined.

Unfortunately we didn't catch this during the review process and the release candidates, so I didn't know until now that this was actually a breaking-change for some of our users like you. That's bad and it shouldn't happen. I'm very sorry that it caused problems for you. :(

---

Now let's talk about the way forward. But before that, I want to explain what the refactoring in Kirby 3.4.0 did:

Before Kirby 3.4.0, we had both an `Html` class and an `Xml` class. They used very similar but different code, which meant code duplication and different, sometimes buggy behavior (like in this case where the code didn't match the docs). So what I did in 3.4.0 was to merge the two classes together and move the basics into the `Xml` class so the `Html` class can depend on it/extend it with HTML-specific features. This ensures consistency and makes the whole set of classes much easier to test for each edge-case.

But merging the classes also meant that the `Xml::tag()` method now needed to support self-closing elements to avoid having to duplicate the full code in `Html::tag()` again (there needs to be a way for the `Html` class to make the `Xml` class generate self-closing tags). So `Xml::tag()` now accepts the same `null` (which is again consistent with the documentation).

The `Html::tag()` method can now call the `Xml::tag()` method with a `null` argument either if the user has explicitly defined that (otherwise the extended `Html` class would behave differently than the `Xml` class, which is again very confusing and not allowed in PHP inheritance) or if the tag is a known void tag (in which case the `Html::tag()` method will enforce a self-closing tag automatically).

This all means that passing `null` to `Html::tag()` will now indeed return a self-closing tag. So one reason is the adaptation to the docs and the other reason is PHP class inheritance.

---

If we decide that we want to roll this behavior back to the old behavior, we would need a protected method in the `Xml` class that can generate both normal and self-closing tags. The public `Xml::tag()` method would then only support normal tags like before and internally call that protected method.

At the same time, we would need to remove the feature that allows to pass `null` explicitly for self-closing tags. I'm not sure if that's a good idea though. The previous behavior of always using just the hard-coded void list means that it would be impossible to generate other self-closing tags that we haven't listed. Also we have documented this feature for a long time now, so there could be edge-cases where users have depended on the documented behavior and where it worked by accident but would stop working in the future if we change anything else about the classes later (at which point we will have forgotten that the feature has been a thing people may have relied on).

**Comment by LeBenLeBen** [comment]
Thanks for taking the time to explain! For me specifically, this is not an issue anymore. I just replaced the previously `null` value with `''` in the only place where this was causing an issue. I just wanted to report it since that looked like an undesired breaking change.

To give you more context, my case is a dynamically generated form based on an external service that allows people to submit an application for a job. It was done back in the Kirby 2 days. The `null` value was coming from the textarea default value, populated with POST data, through `get($field->name)` which returns `null` if the value is empty apparently. I changed it for `get($field->name, '')` and it’s all good now.

**Comment by lukasbestle** [comment]
Thanks for the additional information!

I‘d say we should wait if other users run into the same issue. We‘ll leave this issue open for now for further discussion.

**Comment by bastianallgeier** [comment]
Thanks for the explanation @lukasbestle. I really wasn't aware that we had it in the docs like this. 

It makes total sense to share the tag code between the XML and HTML classes. It also makes 100% sense that the Xml::tag method provides an easy way to create self-closing tags and passing null for the content to create one makes sense as well. 

But in my opinion there's also never a situation in which I want `Html::tag('textarea', null)` to create a self-closing textarea or `Html::tag('div', null)` to create a self-closing div, but as in @LeBenLeBen's example there's a high chance that passing null as empty value - like in form submissions - can happen. 

Couldn't we just handle this entire problem inside an extended `Html::tag()` method without breaking inheritance? 

In the Html class we already know which elements are void. So for all other elements we could take care of passing an empty string to the `parent::tag()` method if the element is not self-closing but the value is null. 

This does not break inheritance, is easy to implement, but also still creates a more reliably behaviour for the `Html::tag()` method. What do you think?

**Comment by lukasbestle** [comment]
That's a nice and simple solution!

I thought about something like this yesterday but discarded it because passing `null` to `Xml::tag()` would then return a different result than passing `null` to `Html::tag()` (because the logic is different). In pure inheritance, this wouldn't be allowed. But I forgot that we are talking about static methods here, so the fact the methods extend each other is purely an implementation detail and not something anyone would rely on. From the outside the classes are distinct.

This still leaves us with the minor issue that it won't be possible to override our hard-coded `isVoid()` list, but actually you can by just calling `Xml::tag()`, which will do exactly what you tell it to do no matter if the tag is in our list or not. So by removing the documented feature again, we don't actually remove any functionality.

I have fixed this in #2751. I think we can still ship this in 3.4.1 as the code change is very minor.

**Comment by distantnative** [comment]
Love this solution!
Regarding your comment, @lukasbestle, maybe we could make the list a static property (like we do in other classes). That way, if someone would want to alter the list, they still could.

**Comment by lukasbestle** [comment]
Oh yes, absolutely! On my list. :)

**Comment by bastianallgeier** [comment]
✅  I just merged it into our rc.
