### ISSUE TITLE
Server with no server name has wrong URLs

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2778]
**Describe the bug**  
We have a Kirby site running on nginx and AWS. Our server has no `server_name` set and when you visit `http://my-website.eu-central-1.elasticbeanstalk.com`, all URLs in the site use the local server IP, e.g. `http://172.31.21.191/assets/image.jpg`. That URL is inaccessible because the IP is not exposed to the internet.

This appears to happen because Kirby uses `SERVER_NAME` in `Server::host()` [here](https://github.com/getkirby/kirby/blob/29b36fffa6527804ac0fdea757c77878c3ccd1b8/src/Http/Server.php#L160), instead of using `HTTP_HOST`. This is how `phpinfo()` looks when `server_name` is missing:

![image](https://user-images.githubusercontent.com/5570098/90006675-041c5600-dca2-11ea-99b4-efc7b3ec5574.png)

Since `HTTP_HOST` holds the host name with which the HTML document is accessed, I think it makes sense to use that for the URLs in the page itself. At the moment, I use this as a fix in my `index.php`:

```php
$_SERVER['SERVER_NAME'] = $_SERVER['HTTP_HOST'];
```

...but I think it'll be better if Kirby handles it in core.

**Kirby Version**  
3.4.2

**Comment by neildaniels** [comment]
Keep in mind: if you use `$_SERVER['HTTP_HOST']` then the end-user can send a request with whatever host they want. (It's merely pulled from the request header.) Because of this, you do run the risk of your server generating pages with arbitrary hostnames. If you have custom configs that are based on your expected hostname, those won't be applied if the user overrode the host.

There's some more context here (albeit skews a little towards Apache advice): https://stackoverflow.com/questions/1459739/php-serverhttp-host-vs-serverserver-name-am-i-understanding-the-ma

On my Nginx setup, I manually define the `server_name` fields that I need to avoid complications. (Also note: if you list multiple names in the same `server_name` property, only the first will appear in `$_SERVER['SERVER_NAME']`. You'll need multiple server blocks if you need more than one.)

Because of the potential to bypass domain-specific config settings (among other concerns), I don't think Kirby should fall back to `$_SERVER['HTTP_HOST']`.

**Comment by yandodov** [comment]
I did some research on my own and found about Host header attacks. I agree that using `HTTP_HOST` wouldn't be a good idea. But on the other hand, Amazon URLs are unpredictable, which makes this problem annoying to handle.

That's why I propose to use `HTTP_HOST` only when the `debug` option is set to `true` and only use it as a fallback, i.e. when `SERVER_NAME` is empty. I have a `config.my-site.com.php` where I've set `debug` to `false`, so I wouldn't have this vulnerability in production, but I _would_ be able to open the test environment successfully.

**Comment by lukasbestle** [comment]
I agree with @neildaniels. Using `HTTP_HOST` would introduce a potential attack surface.

> That's why I propose to use `HTTP_HOST` only when the `debug` option is set to `true`

To be honest I'm not sure this is something we can do in the core:

The `debug` option is meant for debugging, so it mostly enables detailed error reporting. In your specific case, enabling this fallback for development hosts is a good fit as your development host is the only one with this issue, but in other setups the missing `SERVER_NAME` could be completely independent from debugging hosts.

Adding this behavior to the `debug` handling would also mean that changing the value of the `debug` option changes the behavior of Kirby. If you wanted to debug exactly that behavior, you wouldn't have any way to do so.

**Comment by yandodov** [comment]
@lukasbestle that makes sense. Then perhaps you should put a warning somewhere in the docs about this issue and leave it at that.

**Comment by lukasbestle** [comment]
Done. ✅
