### ISSUE TITLE
[Panel] Switch to Top Navigation Bar

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#284]
![mockup](https://user-images.githubusercontent.com/3788865/37835119-b18ea78c-2eaf-11e8-9597-6843757c4a58.jpeg)

**Comment by distantnative** [comment]
Especially with those 3 menu items to the right, I think it could be really cool if only the icons would be visible on default and when you hover over one of them, the text label slides out.

**Comment by jenstornell** [comment]
Instead of the left sidebar? Why this change? It's probably easier to adapt to mobile devices / responsiveness.

The pitfall is when there is much information up there. Then it may break at some point.

## Another CMS

### Old version

Menu on top. Then they bloated it and added sub menus.

![image](https://user-images.githubusercontent.com/927011/37835330-380403f2-2eb0-11e8-8e22-725586d44d6b.png)

### New version

Sidebar to the left like Kirby has now. They also have a top menu for some things.

![image](https://user-images.githubusercontent.com/927011/37835358-46d2e8e4-2eb0-11e8-8999-1e27209bfb26.png)

### May work, kind of

I think it can work if very careful what to put there. In your mockup, I like the things up to the right, but I would prefer to have only the icons and also put them all the way to the right. I'm not too fond of the left stuff, at least not if we could keep the left sidebar around.

**Comment by jenstornell** [comment]
Now I read this quote:

>I think it could be really cool if only the icons would be visible on default and when you hover over one of them, the text label slides out.

Ahh, please don't slide on hover. What will happend is that when hover, all the other icons will move around like crazy. And it will not work on a mobile device (if that's important).

Instead, put a simple title attribute on them.

**Comment by bastianallgeier** [comment]
I like it a lot and actually even started implementing a topbar version last week. Here are the main reasons, why I think it's good to switch back: 

1. the sidebar in its current state is just a waste of space. Even with a couple additional custom views, it would be not very useful compared to how much space it needs. 

2. with our new sections, the more space we have for the content, the better. The entire concept really starts to shine when all the focus is on the content and not on some stupid bar. 

3. TBH I added the sidebar because everybody has it. Not a very good reason in the first place. 

4. The topbar is so much easier to make responsive. 

5. We can use icons only for a very narrow mobile version and show the labels as soon as possible. The icons + labels are the most obvious solution for users. 

6. If we need to add custom views, we can still switch to a dropdown menu like in v2

**Comment by jenstornell** [comment]
Yes, if you prevent this top menu from being bloated with all kinds of stuff, I think it can work.

What if we have a plugin that needs 5 custom views and want to somehow group them. Then we have three plugins like that. How will that work? If we let the plugins put like groups up there it can be crowded. A dropdown submenu could work but it's not really easy to navigate them.

Maybe I'm thinking too far ahead, but maybe keep the sidebar, but only for the custom views. Then the item would serve as a group that could collapse and open and in that group have the custom views. It would work with infinity groups with infinity items. If no custom views exists, then the sidebar could be hidden.

I don't have the answers, but I think a discussion about custom views could be healthy when that time comes.

**Comment by distantnative** [comment]
I would say we have plenty of time into the future of 3.x to figure out some concept of preventing too many custom view menu entries. Given that real custom view plugins will be possible for the first time with 3.1 as it looks like right now, I would assume to only see a handful plugins to add this at all in the next months.

**Comment by lukasbestle** [comment]
What about a sidebar with only icons that expands to icon+text when needed?

**Comment by distantnative** [comment]
@lukasbestle What would be the advantage to a top bar (with only icons or icon + text when needed)?

**Comment by lukasbestle** [comment]
If you expand the sidebar, it has more room for custom views. The topbar can't really be expanded downwards to get the same effect.

**Comment by bastianallgeier** [comment]
IMHO the custom views are really no big issue. What are realistic scenarios? I can't think of even bigger projects where we would end up with more than 5 or 6 additional custom views. Those can easily be hosted in a dropdown and it wouldn't affect the usability in a negative way. But we gain a much leaner setup in terms of making the main content area responsive. An expandable sidebar means lots of extra css for the collapsed/expanded version + lots of edge cases for the content area. If we had element queries, I would be totally up for it, but this way I see more problems than benefits.

**Comment by jenstornell** [comment]
I have a new fresh approach. Let's say we keep the top bar.

One plugin then register 5 custom views. Instead of some grouping/nesting, maybe the can have access to setup tabs, just like on panel pages. Then one plugin should always only take up one item in the dropdown.

**Comment by distantnative** [comment]
Tabs, sections etc. will be all available to custom view plugins eventually. No worries ;) That's why @bastianallgeier and I think that we really don't have to worry about to many custom plugin views.

**Comment by lukasbestle** [comment]
I agree. In the end, the topbar has more advantages than disadvantages.

But regarding “more space for content”: I think the content area should also not be too wide.

**Comment by jenstornell** [comment]
@distantnative If a custom view works just like a page, with fields etc controlled by a blueprint, it would be a nobrainer for a field developer to create a custom view.

A nice sideeffect would be that you crew would not need to do much to implement it. Everything is already there. The only thing you would need to figure out would be where to save settings from such a custom view.

*low hanging fruit*

**Comment by lukasbestle** [comment]
That's the plan. We want to provide full customizability (= custom HTML) but also want to offer a simpler blueprint-based approach. After all it is already possible to build custom sections – and if all you need is a view that is made up of such sections, you don't need the full customizability.

So as I said: We want to provide both at some point. But that's unrelated to the topbar issue (for which we are working on a nice solution at the moment).

**Comment by bastianallgeier** [comment]
✅
