### ISSUE TITLE
Topbar hamburger arrow not needed

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#293]
The hamburger menu icon looks good, but the arrow next to it does not really fill any function. It just takes up space and makes it less clean.

![image](https://user-images.githubusercontent.com/927011/37920454-29b4e98c-3127-11e8-9e56-4a2c28547983.png)

**Comment by distantnative** [comment]
Thanks for your comment, but at this time in the alpha phase we will keep the current state. There has been quite some thought gone into this and we want to see how it works out through the alpha and beta phase. We might come back to such minor design details at the end of the beta, if (looking back) this has turned out problematic.
