### ISSUE TITLE
Topbar button looks the same as success

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#294]
Which of these two is a button and which one is a success message. It's hard to tell if at first sight. Maybe make the button look like a button, or some way to distinct the two?

![image](https://user-images.githubusercontent.com/927011/37920747-fdcff338-3127-11e8-9a36-00035e2529cf.png)

**Comment by distantnative** [comment]
Thanks for your comment, but at this time in the alpha phase we will keep the current state. We might come back to such minor design details at the end of the beta, if (looking back) this has turned out problematic or in general reworking the button components (since there are a few issues open where we agree that they definitely need some work in terms of accessibility etc.).
