### ISSUE TITLE
Topbar site icon makes it over exposed?

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#295]
There is an icon to the left of "Site" on the bar. It takes up some space, but it also makes "Site" very exposed, maybe too much.

"projects" and "projects-a" does not have an icon.

I think "Site" looks good in the dropdown menu, because all things have icons.

![image](https://user-images.githubusercontent.com/927011/37920917-8a438618-3128-11e8-89c6-f47343fa6267.png)

**The alternative could look like this:**

![image](https://user-images.githubusercontent.com/927011/37921302-bb6c40da-3129-11e8-8f6b-9b2adea41ae9.png)

A bit cleaner I think.

**Comment by distantnative** [comment]
Thanks for your comment, but at this time in the alpha phase we will keep the current state. There has been quite some thought gone into this and we want to see how it works out through the alpha and beta phase. We might come back to such minor design details at the end of the beta, if (looking back) this has turned out problematic.
