### ISSUE TITLE
[Panel] Accessing parent of page section items

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#298]
Hey 👋

I find it quite difficult to reach pages like `/about`, `/projects`, .. in the panel. Currently the only option is clicking on the headline of the page-list under *Site*. But these headlines don't really look like links. Especially after ditching the sidebar (where important page-links could have been placed) it's important to make things more clear. 

One question: How does the page-list element even know where to link its headline to? The deepest common parent of all queried pages?

(PS: I know UI isn't finalized yet 😛)

**Comment by distantnative** [comment]
If you want more explicit links, you just have to set up your `site.yml` blueprint accordingly, featuring a section like

```
main:
  type: pages
  query: site.children
```

Regarding your question about where the headline links to: This is defined with this piece of code

```php
public function link()
    {
        $parent = $this->parent();
        $model  = $this->model();

        if ($parent === null) {
            return $this->linkForModel($model);
        }

        $parentClass = get_class($parent);
        $modelClass  = get_class($model);

        if ($parentClass !== $modelClass) {
            return $this->linkForModel($parent);
        }

        return null;
    }
```

Model is basically the current object you are at, could be a page, file, user or the site. If there is no parent, headline links to the parent itself. Otherwise the parent and the model are compared if they are from the same class (e.g. both a page). Only if not (e.g. model is a page, but parent is site – or model is a file and parent a page), the headline links to the parent. If none of these options apply, the headline does not link anywhere.

**Comment by distantnative** [comment]
The next alpha will make it visually more clear when/that a section headline can be clicked:
<img width="1106" alt="screen shot 2018-03-29 at 17 22 08" src="https://user-images.githubusercontent.com/3788865/38097469-c5c43350-3375-11e8-89bd-9ea7e65d91bb.png">
