### ISSUE TITLE
Keyboard shortcut for panel search is broken

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#3015]
**Describe the bug**  
The Keyboard shortcut for opening the panel search is broken since Kirby 3.5

**To Reproduce**  
1. Log in to panel
2. Press ⌘ + ⇧ + F

**Screenshots**  
<img width="400" alt="Bildschirmfoto 2020-12-18 um 11 44 49" src="https://user-images.githubusercontent.com/18071758/102606505-1f531280-4127-11eb-9298-f33d38aeb8b2.png">

**Kirby Version**  
3.5.0

**Console output**  
none

**Desktop
 - OS: macOS
 - Browser: Chrome, Safari, FF

**Comment by afbora** [comment]
@distantnative This issue occurs because the `search` method in `App.vue` (binded `this.$events.$on("keydown.cmd.shift.f", this.search)`) has been removed on this commit https://github.com/getkirby/kirby/commit/8f60f285028368e54b872507e2b2134660b1f7a9#diff-1cb2e578b6777ca784e882355c095af6e8b2c9926eba469a5ca844aeb939a237

**Comment by bastianallgeier** [comment]
@distantnative is there a reason why this has been removed? Can we reimplement it?

**Comment by bastianallgeier** [comment]
✅
