### ISSUE TITLE
Detecting cronjob requests feature

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#303]
Kirby CMS can not detect Cronjob requests. I think, this feautre should be have.

I created cron.php and included bootstrap.php but doest work properly.

Sample cronjob request:

    /usr/bin/php -q /home/astalavista/public_html/index.php /api/test

**Comment by lukasbestle** [comment]
I already answered in the Kirby forum, please don't open the same issue twice.

**Comment by afbora** [comment]
This is not issue. This is feature request.

My cron.php working but not properly. For example: api/test working perfect but same function in cron.php is not.

Why not implement detecting cronjob requests into Kirby? Useless or unnecessary?

**Comment by lukasbestle** [comment]
What you mean is not a "cronjob request" but general command-line support for Kirby. Supporting this would mean changing a lot of the code, because the PHP APIs for web and CLI differ a lot.

I can help you with implementing your `cron.php` in the forum if you tell me there what exactly doesn't work properly.

**Comment by afbora** [comment]
For example:

   /usr/bin/php -q /home/astalavista/public_html/index.php /api/test

CodeIgniter undertstand above request from cronjob and run `api/test` method. But Kirby not.

Just putting a listener for cron requests isnt enough? Is this so hard?

**Comment by lukasbestle** [comment]
CodeIgniter is a quite huge general web framework and Kirby is a CMS.

I think that CLI requests are simply not widely used with Kirby. Adding complexity for a feature that isn't the/one main selling point is not worth it in my opinion. Kirby is simple and should stay simple.

But since I'm not an official member of the Kirby team, I can't give definite answers. @bastianallgeier, what do you think about this?

**Comment by lukasbestle** [comment]
BTW: You can also use `curl http://example.com/api/test` in your cronjob and it will just work.

**Comment by bastianallgeier** [comment]
I'm actually on Lukas' side here. It would be awesome to have a cli interface in general. Lukas started to work on something for Kirby 1 and there's this: https://forum.getkirby.com/t/kirby-cli-installer/1311 but unfortunately both projects stopped. Adding it to the core would be a huge overhead. So I can only hope that either project gets traction again :)
