### ISSUE TITLE
Collection::filter(): Should clone the instance consistently when the filter is invalid

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#3170]
This is the only branch that returns the instance itself:

https://github.com/getkirby/kirby/blob/3.5.3/src/Toolkit/Collection.php#L294

For consistency, it should also clone the instance so that the return value can always be assumed to be independent from the original instance.

**Comment by bastianallgeier** [comment]
I know it seems like a small issue, but wouldn't this still be considered a breaking change?

**Comment by lukasbestle** [comment]
Yep, better safe than sorry. I've moved this to 3.6.

**Comment by distantnative** [comment]
I'm realising, this seems to be dead code:

- By default `$operator` is `==`
- The only place where this would be changed is https://github.com/getkirby/kirby/blob/3.5.3/src/Toolkit/Collection.php#L277
- But the if statement already checks if the operator (`$test`) exists
- So `$filter` could only be `null` in this line https://github.com/getkirby/kirby/blob/3.5.3/src/Toolkit/Collection.php#L293 if `==` was not an operator in `static::$filters` as in https://github.com/getkirby/kirby/blob/3.5.3/src/Toolkit/Collection.php#L290
- But we always define `==` in the same file https://github.com/getkirby/kirby/blob/3.5.3/src/Toolkit/Collection.php#L1190

So that code can't really be reached at all.

**Comment by bastianallgeier** [comment]
@distantnative you are right. We should probably just remove that if clause.

**Comment by lukasbestle** [comment]
Yep, good catch! 👍
We can also remove the `?? null` in the line above as the array element is guaranteed to exist.

Users *could* unset the `!=` filter manually, but I don't think anyone would do that.

**Comment by bastianallgeier** [comment]
✅
