### ISSUE TITLE
Object methods: Align return values (immutable)

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3231]
It feels very weird to have return values of `$this|static` on many of the page action methods.
From my view, it would be much clearer if they would always behave as immutable `static` (or even if we return `$this` for performance reasons) to  only label them as `static`.

@lukasbestle would be great to hear your opinion on this?

**Comment by lukasbestle** [comment]
To be honest I don't think so. The difference is indeed something to wrap the head around the first time you stumble across it, but just `static` would be wrong as long as we actually return `$this`.

I think the better strategy is to communicate this more clearly. Maybe there could be a tooltip for these type hints that explains what `$this` and `static` mean.

**Comment by distantnative** [comment]
Explaining the difference between `$this` and `static` is not the problem. And I get that they are per-se different.

My point is, that I don't think it is very sensical that the same method returns sometimes `$this` and sometimes `static`, e.g. `Page::changeNum`: https://github.com/getkirby/kirby/blob/develop/src/Cms/PageActions.php#L36

I don't think it's very user-friendly that when the passed `$num` is the same as the current, we just return the existing object (`$this`) but in other cases we treat the object as immutable and return a clone. It's something rather difficult to handle for the user.

I get why we are doing this for performance reason, but with our automatically generated reference, it's near impossible to communicate which one happens in which case. We would have to display both explanations - for $this as well as for static - and somehow when they apply.

**Comment by lukasbestle** [comment]
The issue is that such a change would be a massive breaking change. The whole immutability inconsistency we have at the moment really needs to be fixed, but we can't do it until Kirby 4 IMO.

I think in the example you mentioned it wasn't explicitly done for performance reasons but just because at the time we didn't think about the difference and its implications.

But to be honest I think the difference doesn't matter much in practice: The user can always reassign the object to a local variable. No matter if the same instance is returned, the user can continue working with that assigned variable. As far as I can tell, every actual change to the objects is done by cloning it (so that the object stays immutable), so assigning the same instance and then running additional operations on it shouldn't cause issues.

Maybe I missed something here, but I don't think most users will need to know exactly when a method returns what, it's just important to know in general that the method sometimes returns different values. Those who need to know are already so technical that they can look it up in the code. If we'd start documenting this, the reference would become out of date quickly and it would also be a massive task.

**Comment by distantnative** [comment]
> If we'd start documenting this, the reference would become out of date quickly and it would also be a massive task.

Yes, I think any docs here only van be automatic ones.

> But to be honest I think the difference doesn't matter much in practice: The user can always reassign the object to a local variable. 

I think the most critical case is the other way around: a user expecting immutability  and getting a new cloned object, assigning it to a new variable as they want to work with this new object. But actually `$this` was returned and now they are working on the existing instead of a separate object.

**Comment by lukasbestle** [comment]
But if every action that actually changes the object's properties clones the object, is there a difference between working with a clone of a clone or a clone of the original? The end result will in both cases be a clone. I think it's never possible to overwrite anything in the original object. So a `$this` instance should be harmless, even if the user expects a clone.

**Comment by distantnative** [comment]
Didn't think about that. Indeed, it doesn't matter if you work with a clone or the actual object if any method that alters the state returns a clone. Haven't checked all again, but let's assume all altering methods work like that.
