### ISSUE TITLE
Session: Allow clearing the session on the "Session is currently read-only" error

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#3263]
From a discussion with @nilshoerrmann on Discord:

The error can only be fixed by clearing the session cookie from the user's browser. So the exception could pass a flag in its `details` data (like `'offerSessionClearing' => true`) that would then be picked up by the Vue frontend to render a custom dialog with the options to retry, logout or cancel. Logging out would be done by sending a `POST` request to a new API endpoint that then clears the session cookie.

This needs to be tested with both debug mode on and off as the exception will likely differ between the modes.

**Comment by nilshoerrmann** [comment]
When a fatal error occurs on the frontend, Kirby has this neat way of presenting this to the visitor: 

- First, there is a bold headline declaring the that there happened a fatal error in general.
- Second, there is an advice for the developer in smaller type.

This kind of writing would be nice here as well:

- So there could be a general message: "You cannot login because your session is locked – [ clear ]"  
- The more technical information (including the session id/hash) could be given in small print and in debug mode only.

**Comment by nilshoerrmann** [comment]
This is still an issue.
