### ISSUE TITLE
File not deleted via files field in panel

### ISSUE THREAD

**Issue by verkruemelt** [getkirby/kirby#3379]
**Describe the bug**  

Delete File in `files` field doesn't delete that file. It's only unlisted in the field, but it exists in the folder anyway. File is visible in the side-panel with preset `page`. If you try to 'reupload' the file error `The file exists and cannot be overwritten` occurs.

**To Reproduce**  
1. Create new page via panel.
2. Upload a file to that page. Save.
3. Delete that file via `files` field. Save.
4. File isn't listed in `files` field but in the side panel.

**Expected behavior**  

Delete the selected file in the `files` field.

**Screenshots**  
![grafik](https://user-images.githubusercontent.com/1926264/119953910-c1acd700-bf9e-11eb-9f43-fbdd260418a1.png)

**Kirby Version**  

3.5.5

**Console output**  

No Output.

**Desktop (please complete the following information):**  
 - OS: Win10
 - Browser: Chrome 91.0.4472.77, Firefox 88.0.1

**Smartphone (please complete the following information):**  
Not tested.

**Additional context**

**Comment by afbora** [comment]
This is expected behavior. Because the files field keep the page data. It is not `deleted` from the files field, it is `removed`. To delete the file from the page, you should use the [files section](https://getkirby.com/docs/reference/panel/sections/files), not the [files field](https://getkirby.com/docs/reference/panel/fields/files).
