### ISSUE TITLE
Cropping an image fails, if there is already a resized image with the crop dimensions

### ISSUE THREAD

**Issue by trych** [getkirby/kirby#3418]
**Describe the bug**  
I was just trying to resize and to crop some images and ran into this bug:

Let's say I have an image of these dimensions: `529 × 705`
Now, if I first resize this image with something like: `$img->resize(512, 288)` then it will create a resized image with the dimensions `216 × 288` and save it in the media folder with a name like `myimg-512x288.png`.
Now, if I next try to crop the image with the same numbers, `$img->crop(512, 288)` it does *not* create a new, cropped image as Kirby seems to assume that the image already exists and it takes the previously resized image (which is wrong).

So my guess is that the names collide as the media folder does not create different names for cropped or resized images. Now that I investigated this issue, I am fairly certain that I have run into this issue in the past already and thought the crop command is broken somehow.

**Expected behavior**  
Crop the image as expected, even if there already is a resized image with the same arguments.

**Kirby Version**  
3.5.3

**Desktop (please complete the following information):**  
 - OS: macOS 10.13.6
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by distantnative** [comment]
I think the solution should be that the first image is saved as `myimg-216x288.png`

**Comment by trych** [comment]
I have to be honest, I don't even properly understand how the `resize()` method is supposed to work. If I do `resize(512, 288)` on this particular image, it apparently resizes only by height and ignores the `512`. What is the logic behind this? How does it decide which side to resize? Cannot find anything about this in the docs.

**Comment by trych** [comment]
Btw. the same bug happens when I first do `resize(512)` and then later `crop(512)`, as it then sees the image `myimg-512x.png` already exists. So I don't get the square cropped image as I would expect.

Not sure, if the specific nomenclature of `filename-512x.png` is important to keep track of how the image was created, but if not it could just be changed to the actual final dimensions as @distantnative was suggesting. If it is important somehow, the name would also need to keep track of the original command being a crop or a resize, so something like `filename-c512x.png` / `filename-r512x.png`.

**Comment by iskrisis** [comment]
The drivers are naming images only using values provided to the functions. So that's not ideal. The main reason for this i think is that the resize calculation is passed to the gd/im along with the final name of the file upfront so it cannot know dimension calculated by gd/im AND you need to generate the url for the final image somehow without reading the image to get the dimension because that would be inefficient. So it's very simple and a bit dirty solution.

@trych the `resize`/`crop` functions will never upscale. Resize will also keep ratio of the image. So `resize` downscales to boundaries provided in the function and keeps the ratio. Now if you think about it both functions have to somehow generate the image name/url so it can be used later. This can lead to problems when you want to have two images that would lead to same filename. For example if you wanted have two same images one cropped to square `crop(512)` and other resized to 512 width in ratio `resize(512)` it will lead to same `image512x.jpg` filename. 

Your suggestion about adding `c`/`r` is interesting. In mean time there are few strategies how to tackle this:

- Does it ever make sense to use resize and crop together? Crop in Kirby is already resize/dimension aware. I am not sure what would be the usecase since both functions generate different commands for image generation. I think they are not chainable at all.

You can feed the image more input to make things work. 
- For example you could use `crop(512, 512)` that will generate `image512x512.jpg` image. Yes it seems that `crop(512,512)` and `crop(512)` are generating two different thumbnails. This is probably easiest bug to fix that would help some of the issues.
- Another hack to get around might be to specify use `quality`. `resize(512, null, 70)` and `crop(512, null, 71)` will give you two working images resized `image512x-q70.pg` and cropped `image512x-71.jpg`.

I know this is not ideal especially needing tho know this BUT i am working mostly on image heavy websites and it is rare to hit limits of this simple system.

**Comment by lukasbestle** [comment]
I agree it would be best to include `c` in the filename for cropped files. This ensures best performance and also fixes the bug.

**Comment by iskrisis** [comment]
@lukasbestle what do you think about adding the second implied dimension? `crop(512)` outputting `image512x512` instead of `image512x` ? Is there any technical reason for this? I think it makes sense to use `image512x` or `imagex512` if i use `resize(512, null)` `resize(null,512)` it makes it clear which dimension i didn't care about. But with `crop` it always means rectangle if i use only one dimension.

**Comment by lukasbestle** [comment]
I looked through the code but couldn't fully track down if a cropped thumb with just a `$width` is guaranteed to become a square with `$width x $width`. If that's the case, I think we can safely make `crop(512)` use the thumb `image512x512` instead of `image512x`. @bastianallgeier?

**Comment by iskrisis** [comment]
For reference the height for crop is initially set here https://github.com/getkirby/kirby/blob/38afb2d650f3764d23d732b23ae8f04ab9ffba69/src/Image/Dimensions.php#L77 if not set its just null and handling of this is passed to each driver:
IM https://github.com/getkirby/kirby/blob/38afb2d650f3764d23d732b23ae8f04ab9ffba69/src/Image/Darkroom/ImageMagick.php#L198 GD https://github.com/getkirby/kirby/blob/38afb2d650f3764d23d732b23ae8f04ab9ffba69/src/Image/Darkroom/GdLib.php#L75

`IM` driver leaves this to `IM` by using their syntax https://imagemagick.org/script/command-line-processing.php#geometry in `GD` width is used as height if no height is provided.

Maybe it should be better to pass handle these missing values upfront like in this normalize method https://github.com/getkirby/kirby/blob/38afb2d650f3764d23d732b23ae8f04ab9ffba69/src/Image/Darkroom.php#L79 

But i am unsure where the code for the url generation is because i assume that would break.

**Comment by lukasbestle** [comment]
Thanks for tracking this down! I fully agree the height should be normalized upfront.

The name of the thumb is generated by `Cms\Filename::attributesToString()` if I remember correctly.

**Comment by bastianallgeier** [comment]
The only way to properly fix this is by adding "crop" to the filename. If one of the dimensions is missing, it's not being recalculated in order to create the filename. This would mean that the file dimensions would need to be read for every thumbnail. This slows down the performance of a page dramatically if it has a lot of resized/cropped images on it. But as soon as we add the additional "crop" value to the filename, it should be fixed. A PR is on its way.

**Comment by bastianallgeier** [comment]
✅
