### ISSUE TITLE
Error Uploading Some SVGs in Panel (attribute and namespace errors)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#3424]
**Describe the bug**  
I've run into situations where the Panel refused to accept uploads of certain SVGs. It seems like it's running SVGs through some kind of strict validation, where some extra attributes or "invalid" attributes cause an outright rejection.

Can this validation be removed or improved for SVGs?

Current workaround is I have to import and reexport SVGs from something like Sketch.

**To Reproduce**  
1. Try to upload either of the attached SVGs to a Panel files section

[Example SVGs.zip](https://github.com/getkirby/kirby/files/6632933/Example.SVGs.zip)

Reproduces on https://trykirby.com

**Expected behavior**  

**Screenshots**  
<img width="529" alt="Screen Shot 2021-06-10 at 9 08 01 AM" src="https://user-images.githubusercontent.com/417182/121559949-e9069980-c9cb-11eb-8733-f0dba910a120.png">
<img width="528" alt="Screen Shot 2021-06-10 at 9 09 10 AM" src="https://user-images.githubusercontent.com/417182/121559946-e7d56c80-c9cb-11eb-946c-433432130985.png">

**Kirby Version**  
`3.5.6`

**Console output**  

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.1 (16611.2.7.1.4)

**Comment by bastianallgeier** [comment]
The new validation rules are a the result of a potentially severe security issue, we fixed in: https://github.com/getkirby/kirby/releases/tag/3.5.4 

We will look into your examples and see what we can do. Our tip right now is to optimise the SVGs with https://jakearchibald.github.io/svgomg/ first. It's a lot more comfortable to import and reexport from Sketch.

**Comment by lukasbestle** [comment]
@neildaniels I've [created a PR](https://github.com/getkirby/kirby/pull/3457) that allows to allowlist the custom namespace used in the second file. It's weird that this namespace is in there as it's not used at all, maybe it's just an ad for the optimization tool?

Regarding the first file I agree with Bastian that optimization before upload is the way to go: The `xml:space` property is deprecated. There are a few other deprecated properties that are in use in tools with a lot of history (like Illustrator or Inkscape). We didn't want to include them as we would have to manually review each of them for possible security risks. It's a good idea anyway to run SVGs through SVGO or SVGOMG to get an optimized file size for the web.

Also see https://github.com/getkirby/kirby/issues/3433#issuecomment-864851723 for more details on our `Sane` implementation and how you can extend it.

**Comment by bastianallgeier** [comment]
✅

**Comment by rasteiner** [comment]
SVGOMG no longer removes `xml:space` since [SVGO v2.1.0](https://github.com/svg/svgo/releases/tag/v2.1.0). This is because `xml:space` is actually useful (Illustrator uses it, many files online have it, and browsers still support it even if deprecated). 

Could you point me in a direction that explains what the security implications of `xml:space` are? 
The only source I've found is [this](https://www.zerodayinitiative.com/advisories/ZDI-19-710/), where the exploit consists of crafting a particular value for `xml:space` and making the file interact with XmlLite.dll

Did I miss another one or is it just that? Otherwise it could be useful to allow this attribute, but limit its value to `"preserve"` (there's also `"default"` as valid value, but that is removed by svgo because it's the [obvious] default).
I think I would be able to PR this if you want

**Comment by iskrisis** [comment]
I have the same issue. It's really to explain clients. Actually i myself can't seem to be able to upload svgs. One thing is `xml:space` but i also get errors like `enable-background` not allowed.

Can't i turn this off if i don't have malicious editors?

**Comment by lukasbestle** [comment]
@rasteiner @iskrisis We will add support for `xml:space` [in 3.6.1](https://github.com/getkirby/kirby/issues/3982). Missing it was an oversight. In a future 3.6.x release we will also add a mode that allows to sanitize instead of validate uploaded files. Then everything that isn't allowlisted will just be removed from the uploaded file.

@iskrisis You have two options: Either you can add the attributes you need to the allowlists (for example with `Kirby\Sane\Svg::$allowedAttrs[] = 'enable-background';`). If you want to disable validation completely, you can use:

```php
unset(Kirby\Sane\Sane::$handlers['svg']);
unset(Kirby\Sane\Sane::$aliases['image/svg']);
unset(Kirby\Sane\Sane::$aliases['image/svg+xml']);
```

For everyone else reading along: Of course we *do not* recommend this. Only do it if you are absolutely sure all file uploaders can be trusted.

**Comment by alicericci** [comment]
> 
> @iskrisis You have two options: Either you can add the attributes you need to the allowlists (for example with `Kirby\Sane\Svg::$allowedAttrs[] = 'enable-background';`). If you want to disable validation completely, you can use:
> 
> ```
> unset(Kirby\Sane\Sane::$handlers['svg']);
> unset(Kirby\Sane\Sane::$aliases['image/svg']);
> unset(Kirby\Sane\Sane::$aliases['image/svg+xml']);
> ```

In which file do I need to put those lines to disable validation ?

**Comment by lukasbestle** [comment]
@alicericci Do you still have a need for this after the changes in Kirby 3.6.1? I‘m interested to hear what stops you from using Sane.

To answer your question: You can put these lines anywhere after Kirby is initialized, so in a plugin file or in `site/config/config.php`.

**Comment by alicericci** [comment]
@lukasbestle Thanks ! 


After the changes in Kirby 3.6.1, svg cleaned up with [svgomg](https://jakearchibald.github.io/svgomg/ ) work, but svg straight from illustrator don't. 
<img width="474" alt="Screenshot 2021-12-30 at 12 20 59" src="https://user-images.githubusercontent.com/43652271/147747733-061042dc-15f3-4d03-827d-37f680c50e0f.png">
The doctype produced by illustrator 
`<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
`

**Comment by lukasbestle** [comment]
@alicericci I don't have Illustrator at hand to test it, but I heard that checking "Minify" in the export dialog omits the doctype.

**Comment by 8grad** [comment]
hej, 👋🏼 *.svg's cleaned up with [svgomg](https://jakearchibald.github.io/svgomg/) does the trick for me.
