### ISSUE TITLE
[3.6.0] Class aliases don't seem to work always

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3479]
<img width="485" alt="Screen Shot 2021-07-03 at 15 45 12" src="https://user-images.githubusercontent.com/3788865/124356330-b8ee9700-dc15-11eb-879d-fff9091503f6.png">

Need to investigate

**Comment by bastianallgeier** [comment]
The aliases are loaded in the bootstrap.php file. I think this is an issue when an alias is used in a class definition before the bootstrap file is even loaded. Could be mainly a composer issue.

**Comment by distantnative** [comment]
Let's see throughout the alpha and beta how often plugin developers will face this. Maybe we can ignore it, it's super easy to fix on the plugin's side.

**Comment by lukasbestle** [comment]
Does this only happen when the aliased classes are used in plugins? If so, is it a full Composer install where Kirby and all plugins are installed from a global `composer.json`? Because then Composer should resolve the dependencies so that Kirby is loaded before the plugins that depend on Kirby.

If Kirby isn‘t installed via Composer, that dependency resolving won‘t be done.

**Comment by distantnative** [comment]
> If Kirby isn‘t installed via Composer, that dependency resolving won‘t be done.

I think this was the case for me in my plugins development setup.

**Comment by lukasbestle** [comment]
Could you please test that again by comparing these two cases (Kirby installed with Composer and a simple ZIP extract from the `kirby` repo)? If installing Kirby with Composer fixes it, then this is basically intended behavior and we can't fix it in Kirby.

**Comment by distantnative** [comment]
What Lukas wrote.
