### ISSUE TITLE
Docs: $users->create()

### ISSUE THREAD

**Issue by Pascalmh** [getkirby/kirby#357]
It seems like the language should be a mandatory field as the Panel breaks for users without a specified language.

A better Solution is probably to fallback to another default site language?

> Panel Error:
> The package.json is missing for the translation with code: 
> 
> It happened here:
> File: /panel/app/src/panel/translation.php
> Line: 41

How to reproduce:
```
site()->users()->create(array(
    'username' => 'foo',
    'password' => 'bar',
));
```

Now try logging with the user.

**Comment by lukasbestle** [comment]
Users are not always used to log in to the Panel. They can also be used for frontend login, which won't need the language attribute.

I think the Panel should fallback dynamically instead (meaning: when logging in and the attribute is not set).

**Comment by bastianallgeier** [comment]
I just fixed this in the panel.

**Comment by fourpixels** [comment]
Sorry to open this again, but is there a way to somehow rename that file, because `package.json` is heavily used in `NPM`? I stumbled upon a problem because I'm using some npm modules to upload my website, so I've ignored `package.json` to be uploaded to the server..

It's not that much of an issue, but just mentioning :)

Otherwise - you rock!

**Comment by bastianallgeier** [comment]
@fourpixels I think you hit the wrong repo and issue.

**Comment by fourpixels** [comment]
Sorry, a bit overwhelmed and tired of work. I've had an issue uploading the whole site on a server, and because of the above mentioned things, my package.json was missing and therefore the panel wasn't working. And I've ended up posting this thing here, as the error was quite the same :)

Sorry again about spamming your nice topic, I can delete my comments later on :)
