### ISSUE TITLE
[Starterkit] .htaccess: don't redirect for non-existent asset files

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#357]
Currently, if an asset file does not exist, those requests are also redirected to `index.php` or `panel/index.php`. Which is not ideal, since we cannot detect if a icon svg file does not exist etc.

Therefore, we should not redirect for those request, but simply let them fail. Ugly but functional `.htaccess` to implement this:

```
# make panel links work
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
 +RewriteCond %{REQUEST_URI} !^/panel/assets
  RewriteRule ^panel/(.*) panel/index.php [L]
  
  # make site links work
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
 +RewriteCond %{REQUEST_URI} !^/panel
 +RewriteCond %{REQUEST_URI} !^/assets
  RewriteRule ^(.*) index.php [L]
```

But maybe there is a way to make that prettier.

**Comment by bastianallgeier** [comment]
After double-checking, I think we can close this tbh. Site assets throw our Kirby error page which is fine because we get a 404 on that and we can check for it. The panel assets redirect because of the panel router. That's fine as well IMHO, because we handle assets in the panel differently anyway and we don't have to check for stuff which might not be there.
