### ISSUE TITLE
Calling replace() on an empty field results in the page ID

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#3652]
**To Reproduce**  
1. Clone the plainkit
2. Set the homepage title to `Title: ` (empty value)
3. Modify the template to `<?= $page->title()->replace(compact('page')) ?>`

**Expected behavior**  
When `replace()` is called on an empty field, an empty string is expected. The page ID is returned instead.

**Kirby Version**  
3.5.7.1

**Comment by lukasbestle** [comment]
This is caused by the following lines in `ModelWithContent::toString()`:

https://github.com/getkirby/kirby/blob/bf73940837cbaa3c13da511c23b539466e141bbf/src/Cms/ModelWithContent.php#L699-L701

It looks like a useful fallback for general-use string templates, but for the `replace()` method it's indeed weird.

**Comment by afbora** [comment]
✅
