### ISSUE TITLE
[3.6.0-alpha.4] WebP & AVIF support

### ISSUE THREAD

**Issue by findthebug** [getkirby/kirby#3660]
The new thumnail gen is super nice, but missing one feature in my opinion. right now, if i set the default thumbail settings to webp in config the media folder will just deliver webp even i uploaded a png.
this is o.k, if u just using webp images but for backward compatibility it would make sense the system would deliver also the original file e.g. jpeg or png, as a format pair like:

media/cool.webp
media/cool.jpeg (original file format)
...

if you have such pairs in media you can do following. the browser can now decide which files to take and you have proper fallback for old browsers.

```html
<picture>
    <source data-srcset="cool.webp" type="image/webp" srcset="cool.webp">
    <source data-srcset="cool.jpg" type="image/jpeg" srcset="cool.jpg">
    <img data-src="cool.jpg" src="cool.jpg">
</picture>
```

would be great if i can set multible thumb gen in config which generates the media folder with the given image-pairs

```php
'thumbs' => [
    'format' => ['webp','png','jpg'],
],
```

**Comment by distantnative** [comment]
As you point out yourself, this would require an output of the template methods (e.g. `$image->thumb()`) drastically from the current behaviour, e.g. generating a `<picture>` set.

There is a feedback idea about `<picture>` set: https://kirby.nolt.io/333
Though, as I voiced there, I am not too convinced yet that there is a standard way yet that we could support. Too many different solutions for doing responsive images still, so that any implementation would be very opinionated.

Maybe for your specific needs, a custom file method (https://getkirby.com/docs/reference/plugins/extensions/file-methods) would be more suitable than integrating this opinionated solution into the core. With that you could realise something like

```php
$file->thumbs(['webp', 'png', 'jpg'])
```

**Comment by lukasbestle** [comment]
I agree with Nico. A custom file method allows maximum flexibility regarding the output markup. If we baked that into the Kirby core, it would be very hard to customize.

**Comment by MaluNoPeleke** [comment]
Is there a more specific example of the mentioned custom file method for this use case?
I would like to use it as well but don't know how to build it.

**Comment by lukasbestle** [comment]
I don't think anyone has implemented yet, but basically it would call `$this->thumb()` for every passed format and then return the HTML code for the `<picture>` element.

**Comment by bastianallgeier** [comment]
I agree that a custom method is the way to go, but we should also start thinking about a next step in our image delivery API. Cloudinary, KeyCDN and Imgix offer a way to deliver images based on the accept header sent by the browser. This way you can make use of webp or avif based on the accept header in a regular img. But this is nothing we can solve in 3.6.
