### ISSUE TITLE
[Panel] File section: drag from other section to set/replace cover

### ISSUE THREAD

**Issue by HYR** [getkirby/kirby#371]
Not sure if this just isn't implemented yet but I'm not able to make another (already uploaded) image the cover image for a post.

![image](https://user-images.githubusercontent.com/5200901/38321899-162ab3c6-37f6-11e8-8fa8-8663edc44607.png)

**Comment by distantnative** [comment]
Cause they belong to a different files section with a different file template. Delete the current cover, upload a new one – or simply replace the current one.

**Comment by HYR** [comment]
@distantnative But as a user wouldn't you expect to be able to choose a new cover image from your existing images. Say I want the current cover image to still be in the page but not the cover image. If I'm understanding you correctly I have to delete both and re-upload them to make the change. That seems unintuitive to me. I expected to be able to drag and drop the image on to the cover spot and have them swap places. Or maybe choose from dropdown menu to do that.

**Comment by distantnative** [comment]
Regarding the dropdown menu:
Keep in mind that the Cover section is just another files section with a maximum of 1 file (and the cards style instead of the list style). You could have 7 of such files sections in your blueprint. Which one should be in the dropdown then? and would swapping really make sense once you have more than 2 sections?

**Comment by HYR** [comment]
Good points. Just letting you know what i expected to be able to do as a user. Perhaps you can tie the draggable areas together through a blueprint setting? Not sure what the best answer is. :)

**Comment by distantnative** [comment]
@bastianallgeier Maybe we could have some dragging between file sections of the same parent, where  dragging would change the file template (similar to changing the page status).

And with sections that have already their max of files, instead of adding/sorting the new one in between, we would replace the current file with the dropped one. Or even swap them.

Thoughts?

**Comment by meszarosrob** [comment]
I think I can resonate with what @HYR is saying here.

Using different CMSs I got used to having some kind of "media selector" where in some situations I was able to select images from already uploaded files.

To make it more concrete this "Cover" image deceivingly (on the surface) looks a hell lot like the "Featured Image" in WordPress https://youtu.be/hNg1rrkiAjg?t=18s

When I was playing around with Alpha 7 I had once or twice the expectation to select for the cover an already uploaded image.

I had to reflect on what I am actually doing - that I am using Kirby now and not some kind of other CMS - to get rid of this automatization.

In some situations it would make sense to have a modal where I could select the already uploaded images for that specific page - I can think of differnet usecases, but I also can understand that this might be something that is not aligned with Kirby in general.

**Comment by wottpal** [comment]
I also had the feeling that it should be easily possible to either upload a cover-image or select it from another files-field so I opened #263. I also just posted my thoughts there on how drag'n'drop between file-sections could be implemented to solve this.

Please let me know what you think.

**Comment by bastianallgeier** [comment]
I'm closing this for the more general ticket to enable drag & drop between sections again: https://github.com/k-next/kirby/issues/554
