### ISSUE TITLE
[Panel] Select a position options

### ISSUE THREAD

**Issue by meszarosrob** [getkirby/kirby#407]
Having 5 published pages

![image](https://user-images.githubusercontent.com/6097856/38675164-7e6284ae-3e5f-11e8-9b0f-6b4b7cedd69d.png)

I get this options for the select

![image](https://user-images.githubusercontent.com/6097856/38675198-9733a634-3e5f-11e8-9f0d-f1c2fbf46ebf.png)

Two things:

1. I find it rather difficult to understand why the the options are not in the following format "1 - Oceans are quite nice" - meaning the position number and the title of the project in the same option. It think it would be easier to comprehend what is going on

2. I find it confusing that the page I try to order does not have the title included in the list For example take a look at the last page (Glowing in the dark tent) that should be after the number 5 and not before it. (Compare the order of the number and the title for the first two pages)

**Comment by distantnative** [comment]
I think you have misunderstood some things:

1. The options are not numbered like "1 - Oceans are quite nice" because the number does not refer to the page "Oceans are quite nice". The number you are selecting is the future position of your current page. The sibling pages are shown to make it easier to understand what the result will be: If you choose the position number 2 that means your current page will go between "Oceans are quite nice" and "Lame light effects". If you would just show a select with the siblings and their current ordering numbers as options, what would happen if I choose "2 Lame light effects"? Will me current page be insert before, after?

2. Also here, the numbers are not concerned with the current ordering numbers. You are choosing the position of your current page, so this is all about how the result (future) will look like. Since all siblings pages will be changed to (as they have to be resorted) it's not really beneficial to show their current ordering numbers.

**Comment by meszarosrob** [comment]
I see. Thanks for the thorough explanation!

**Comment by distantnative** [comment]
No problem! If you have ideas how to improve it visually to make this clearer right from the start, please let us know.
