### ISSUE TITLE
New thumb API: Rate limiting

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#412]
As far as I can tell, the new thumb API doesn't have any rate limiting, meaning that users/IP addresses can request as many thumbs as they want. APIs like this are very "useful" for DoS attacks by doing something like this:

```
http://yourdomain.com/projects/project-a/forrest.jpg?w=300&h=200&crop=true&bw=true
http://yourdomain.com/projects/project-a/forrest.jpg?w=301&h=200&crop=true&bw=true
http://yourdomain.com/projects/project-a/forrest.jpg?w=302&h=200&crop=true&bw=true
http://yourdomain.com/projects/project-a/forrest.jpg?w=300&h=199&crop=true&bw=true
http://yourdomain.com/projects/project-a/forrest.jpg?w=300&h=198&crop=true&bw=true
http://yourdomain.com/projects/project-a/forrest.jpg?w=5000&h=2000&crop=true&bw=true
...
```

This can basically take down the server. So I think we should implement a check that blocks access if the same visitor wants to generate more than a specified amount of thumbs.

**Comment by ralfgoeke** [comment]
Further steps to prevent potential could be to:

- add an option to set max and width dimensions
- add an option for setting a threshold for rounding to even numbers like 100, 200, 300... or 50, 100, 150...

The latter would also prevent us from cluttering the server with a zillion different sizes.
So basically the thumb api would convert 367, 382, 395 to 400 and so on.

**Comment by jenstornell** [comment]
It's the first time I see what the new thumbs API does. Maybe not the right place but I have some questions about it.

- Is it a total replacement of how it works today? I hope not.
- Is it enabled by default? I hope not.
- Are the images cached when doing a url call like that?

**Comment by lukasbestle** [comment]
> Is it a total replacement of how it works today? I hope not.

No. The PHP API will continue to be there and has even been [improved](https://gist.github.com/bastianallgeier/4e486015218cf9cd46c104bf8548791d#new-thumb-api).

> Is it enabled by default? I hope not.

In the current dev version, yes.

> Are the images cached when doing a url call like that?

Yes, like with the PHP thumb API.

**Comment by bastianallgeier** [comment]
There's just no rate-limiting / authentication in the current dev version. For the release I'm planning to have a referer-based block by default with an additional option to add an authentication token for external calls. 

There will also be a new versions feature coming up either in 2.3 or in 2.4, which you can use to define and reuse thumb versions: 

```php
c::set('thumbs.versions', [
  'large' => [
    'width' => 1200,
    'height' => 800,
    'crop' => true
  ],
  'medium' => [
    'width' => 800,
    'height' => 600,
    'crop' => true
  ],
  'small' => [
    'width' => 300,
    'height' => 200,
    'crop' => true
  ]
]);
```

The API can then be setup to only accept those versions. In your templates you will be able to use versions like this: 

```php 
$image->version('large')->url()
```

The API is used internally to replace blocking generation of thumbnails during the first template call. This enhances the perceived performance, is more flexibel and is far easier to replace with external services such as Imgix or Cloudinary. 

You will not notice this however, while building templates. The syntax stays 100% the same, except there are now even more methods. For example setting the width of an image file, will now automatically create/return a modified instance of the image object, which will produce a matching thumbnail url. 

```php
$image->width(300)->url()
// http://yourdomain.com/page/image.jpg?width=300
```

Such a self-hosted image API is of course always slower compared to just using the URL of a real image on the server. That's why the API is only being called once, when the Thumb does not exist yet and redirects to the cached version afterwards. In your templates, Kirby is smart enough to detect existing thumbnails and rewrite the URL before render, to avoid those redirects. 

```
http://yourdomain.com/thumbs/page/image.jpg@width=300.jpg
```

So there are no disadvantages but only performance benefits from the new API. 

The API is also way smarter in organizing thumb files. Each file is stored in a subfolder of thumbs, which will match the path of the page, the image belongs to. This makes it far easier to delete unnecessary thumbnails later and even the panel now cleans up after renaming or deleting pages. 

Additionally the thumb filepaths are no longer bound to your environment. You can upload your entire thumb folder now and it will work out of the box on your server. This means that you can even check in thumbs in a git repo and version controll them. It also means that you can run any kind of additional optimization script, once the thumb has been generated, to further reduce its size. 

Finally, if you don't like any of this, the new Thumb API is now a core component of Kirby, which can be replaced by your own Thumb Engine in a matter of a couple lines of code: 

```php
// plugins/customthumbs/customthumbs.php

class CustomThumbs extends Kirby\Component\Thumb {
  // overwrite the thumb API behavior here
}

$kirby->register('component', 'thumb', 'CustomThumbs');
```

**Comment by lukasbestle** [comment]
Sounds awesome!

One issue however:

> For the release I'm planning to have a referer-based block by default

Since the `Referer` is just a header, you can easily fake it, so it won't protect the API.

**Comment by bastianallgeier** [comment]
@lukasbestle agreed. Then maybe session based. I'm still experimenting with the final authentication method.

**Comment by jenstornell** [comment]
Great replys!

>For the release I'm planning to have a referer-based block by default with an additional option to add an authentication token for external calls.

I don't really care how, but it feels really important to keep external traffic out (404) of the thumb generating urls by default.

Else Kirby is leaking urls. WordPress is leaking urls big time and I don't want that back.

>thumb versions

Now I mention WordPress again, but this is a really nice feature over there, so good news.

>and even the panel now cleans up after renaming or deleting pages.

Yes! Great news!

**Comment by fabianmichael** [comment]
Another way to prevent unwanted external calls to the thumbnail-API could be an approach, that I would call something like an *auth file*. The generating-process for a single image would look like this:

1. A thumbnail is requested from a template through PHP code.
2. The thumb component checks, whether it already exists. If so, it will just return the url to that image. If not, it will also create a file that tells the thumbs API, that a thumbnail of the requested size is going to be requested by the browser and it is allowed to create that size. If the thumbnail file is called `thumb@width=300.jpg`, the auth file could be called `.thumb@width=300.jpg.auth` for example.
3. A HTTP request is made to the thumb API. The thumb component then checks, if there is an *auth* file for the requested thumbnail-size. If so, the requested image will be generated and shown, otherwise the API will refuse to generate that size.

I used this method in an (unreleased) image manipulation plugin for kirby with great success.

**Pitfalls:**

Apache has some strange behavior by looking for similar filenames, when a request is made to a non-existant file. So the *auth* files should probably not be named something like `thumb@width=300.jpg.php`, otherwise a user has to ensure, that both `CheckSpelling off` and `Options -MultiViews` are set, either in the Apache configuration or via `.htaccess` file. The name of the auth file just has to be different enough, so Apache will not redirect to it. I don’t know, how far Apache’s »guessing« algorithm goes, but it should be possible to find out with a few simple tests.

**Comment by bastianallgeier** [comment]
After checking all the issues and rethinking the API. I decided to go back to the original way of generating thumbs, but supported with the new component architecture. I really thought this would be a good idea but it turns out that it introduces more issues than it solves problems. I will write more about it soon.
