### ISSUE TITLE
Image blur - Change value

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#437]
If we are going to have `blur` I think there needs to be possible to change the value. Blur can be a range of values.

**My suggestion**

Set to any value between 0 and 100, like this:

```php
$page->image()->blur(0) // None
$page->image()->blur(50) // 50%
$page->image()->blur(100) // Max
```

**Comment by bastianallgeier** [comment]
yep, definitely makes sense. The blur ratio is not yet implemented well enough in both default drivers. That's why I didn't add it to the blur method so far. But I definitely will in a later version.

**Comment by mrflix** [comment]
FYI I used `$image->blur()` for the first time today and intuitively tried to set the blur amount in pixels as I'm used to with [CSS Filters](https://developer.mozilla.org/en-US/docs/Web/CSS/filter). E.g. `$image->blur(5)` for a 5 pixel blur.

**Comment by bastianallgeier** [comment]
I just added this to the develop branch for 2.4.

**Comment by mrflix** [comment]
Thanks for the quick addition!
My first attempt using this was to pre-render this css blur of 30px on the server:
![30px css-blur](https://cloud.githubusercontent.com/assets/60777/18840543/38eb2ad6-840f-11e6-8ab7-7911f7a2bc87.png)

Unfortunately using the GDLib driver the result of `blur(30)` is quite shallow:
![30px kirby-blur](https://cloud.githubusercontent.com/assets/60777/18840588/5eaf5ea4-840f-11e6-8495-ed5a8a1d99b1.png)

Digging deeper into it revealed a limitation of the php-gd-library:
Kirby's [thumb class](https://github.com/getkirby/toolkit/blob/84530101e95e8ca7ffc4f350b409b7b7c0ce3feb/lib/thumb.php#L346) is handing over the `blurpx` (e.g. blur radius) parameter to SimpleImage's [blur method](https://github.com/claviska/SimpleImage/blob/master/src/abeautifulsite/SimpleImage.php#L174). SimpleImage's blur method calls php's native `imagefilter` method. But instead of handing over the blur-radius to the php function it calls the imagefilter `blur-radius` times:
```php
for ($i = 0; $i < $blurpx; $i++) {
  imagefilter($this->image, $type);
}
```
Why? Because php links to gd's [gdImageGaussianBlur method](https://github.com/libgd/libgd/blob/master/src/gd_filter.c#L615) that doesn't accept a parameter and performs a 1 pixel radius blur. So instead of blurring the image once with a very wide brush `SimpleImage` blurs the image very often with a thin brush. At least with big radius values this leads to very different results.
Reading gdImageGaussianBlur's documentation I stumbled over this gem:

> *NOTE:* You will almost certain want to use
    `<gdImageCopyGaussianBlurred>` instead, as it allows you to change
    your kernel size and sigma value.  Future versions of this
    function may fall back to calling it instead of
    `<gdImageConvolution>`, causing subtle changes so be warned.

Unfortunately a php binding to `gdImageCopyGaussianBlurred` doesn't exist.

The good news: with ImageMagick as the thumbs driver the blur looks as expected.

**Comment by lukasbestle** [comment]
Thanks for testing. There's unfortunately nothing we can do about this as you wrote. :)

**Comment by mrflix** [comment]
Well, what this shows is that the blur method breaks the abstraction of the thumbs driver. The results that should be the same are very different depending on the driver. At the very least the docs should indicate that.
