### ISSUE TITLE
Should Tpl::$data be flushed at some point?

### ISSUE THREAD

**Issue by fvsch** [getkirby/kirby#449]
When rendering more than one page, `Tpl::$data` grows over time. For instance if controller1 sets a `test1` value and controller2 sets a `test2` value, in the next page that has nothing to do with those controllers the template will still have access to those variables with their latest value.

This is why issue https://github.com/getkirby/kirby/issues/448 does not completely break the static build: the variables expected by templates are still defined, but with state values.

Could this create more issues in Kirby or plugin code? If yes, could it be handled by flushing `Tpl::$data` at some point? Or is this something that will only or mostly affect the StaticBuilder plugin and that I should try to manage there?

**Comment by fvsch** [comment]
For the record the Template component does:

```php
tpl::$data = array_merge(tpl::$data, $data);
```

So I did the same thing in the Twig template component. If I change it to `tpl::$data = $data;`, it effectively resets the template data for each page render, and page rendering fails like it should in #448 (instead of “succeeding” with stale data).

Is there a reason for merging with previous data instead of just replacing it?

**Comment by lukasbestle** [comment]
The reason is that `tpl::$data` allows to set global template variables from plugins or other user components, so Kirby must preserve what is currently in this array instead of just overwriting it completely.

It is bad here because you are rendering multiple pages per request. This is not the normal use-case, so it probably hasn't been considered.

I have created a fix for this in #450.

**Comment by lukasbestle** [comment]
Fixed in 2.3.1.
