### ISSUE TITLE
helper for loading from dotenv in config files

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#463]
just a suggestion... 
maybe you could add a helper to load sensitive data for config files from dotenv file so they can never be published to github etc (kirby could ship with a gitignore file doing that). this lib seems like a good choice.

https://github.com/vlucas/phpdotenv

**Comment by lukasbestle** [comment]
We had support for `.env` before, but we dropped it in the latest alpha release because of security reasons: Files named `.env` are accessible via HTTP as the common web servers like Apache and nginx don't block access to them by default.

As we wrote in the [changelog](https://www.notion.so/getkirby/Alpha-10-45d42e49740648d48f3fd0c7af62ca15#6f7304de9e83414989f982bb88315652), support for `.env` would be better suited for a plugin.
