### ISSUE TITLE
Outside click does not work in structure field to close

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#465]
![image](https://user-images.githubusercontent.com/927011/40346141-24ddff60-5d9c-11e8-8c0f-5297430f0fce.png)

The first thing I did was to try to click outside the modal to close it. It did not work. It's a really common UX pattern to click outside of modals to close them.

**Update:**

I just noticed that I can click around on the other rows even when they are dark. Nice feature but not expected. I'm not sure if it should be darken out at all. Everything clickable should probably be fully visible?

**Comment by H-i-red** [comment]
Yes, I tried the to click outside as well. Remove the dark background. No need to "fake" modals when we don´t need them ;). Perhaps add some more spacing or set a different background color to the "structure-item". Also noticed this, when you click on another structure, the old structure is still active and displayed.. Also The "autoclose collapse thing", sometimes and perhaps most of the times you want a overview of all data.. So manually close the structure item instead of auto close upon clicking on other structure. It safes time and "CLICKS".. hmm i perhaps second that.. all the data is already displayed in the "item-content".. Cool !!

Anyway just suggestions, great work !!

![skarmavbild 2018-05-22 kl 13 44 52](https://user-images.githubusercontent.com/19476159/40361441-a2a1114e-5dc9-11e8-9a01-c6d737017c44.png)

**Comment by bastianallgeier** [comment]
✅

**Comment by REHvision** [comment]
I'm still experiencing this behaviour in Alpha 11. When one item inside a group is opened and another is clicked it correctly switches the item really nicely. But when clicking on an item in another group (like in the restaurant menu) they both stay open and they overlay/darken each other. I would also expect an outside click on the backdrop (like with most modals) to close it again :wink:

**Comment by bastianallgeier** [comment]
✅
