### ISSUE TITLE
Fallback for error page

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#488]
In Kirby 2...

## White screen of death on deleted error folder

I deleted the `error` folder in the content folder. The panel seems to work like normal, but the error pages on the site did just show a "white screen of death" with a 200 success code.

## No error folder, no fallback

I would expect that a missing error page would mean a fallback to the `error` template (what I was hoping for) or at least the `default` template. It seems like it don't fallback at all.

## Error messages needed, but not always controlled by the panel

Maybe you can fix this at some point in Kirby 3. We need an error message on site errors, but we don't always need that to be setup in the panel.

Now, it may seem simple to just setup the error as panel page, but if we don't really need it, it's a bit of an overhead. We need to create a folder in content that we don't need. We also need to create a blueprint only to make it hidden in the panel. So I need to add things to remove things.

If virtual pages will fix this issue, you can close it.

**Comment by lukasbestle** [comment]
> I deleted the error folder in the content folder. The panel seems to work like normal, but the error pages on the site did just show a "white screen of death" with a 200 success code.

That should indeed not happen. We should definitely have a fallback, at least a plain text "Not Found" message with HTTP 404. I don't think we should polish that fallback page though (like with custom CSS). It's a fallback after all.

> Maybe you can fix this at some point in Kirby 3. We need an error message on site errors, but we don't always need that to be setup in the panel.
> 
> Now, it may seem simple to just setup the error as panel page, but if we don't really need it, it's a bit of an overhead. We need to create a folder in content that we don't need. We also need to create a blueprint only to make it hidden in the panel. So I need to add things to remove things.
> 
> If virtual pages will fix this issue, you can close it.

To be honest, I don't think there is any kind of overhead here. It's just a required part of the CMS and it has always been one. The error page *is* content, so it makes sense to have that page.

The issue is that each additional feature and configuration variant will actually *add* overhead to the CMS and not remove it. That's why I think we should keep it simple :)

**Comment by bastianallgeier** [comment]
✅ Kirby now fails gracefully when there's no error page and shows a sad smily and returns a 404.
