### ISSUE TITLE
[Ui] Date and time fields: custom formats

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#492]
There seems to be no way to change the date and time formats in the panel, it's always following the German standard notation:

![bildschirmfoto am 2018-06-08 um 10 11 00](https://user-images.githubusercontent.com/25466/41146635-42de2538-6b04-11e8-8db6-f2f240b7ec81.png)

How would I change this to `2018-06-08` for example?

**Comment by distantnative** [comment]
Indeed at the moment it is only supported to set the format that ends up in the content file.
Would be a feature to also support a different format for the panel field.

**Comment by nilshoerrmann** [comment]
I'm not sure how far we are from custom formats: but would it be possible to use a more international date format in the meantime (like ISO 8601: `YYYY-MM-DD`)?

**Comment by distantnative** [comment]
From custom formats still a bit far. Still missing the right idea how to structure all the HTML etc. based on just a simple format string (which could entail so many things to consider).

But I have switched the inputs to display as `YYYY-MM-DD` in the meanwhile as you suggested, since it is indeed a much more international variant.
