### ISSUE TITLE
[Panel] Basic authentication breaks panel access

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#498]
Protecting a Kirby 3 install with basic authentication using `.htaccess`/`.htpasswd` breaks the backend:

![bildschirmfoto am 2018-06-12 um 11 12 40](https://user-images.githubusercontent.com/25466/41281393-8c681580-6e31-11e8-89b8-49d997d429e6.png)

It looks like Kirby is trying to use the basic authentication credentials to log the user into the panel but this only works if you've set up all the Kirby users in your `.htpasswd` as well. This would require me to know the users' passwords which – of course – is not desired.

### Expected behaviour

It's a nice feature to try to use basic authentication to log the user in. But if it fails, I'd expect the panel to show the default login so I can login manually.

**Comment by lukasbestle** [comment]
That's actually not an intended feature. Well, not entirely at least.

It looks like the browser submits the Basic auth credentials on every request, even those we submit via `fetch()` from the frontend JS code. If Basic auth *and* a session is given, our backend API code will prefer the Basic auth over the session cookie that is also passed in the request. That's useful for CLI use-cases where you don't want to get a session token first but simply want to authenticate using username and password.

We need to verify that my theory about the browser sending the Basic auth for `fetch()`requests is correct, I unfortunately can't test that at the moment.

If that's indeed the case, I see three possible solutions:

- Try to find a solution to make `fetch()` ignore the Basic auth from the `.htpasswd` auth prompt and not pass those credentials for API requests. Not sure if that even works though, as Apache will then block those requests as they are not authenticated.
- Remove support for API requests with Basic auth entirely.
- Switch to a custom header for Basic credentials for the API.

**Comment by distantnative** [comment]
I would assume `fetch()` indeed includes the Basic Auth every time to reach APIs behind a site protected by `.htaccess/.htpasswd`.

I have little knowledge in the area, but do you think setting the `credentials` parameter on `fetch` to `omit` could work?
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Parameters

**Comment by lukasbestle** [comment]
The issue is that Apache will then block the request entirely as only those requests will be allowed that pass the `.htaccess/.htpasswd` check. If our `fetch()` requests don't include those credentials, it's not going to work. Therefore users would need to disable the `.htaccess/.htpasswd` protection for the API endpoints, which is a bit confusing.

The solution I'm currently considering most is a custom header like `X-Kirby-Auth` that looks just like the `Authorization` header. On the backend we would need to adapt [the user detection code](https://github.com/k-next/kirby/blob/3.0-alpha-10/src/Cms/AppUsers.php#L125-L131), in the Panel just the [header name](https://github.com/k-next/kirby/blob/develop/panel/src/api/auth.js#L14).

The only question is if we should still allow the `Authorization` header or if we should only ever support our own custom header. The latter would be a lot more robust as it avoids edge-cases, but the custom header is also a custom behavior that API clients need to support and we therefore need to document. It also makes it more difficult to "just pass" the username and password when sending an API request using `cURL` as you would need to do the conversion to Base64 yourself. :(

**Comment by distantnative** [comment]
Could we easily provide small libraries for our APIs to be used by developers where we cover these issues? E.g. my idea would be to bundle the JS api files we use in the panel as some sort of library for developers then to use e.g. in their front-end API call based projects.

**Comment by nilshoerrmann** [comment]
> E.g. my idea would be to bundle the JS api files we use in the panel as some sort of library for developers then to use e.g. in their front-end API call based projects.

Independent of a solution to the authentication issue this would be very much appreciated.

**Comment by lukasbestle** [comment]
+1 for API official wrapper libraries! Those would definitely be helpful for devs.

But unfortunately they are not going to solve the issue completely as my proposed solution would make it harder to use dev tools like cURL or Paw where an API wrapper library can't be used.

Do you have any other ideas how we could solve this Basic auth issue?

**Comment by bastianallgeier** [comment]
✅ should be fixed in the next nightly build
