### ISSUE TITLE
[Cms] Change str::slug to support swedish and other languages

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#519]
With `str::slug` the word `Bytesrätt` gets translated to `bytesraett` where `ä` is translated to `ae`.

To make this right, you may need to include a bigger library like: https://github.com/cocur/slugify

**They have a great example of just my case and it looks like this:**

```php
$slugify = new Slugify(['rulesets' => ['default', 'turkish']]);
$slugify->slugify('ä'); // -> "a"
```

With Kirby syntax it could look like this:

```php
echo str::slug('Bytesrätt');
echo str::slug('Bytesrätt', ['rulesets' => ['turkish']]);
```

The second argument is the same as Slugify, so it's just a wrapper. It will work for all arguments.

For even more advanced things with Slugify, we could use their class directly. Best of both worlds?

**Comment by nilshoerrmann** [comment]
Having transliteration settings for each language like Slugify provides is a great idea. I remember having long discussions about this in the Symphony CMS community a few years ago which pointed out a few things the CMS has to manage: 

- The user language may not be used to determine which transliteration rules should be used because a) the user language might differ from the site language and b) users with different language settings would create different slugs.
- Page content has to be taken into account when choosing rules: an entry in Swedish needs different treatment than an entry in German (see the `ä` umlaut for instance).

So even if a site is not multilingual per se, there is a need for a default language setting.  
And there might be cases where the user wants to change the transliteration settings on the per entry basis.

**Comment by jenstornell** [comment]
If you want to look at alternative(s) to Slugify, I think this seems nice:

https://github.com/ausi/slug-generator

>Some libs carry large rulesets with them that try to convert characters to ASCII, no one uses Unicode’s CLDR which is the standard for transliteration rules and many other transforms. But most importantly no library was able to do the “correct” conversions, like “Ö-Äpfel” to “OE-Aepfel” for German or “İNATÇI” to “inatçı” for Turkish.

```php
$generator->generate('Hello Wörld!');                        // Result: hello-world
$generator->generate('Hello Wörld!', ['locale' => 'de']);    // Result: hello-woerld
$generator->generate('Hello Wörld!', ['locale' => 'en_US']); // Result: hello-world
```

### My plugin workaround

By the way, I needed to work around this issue in my latest plugin: https://github.com/jenstornell/kirby-toc#kirbytocslugmethod

```php
c::set('kirby.toc.slug.method', function($heading) {
    return str::slug($heading);
};
```

In the future, I hope to deprecate this option.
