### ISSUE TITLE
Broken default routes in multi language setups

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#541]
Before 2.4.0 url’s without the language prefix would rout to the requested page in the default language. For example www.foo.com/bar would show the content of www.foo.com/nl/bar. With the site updated to 2.4.1, url’s without the prefix are routed to the landing page. For example www.foo.com/bar would redirected to www.foo.com.

**Comment by martinrisseeuw** [comment]
I went back to 2.3.0 because of this issue only I think the behaviour in combination with language detection should be different. If I'm right, the current behaviour is:

- url/subpage serves the right page to the user in the default language

Expected behaviour:

- url/subpage checks for browser language and redirects to the right page url/nl/subpage i.e

When I initialy load the homepage Kirby servers me the right language that is detected, nl in my case. But when I browse to url/subpage it goes to the default language (en) and when I return to the homepage the language suddenly became english. 

Do you have a suggestion how I can temporary fix this untill you have a solution? @bastianallgeier

**Comment by lukasbestle** [comment]
We will take a look at this in one of the next releases. :)

**Comment by lukasbestle** [comment]
The language detection only happens on the homepage, not on specific page URLs as that would cause issues if the default language is set to be at the domain root (`/`), which is often the case. We might consider this in the future, but for Kirby 2 it's a too large change.

However I have fixed the redirection so that `http://example.com/projects/project-a` redirects to `http://example.com/en/projects/project-a` instead of to the default language's homepage if the page exists.

**Comment by martinrisseeuw** [comment]
@lukasbestle thank you for this fix. Do you have a suggestion how I could work around and reach the wanted behaviour? Or should I make to many changes in the Kirby core?

**Comment by lukasbestle** [comment]
You mean the language detection on subpages? Basically you would need to copy the [language detection code](https://github.com/getkirby/kirby/blob/d5e3c9aa37dbdd9daf070d3913280d1c568325cc/kirby.php#L247-L275) into the [fallback route](https://github.com/getkirby/kirby/blob/d5e3c9aa37dbdd9daf070d3913280d1c568325cc/kirby.php#L361-L368) and adapt it to work with the subpage URIs. If you don't want to modify the Kirby core, it should be possible to override this route in your `config.php` file.

**Comment by martinrisseeuw** [comment]
@lukasbestle Thanks for the help. Yes I mean language detection on subpages. I am a bit stuck with overriding the route. I have to say may experience on this part of Kirby is quite little. Could you maybe give some extra pointers on how to achieve this? I would prefer to do it outside the core with updating in mind.

**Comment by lukasbestle** [comment]
You can override the route like this:

```
c::set('routes', [
  [
    'pattern' => '(.*)',
    'method' => 'ALL',
    'action' => function($uri) {
      // your code here
    }
  ]
]);
```

Unfortunately I won't be able to help with the specific implementation as this outside of the scope of Kirby's feature. Of course feel free to ask in case you have any further questions.

**Comment by LeBenLeBen** [comment]
I have a multilang website with no routes at /, only prefixed ones (/fr, /de, /en). I wanted to be able to share links to pages without prefix so it would take the most appropriate one by detecting the user preferences. If that is of any help:

```php
function getAppropriateLanguage() {
  if ($sessionLanguage = site()->sessionLanguage()) {
    return $sessionLanguage->code();
  } elseif ($detectedLanguage = site()->detectedLanguage()) {
    return $detectedLanguage->code();
  } else {
    return 'en';
  }
}

c::set('routes', array(

  /**
   * Try to redirect URLs to pages without language prefix to the one with prefix
   * Use user current language or try to detect it
   */
  array(
    'pattern' => '(:all)',
    'filter' => function($route) {
      $languages = site()->languages()->toArray();
      $path = detect::path();
      $fragments = url::fragments($path);
      $locale = $fragments[0];

      // The URL already includes the language, nothing to do here
      if (in_array($locale, $languages)) {
        return false;
      }

      // We do care only about pages, don’t override custom routes
      $page = page($path);
      if (!$page) {
        return false;
      }

      return true;
    },
    'action' => function($url) {
      return go(getAppropriateLanguage() . '/' . $url);
    }
  ),

));
```

**Comment by martinrisseeuw** [comment]
This works great! Thanks a lot @LeBenLeBen

**Comment by martinrisseeuw** [comment]
@LeBenLeBen 

I'm running into an issue when using url keys for different languages. I have an example on this website:
http://secridnl.martinr.nl/

1. When you navigate to http://secridnl.martinr.nl/leather it works correctly in english. But when you try it in dutch it doesn't. The url key of dutch is /leer. 

The expected behaviour would be: if my preferred browser language is dutch and I would navigate to  http://secridnl.martinr.nl/leather that I redirect towards http://secridnl.martinr.nl/nl/leer.

Is this a problem you had as well and did you solve it? Or do you have some suggestions on how to adjust the code?

**Comment by LeBenLeBen** [comment]
@martinrisseeuw Indeed, this case is not covered. I tried to do it differently but I was not able to find the corresponding page with the localized slug 😞
