### ISSUE TITLE
[Panel] Tag field: don't display empty row

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#562]
This looks weird:

<img width="881" alt="bildschirmfoto 2018-07-06 um 08 38 19" src="https://user-images.githubusercontent.com/25466/42363507-4110a1ea-80f8-11e8-9071-c83fc694b2d5.png">

I'd expect the tag field to only grow in height when there in not enough space.

**Comment by distantnative** [comment]
As background: It happens cause after the tags there is an "invisible" `<input>`, so that you can click and enter a new tag.

So we will not get around this look while entering a new tag. But I was thinking that maybe we can hide the inout (and thus remove the extra line) as long as the field is unfocused.

**Comment by nilshoerrmann** [comment]
But isn’t there enough space to keep the input on the first line in this case until the new tag gets too long?

**Comment by bastianallgeier** [comment]
✅
