### ISSUE TITLE
Content representations don't work if a corresponding php template is not present

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#612]
What - if any - is the reason why a standard php template has to exist for content representations to work?

**Comment by lukasbestle** [comment]
The issue is that you always need a "fallback template" for other representations. Let's say there is a JSON representation but the user requests a HTML or XML representation. What to do?

If a page is only ever requested in JSON, there is no need to use the representation feature at all. In this case the JSON output can be generated from the template directly. Same for every other possible format.
