### ISSUE TITLE
$arguments ist never used

### ISSUE THREAD

**Issue by chpio** [getkirby/kirby#659]
https://github.com/getkirby/kirby/blob/a0ab4f5cdaced5bced734bdca9e9cc24f0e473a5/core/content.php#L120-L132

**Comment by lukasbestle** [comment]
You are right! I think the second argument is there because the `__call()` method passes its arguments on, but if the `$arguments` are never used, that doesn't make any sense of course.

I just verified whether we have the same issue in the upcoming release, Kirby 3. We fixed it there already. Anyway, thank you very much for reporting this issue. :)
