### ISSUE TITLE
[Panel] Implement if/else in `pages` info-field

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#675]
This was mentioned by someone in the last screencasts comment section. And actually I like the idea of having the "template language" of these info-fields a little more capable.

**Comment by rasteiner** [comment]
I'd like to add somthing to the discussion: 
I don't know how much is too much, but consider the [inner-platform effect](https://en.wikipedia.org/wiki/Inner-platform_effect). Bringing about `if statements` also brings up:
 - boolean logic and operators (`&&`,  `||`, `(`, `)`, `!`)
 - comparative operators (`>`,  `<`, `>=`, `<=`, `==`, `!=`)
 - need to check what is "truthy" (is an empty field true or false? Is it only false if it's not declared in the blueprint?)
 - why not introduce math expressions? 
 - nested if statements? 
 - escaping control chars?

So, before beginning to introduce control logic into yaml strings, consider the use of page models or custom page methods in blueprints:

instead of having:

> blueprint:
> ```yaml
>   info: '[if page.name.isNotEmpty]{{page.name}}[else][if page.artistName.isNotEmpty && page.albumName.isNotEmpty]{{page.albumName}} \[{{page.artistName}}\][else]{{page.title}}[endif][endif]'
> ```


have:

> blueprint:
> ```yaml
>   info: "{{page.info}}"
> ```
> 
> pagemodel:
> ```php
> class DefaultPage extends Page {
>   public function info() {
>     return $this->title();
>   }
> }
> class MusicPage extends Page {
>   public function info() {
>     return "{$this->albumName()} [{$this->artistName()}]";
>   }
> }
> class ActorPage extends Page {
>   public function info() {
>     return $this->name();
>   }
> }
> ``` 

(Yes, I know it's longer).

**Comment by jenstornell** [comment]
A php solution may be more reliable, but the downside is that it's probably not aware of things happening live in the panel. We need to save or refresh the page for the changes to appear, or use ajax.

**Comment by wottpal** [comment]
@jenstornell You mean when a second panel-tab is opened and the page is edited in there? If yes, this is already the case when you edit for example the page-name.

👍 for @rasteiner's approach! Would also be much easier to implement I guess.

**Comment by bastianallgeier** [comment]
The biggest problem for us with added logic to template strings is the performance hit. Parsing those strings would get a lot more complex and thus slower. It would also increase the bug potential massively. I totally agree with @rasteiner's suggestion to put this into modals if necessary.

**Comment by rasteiner** [comment]
Maybe just a kind of _null coalescing operator_ (`??`) and not a fully fledged if statement:

```yaml
info: "{{page.name ?? page.author ?? page.date ?? page.title}}"
```
(split on `??`, then execute the queries from left to right until a non empty string is found)

might be more feasible :)

**Comment by wottpal** [comment]
@rasteiner's idea with a static fallback as last option would be completely sufficient for my needs ;)  The fallback could be displayed in italic for example.

```yaml
info: "{{page.name ?? page.author ?? 'No name given'}}"
```
