### ISSUE TITLE
[Panel] Save-Bar not in the viewport on iOS Safari (iPad)

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#682]
Sometimes it is inside the viewport and disappears after some scrolling and sometimes it's gone right from the page-load. Strange.
![image-1](https://user-images.githubusercontent.com/3930150/42817274-ed001d40-89cd-11e8-8afd-0adb6226a61a.jpg)

**Comment by SebastianEberlein** [comment]
This happens because iOS handles viewport units a little different: 100vh is the height of the viewport when the Safari browser UI is "hidden":

![s](https://user-images.githubusercontent.com/15672385/42826200-20939ed2-89e4-11e8-9f33-6baa5ce4aeab.png)

Since the panel height is set to 100vh, the save bar is inaccessible when the Safari browser UI is still visible.

The form elements are inside an element with `-webkit-overflow-scrolling: touch;`. So you only scroll inside that element and not the entire website. And therefore you never reach the "hidden" Safari UI state.

To make the save bar reappear, try starting the scroll gesture on the black bar at the top. Then you scroll the entire website.

**Comment by wottpal** [comment]
Just in time :)

https://css-tricks.com/the-trick-to-viewport-units-on-mobile/

**Comment by bastianallgeier** [comment]
✅
