### ISSUE TITLE
[Panel] Preview mode

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#69]
@bastianallgeier 
> Instead of opening the site in a new window, a preview iframe should open on the right hand side and react to changes in the form immediately. This would result in a far better user experience while editing pages.

**Comment by jenstornell** [comment]
https://github.com/jenstornell/kirby-reveal/

Agree! Something similar to Kirby Reveal.

**Comment by distantnative** [comment]
In the iframe, loading a version of the site that does not load from the normal content file, but the auto-saved draft file. On input changes in the panel, iframe is reloaded with persistent scroll position across refreshes.

**Comment by tobiasfabian** [comment]
This feature doesn’t sound essential to me. Kirby should focus on the core features. Such additional things should be handled by plugins.

**Comment by jenstornell** [comment]
I think it can be nice to have it built in but I don't want it in the first Kirby 3 release. Take your time with it.

## Prevent blink

With my releval plugin, I noticed that every time the iframe updates there was a blink, caused by the iframe refresh time it takes for the iframe to load. I solved it in the reveal field to use two iframes on top on each other. When the iframe updates, it update the iframe in the back and after fully loaded it switch place on the iframes and put the fully loaded back iframe on front.

## Routes

Be aware that routed pages can be a problem.
