### ISSUE TITLE
[Panel] Make the headline field more visible

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#701]
## Where is the headline?

Can you find the headline from the headline field in this image? You probably can, but it's quite shy.

![image](https://user-images.githubusercontent.com/927011/42923745-76bd40f8-8b27-11e8-966b-fa59000b4860.png)

## Make the headline pop

To really make the headline stand out compared to the field labels, make it a bit bigger. I used `1.5em` for this:

![image](https://user-images.githubusercontent.com/927011/42923728-5ab9f694-8b27-11e8-9eed-7d63c2d2ed64.png)

**Comment by luxlogica** [comment]
IMHO, the 'divider line' underneath the headline is also often not helpful - specially when the section underneath the headline might have divider lines (= line fields) of their own. Having a divider line _above_ the headline might make for a more logical separator.

But ultimately, I'd rather have a larger headline with **NO** divider by default, and have an *option* to add a divider line before/after/none .

Other options that could make the headline field even more useful would be to add an icon (which I'd often prefer rather than numbers), and to be able to have headlines of different sizes - ie., 'main' and 'sub' headlines:

```
pageSettings:
    label: Page Settings
    type: headline
    icon: page
    divider: above
    level: main 
```

**Comment by jenstornell** [comment]
@luxlogica 

I agree about that the line is not needed and that it would make more sense to put it above... But it would be kind of hackish. There is already a field for a line (https://getkirby.com/docs/cheatsheet/panel-fields/line) so I think just removing in from the headline field would be good.

Icon support could be nice as well. I've not seen it in action but it sound good.

All of a sudden this issue became three issues in one. =)

**Comment by bastianallgeier** [comment]
![bildschirmfoto 2018-07-23 um 16 19 59](https://user-images.githubusercontent.com/24532/43082407-474a2adc-8e94-11e8-9b6a-23e505fdb962.png)

The icon and line options sound great, but is something for later.
