### ISSUE TITLE
[Cms] Implement session CSRF token

### ISSUE THREAD

**Issue by mzur** [getkirby/kirby#791]
As @bastianallgeier pointed out in Slack, Kirby 3 does not use a CSRF token anywhere yet. However, this is a mandatory security feature for any state changing requests, as the [same origin policy does not prevent CSRF attacks](https://stackoverflow.com/questions/33261244/why-same-origin-policy-isnt-enough-to-prevent-csrf-attacks).

I intended to implement this and send a PR. But I found that there already is something called a token in the [Session](https://github.com/k-next/kirby/blob/9c20612208655c55f811fd105d79f57123e3abe2/src/Session/Session.php) class. I believe this token is the session ID, is that right? How do you want the CSRF token to be implemented then? Just choose a different name?

**Comment by lukasbestle** [comment]
That is correct. We chose the name `token` as the token itself is made up of the expiry time, the actual ID and a key.

The CSRF protection shouldn't be part of the `Session` classes, but instead part of the API. So naming shouldn't conflict with the `token` of the session.

**Comment by mzur** [comment]
> The CSRF protection shouldn't be part of the Session classes, but instead part of the API

The CSRF token _verification_ certainly but are you sure about generating/storing the token? I usually look at Laravel for these kinds of things as it follows security best practices and is generally well written. They handle the token [in their Session class](https://github.com/laravel/framework/blob/20e84191d5ef21eb5c015908c11eabf8e81d6212/src/Illuminate/Session/Store.php#L605). This would be useful for things like my Uniform plugin, too (which is why I want to have a CSRF token built in to Kirby after all). Uniform has nothing to do with the API.

**Comment by lukasbestle** [comment]
I haven't read the whole Laravel source code, but because that class only has two CSRF methods that generate and return the token respectively, I'd assume that the CSRF token code is only part of the Session class because CSRF protection is related to sessions.

If that's the reason, then what they are building is one class that does two things. But that's not a good practice. It makes implementation for users simpler, but also adds quite a bit of opinionated logic if you fully go that direction. Remember: The token needs to be verified on every request, so it needs to be sent on every request. But how to put it into the markup of every page? Add it as a query param to every link? That doesn't make sense and for some requests (those that don't modify state) the token isn't even needed.

You see: This can never be fully automatic. So I think it makes sense to keep this separate from the session implementation, which does one thing and does it well. I actually think that the implementation in v2 makes a lot of sense. A tiny helper that generates a token and stores it in the session as a normal piece of session data.

**Comment by mzur** [comment]
> A tiny helper that generates a token and stores it in the session as a normal piece of session data.

Sure, if that's the way you want to go, I won't complain. Is there already a place for helpers like these somewhere?

**Comment by lukasbestle** [comment]
That would be this file: https://github.com/k-next/kirby/blob/master/config/helpers.php (sorted alphabetically)

I think the v2 implementation should already be pretty good, of course adapted to the PSR-2 style and with something like `App::instance()->session()->set('csrf', $token)` and `get('csrf')` respectively.

If you want to help with this that's great, otherwise I will implement it tomorrow afternoon.

**Comment by mzur** [comment]
Go ahead, I won't be able to take care of this before tomorrow.

**Comment by lukasbestle** [comment]
✅
