### ISSUE TITLE
[Cms] Smarter Default Sorting

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#856]
`A`-`Ä`-`B`-... (umlauts)
`1`-`2`-`10`-`20`-... (numerical)
`IMG0.png`-`img1.png`-`IMG2.png`-... (ignore case)

Thread on Slack: https://getkirby.slack.com/archives/CBN859614/p1533562910000490

**Comment by lukasbestle** [comment]
@wottpal @bastianallgeier We had that as the default in our first refactored version of the `sortBy()` method in v2, which we had to [revert in Kirby 2.5.10](https://getkirby.com/changelog/kirby-2-5-10) because it turned out to be massively unreliable (its behavior is inconsistent depending on the available PHP modules and locales).

So I'm pretty sure we can't make natural sorting the default. We can however offer it as an option so that it can be used in case the server is configured correctly.

**Comment by wottpal** [comment]
This sounds like you've tried it with the built-in natural sort of PHP? Couldn't you handle a bunch of special cases (esp. Umlauts, because obviously the majority of Kirby users is German I guess) with a custom sorting method. This should work everywhere then, right?

**Comment by manuelmoreale** [comment]
> because obviously the majority of Kirby users is German I guess

Pretty sure this is not really the case.

I think have this as an option would be a nice addition.

**Comment by lukasbestle** [comment]
> This sounds like you've tried it with the built-in natural sort of PHP?

Yes. PHP natively supports the flag `SORT_LOCALE_STRING`, which works quite well in general as it respects the current locale. And because every locale has its own sorting rules, this makes it work with multilang sites without any modifications.

But as I said: The native function is apparently not reliable enough to be used on server setups we can't control (meaning the ones of our customers).

> Couldn't you handle a bunch of special cases with a custom sorting method?

That would get very, *very* complex. Localization is very tricky and implementing it for only one language isn't really optimal as we also have many non-German customers. Also the performance of an implementation in user-space can be quite bad for something as complex as this. Keep in mind that sorting is used in a lot of places throughout the system.

If anyone has an idea how to implement the native locale sorting flag reliably, please get in touch. That solution would be awesome if it worked well.

**Comment by wottpal** [comment]
You are completely right @lukasbestle! I guess it then should be up to the developer to set up the server correctly and then activate locale sorting in the `config`.

**Comment by bastianallgeier** [comment]
✅
