### ISSUE TITLE
[Cms] Thumbnails does not always load in a good way

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#962]
On the first load I see images that does not work.

If I right click and choose "Show image in new tab" it works. Then if I reload the page it works. If I open the page in another browser after the first load it also works.

![image](https://user-images.githubusercontent.com/927011/45476104-67ac4a80-b73e-11e8-9bde-ce87a490ab0a.png)

I'm not sure why it happends but it feels very shaky and I would prefer to disable this new way of loading thumbs.

Anyway, I have a theory. It's that it uses browser cache on an image that has not yet been rendered. My htaccess looks like below.

```text
<IfModule mod_deflate.c>
AddOutputFilterByType DEFLATE text/plain
AddOutputFilterByType DEFLATE text/html
AddOutputFilterByType DEFLATE text/xml
AddOutputFilterByType DEFLATE text/css
AddOutputFilterByType DEFLATE text/javascript
AddOutputFilterByType DEFLATE application/json
AddOutputFilterByType DEFLATE application/javascript
AddOutputFilterByType DEFLATE application/x-javascript
</IfModule>

<IfModule mod_expires.c>
ExpiresActive On
ExpiresDefault "access plus 10 days"
ExpiresByType text/css "access plus 1 week"
ExpiresByType text/plain "access plus 1 month"
ExpiresByType image/gif "access plus 1 month"
ExpiresByType image/png "access plus 1 month"
ExpiresByType image/jpeg "access plus 1 month"
ExpiresByType image/svg+xml "access plus 1 month"
ExpiresByType application/javascript "access plus 1 week"
ExpiresByType application/x-icon "access plus 1 year"
</IfModule>
```

## Possible solution

Add an option to disable this way of loading thumbs which will then go back to the old way.

## UPDATE: Too many redirects

I saw an error message just before the image was loaded when I right clicked and selected "Open image in new tab".

>Error: Too many redirects

After like 1-2 seconds the image was loaded correctly.

**Comment by lukasbestle** [comment]
In my opinion we should rather fix the issue instead of providing an option to disable the feature. After all it's a very useful feature and implementing more options makes everything *more* complex, not less complex.

> Error: Too many redirects

Was that a browser error or a different kind of error? Did it load automatically after 1-2 seconds or after you manually reloaded the URL of the image again?

Please disable your caching rules while we are debugging this to avoid any additional side effects and also to rule out that they play a role in this issue.

**Comment by jenstornell** [comment]
I saw this message in my developer tool console:

```js
Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
```

When I "Show image in new tab" it goes to an error page and then resolve the problem and show the image.

**Comment by SebastianEberlein** [comment]
Could this be related to [this issue](https://github.com/fabianmichael/kirby-imagekit/issues/9) from Kirby Imagekit?

**Comment by bnomei** [comment]
i am also having this issue. mampro apache localhost and online with apache.

the thread @sebastianeberlein linked is more or less about issues with nginx but maybe @fabianmichael did some magic for apache as well.
afaik the problem is the expireheaders sent before thumb creation cause the browser to cache and render a still non existing image.

**Comment by bastianallgeier** [comment]
✅

**Comment by sonicoder86** [comment]
@bastianallgeier what was the solution for the problem?

**Comment by bastianallgeier** [comment]
@vuesomedev we solved this with better media URLs that take care of cache busting.
