### ISSUE TITLE
[Panel] Dialog Logic

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#971]
While looking at the latest commits I noticed the following lines:

https://github.com/k-next/kirby/blob/3e70bfe3925b0959965d843a352bf7b0fd986a33/panel/src/ui/components/Navigation/Dialog.vue#L19-L26

Shouldn't line 21 have a double pipe, like so: `{{ "Cancel" || t("cancel") }}`?

**Comment by bastianallgeier** [comment]
No. This is correct. The single pipe in Vue.js is the notation for a filter. The Cancel button is being translated if a translation exists and otherwise the fallback "Cancel" is used. The text for the submit button can be modified via a prop. That's why we use the double pipe there to fall back to the confirm translation if the prop is not set.

**Comment by nilshoerrmann** [comment]
Thanks – wieder was gelernt :)
