### ISSUE TITLE
[Panel] Selecting Suggestions

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#974]
Selecting suggestions in tag fields works unexpectedly:

- clicking a suggestion in the dropdown doesn't select the option
- keyboard navigation is unclear

When only having one option in the dropdown list I'd expect the interface to use the suggested text on pressing `enter`. But the interface dismisses the suggestion and approves my manually typed input leaving me with half finished content. I'm not sure if it's just me, but this feels counter intuitive although I see some of the reasoning behind the behaviour.

When trying to select an item in the dropdown list using the keyboard, `arrow down` jumps in the middle of the list instead of starting at the first item.

The current behaviour is a bit puzzling :)

**Comment by bastianallgeier** [comment]
I enhanced the keyboard navigation and items are now clickable. But I don't agree that the first item should automatically be selected. 

Let's say you enter two or three letters and the autocomplete gives you a couple results, but not an exact match. How would it be clear that you want the first entry instead of those three characters you've entered?
